### ISSUE TITLE
No examples to follow up ListObjectsArgs.builder() with maker, keyMarker, continuationToken and versionIdMarker

### ISSUE THREAD

**Issue by Nayananga** [minio/minio-java#1010]

**Comment by kannappanr** [comment]
@Nayananga All of these are defined in the S3-spec

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html

For basic listobjects, the example is good enough

For advanced options, I think it is straight forward to add valid input for your test case. Closing this issue right now, Please feel free to reach out to us if you have further qustions
