### ISSUE TITLE
How to get multi-level directory's objects by Api 

### ISSUE THREAD

**Issue by 66545shiwo** [minio/minio-java#1024]

**Comment by 66545shiwo** [comment]
I can list objects by bucket name but it does not  support by multi-level directory

**Comment by balamurugana** [comment]
@66545shiwo what do you mean by multi-level directory? However please refer provided examples in [listobjects() API](http://minio.github.io/minio-java/io/minio/MinioClient.html#listObjects-io.minio.ListObjectsArgs-) and reopen this issue with appropriate detail.

**Comment by 66545shiwo** [comment]
Sorry , I am working hard on my English .
I make a bucket named "my-bucket" , and I create a folder "my-bucket/my-folder" . 
How can i list objects by the folder "my-bucket/my-folder"

**Comment by balamurugana** [comment]
You could use something like below
```java
 // Lists objects information those names starts with 'my-folder/' 
 Iterable<Result<Item>> results = minioClient.listObjects(
     ListObjectsArgs.builder()
         .bucket("my-bucketname")
         .prefix("my-folder/")
         .build());
```
