### ISSUE TITLE
error code 'XMinioObjectExistsAsDirectory' not supported

### ISSUE THREAD

**Issue by pdesoyres** [minio/minio-java#1027]
When creating a file with the same name of an existing directory, I receive the following exception :

```
Caused by: java.lang.IllegalArgumentException: unknown error code string 'XMinioObjectExistsAsDirectory'
	at io.minio.Xml.unmarshal(Xml.java:68)
	at io.minio.MinioClient.execute(MinioClient.java:1050)
	at io.minio.MinioClient.putObject(MinioClient.java:7582)
	at io.minio.MinioClient.putObject(MinioClient.java:4682)
	at io.minio.MinioClient.putObject(MinioClient.java:4881)
```

using :
- java API 7.1.0
- min.io RELEASE.2020-07-20T02-25-16Z

**Comment by vadmeste** [comment]
@pdesoyres this is one of the few shortcoming of MinIO server. Since files are stored in the disks directly. We cannot have a file and a directory having the same name in the same hierarchy level.

**Comment by balamurugana** [comment]
As MinIO does not support the case you mentioned, there is nothing can be done at client side.

**Comment by pdesoyres** [comment]
I do understand that MinIO cannot support this case. I was not clear enough when I created this issue. What I wanted to say is that maybe the client should handle the `XMinioObjectExistsAsDirectory` error code and should throw a proper `ErrorResponseException` instead of `IllegalArgumentException` during Xml unmarshalling process.

I think, the only thing to do for handling this error code is adding an `XMinioObjectExistsAsDirectory` entry to the enum `io.minio.ErrorCode`.

**Comment by balamurugana** [comment]
You are right and you can see https://github.com/minio/minio-java/pull/1028
