### ISSUE TITLE
How to retrive user metadata? 

### ISSUE THREAD

**Issue by kh-evgeniy** [minio/minio-java#1029]
Hello! I'm can't find a way to retrieve userMetadata. 
For example, i'm able to set meta through putObject:
```
 minio.putObject(
                   PutObjectArgs
                     .builder()
                     .bucket(config.bucket)
                     .`object`(objectName)
                     .stream(is, -1, -1)
                     .contentType(contentType)
                     .userMetadata(meta.asJava)
                     .build()
```
But how can I get those values back?

**Comment by balamurugana** [comment]
@kh-evgeniy Please go through the doc https://github.com/minio/minio-java/blob/release/docs/API.md#statObject

**Comment by kh-evgeniy** [comment]
I've looked there and problem is: ObjectStat doesn't have userMetadata

**Comment by balamurugana** [comment]
@kh-evgeniy You could use http://minio.github.io/minio-java/io/minio/ObjectStat.html#httpHeaders-- to get all HTTP headers which contains user metadata prefixed with `x-amz-meta-`. However in next release, you could use [StatObjectResponse](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/StatObjectResponse.java) containing `userMetadata()` method.

**Comment by kannappanr** [comment]
@kh-evgeniy Please look at http://minio.github.io/minio-java/io/minio/ObjectStat.html#httpHeaders--

Any header that starts with `x-amz-meta` is a userMetadata

**Comment by kh-evgeniy** [comment]
Oh, thanks!
