### ISSUE TITLE
MinioClient.bucketExists fails with an InvalidURI error against a minio server with a non-default region

### ISSUE THREAD

**Issue by SpComb** [minio/minio-java#1044]
When using minio-java 7.1.0 against a minio server configured with a non-default `MINIO_REGION`, calls to `minioClient.bucketExists` raise a misleading `ErrorResponse(code = InvalidURI, ...` error:

```
ErrorResponse(code = InvalidURI, message = Couldn't parse the specified URI, bucketName = example-bucket, objectName = null, resource = /example-bucket, requestId = 162E356D81B27D5D, hostId = null)
request={method=HEAD, url=https://minio.example.com/example-bucket, headers=Host: minio.example.com
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/1.5.2
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20200824T125417Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200824/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=accept-ranges: bytes
content-length: 0
content-security-policy: block-all-mixed-content
server: MinIO/RELEASE.2020-08-16T18-39-38Z
vary: Origin
x-amz-bucket-region: example-region
x-amz-request-id: 162E356D81B27D5D
x-xss-protection: 1; mode=block
date: Mon, 24 Aug 2020 12:54:22 GMT
strict-transport-security: max-age=31536000
}
```

Note the `us-east-1` region in the request `Authorization` header, vs the `x-amz-bucket-region` response header.

The same call succeeds when explicitly configuring the MinioClient with the correct region: (from `MinioClient.traceOn`):

```
---------START-HTTP---------
HEAD /example-bucket HTTP/1.1
Host: minio.example.com
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/1.5.2
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20200824T125449Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200824/example-region/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
accept-ranges: bytes
content-length: 0
content-security-policy: block-all-mixed-content
server: MinIO/RELEASE.2020-08-16T18-39-38Z
vary: Origin
x-amz-bucket-region: example-region
x-amz-request-id: 162E3574CC2C46D2
x-xss-protection: 1; mode=block
date: Mon, 24 Aug 2020 12:54:53 GMT
strict-transport-security: max-age=31536000

----------END-HTTP----------
```

I assume this case should be handled by bucket region auto-discovery.

This to be the related error-handling code: https://github.com/minio/minio-java/blob/7.1.0/api/src/main/java/io/minio/MinioClient.java#L1068-L1079

**Comment by balamurugana** [comment]
@SpComb 
1. `MinioClient` discovers region of a bucket (using `GetBucketLocation` API only once) if region is not passed via constructor. If you pass wrong region, it fails with an error from S3 service.(`InvalidURI` error is fixed in master to `BadRequest`)
2. `minio-java` works with `GetBucketLocation` API for region discovery and it does not rely on `x-amz-bucket-region` or anything upon error from S3 service.
3. If you pass region via constructor, it should be correct and valid value.

**Comment by SpComb** [comment]
To clarify, the HTTP 400 / `InvalidURI` behavior described was happening without any region configured. It seems to fail immediately on the HTTP HEAD => 400 error.

The `MinioClient.buckExists` did work when explicitly configured with the correct region. I did not test with any other incorrect region configured.

**Comment by balamurugana** [comment]
@SpComb As I mentioned, `minio-java` uses `GetBucketLocation` API to get bucket's region. In your trace, I don't see no http traces of `GetBucketLocation`. `GetBucketLocation` API is not called only if region is passed.

Can you provide full HTTP traces on error scenario with sample code?

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/1051
