### ISSUE TITLE
how to set presignedPostPolicy return json response?

### ISSUE THREAD

**Issue by rboleynl** [minio/minio-java#1045]
In getPresignedObjectUrl.java，i see the code can set response-content-type like below
// Get presigned URL string to upload 'my-objectname' in 'my-bucketname' 
// with response-content-type as application/json and life time as one day.
Map<String, String> reqParams = new HashMap<String, String>();
reqParams.put("response-content-type", "application/json");

because i want to set upload file limit, so used presignedPostPolicy method to get upload url,
but how to set response-content-type in presignedPostPolicy?

**Comment by balamurugana** [comment]
@rboleynl 
As per S3 specification,
1. There is no option to set upload file limit in `getPresignedObjectUrl()`
2. There is no option to set `response-content-type` in `getPresignedPostPolicy()`. Note that `getPresignedPostPolicy()` gives form-data properties and we need to construct actual URL request and execute.

**Comment by rboleynl** [comment]
thks reply!
