### ISSUE TITLE
Implement GetBucketVersioing API

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-java#1050]
We need to implement GetBucketVersioning API in minio-java as https://docs.minio.io/docs/java-client-api-reference.html#isVersioningEnabled
doesn't capture `suspend` an `off` states and it is required to capture those states as well just like it is done in https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/BucketVersioningConfiguration.html

**Comment by balamurugana** [comment]
PR https://github.com/minio/minio-java/pull/1053 adds APIs `setBucketVersioning()` and `getBucketVersioning()`; removes `enableVersioning()`, `disableVersioning()` and `isVersioningEnabled()`

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/1053
