### ISSUE TITLE
implement user management apis

### ISSUE THREAD

**Issue by forestbupt** [minio/minio-java#1052]
Minio provide the capabilities about user/group management, as well as access control via policy. But I noticed that all client sdks didn't implement the apis and wondering the reason. 

Should I interact with Minio via Http request directly if I need to manage the user accounts dynamically?

**Comment by harshavardhana** [comment]
The API is available as mc command or https://github.com/minio/minio/tree/master/pkg/madmin

There are no plans to implement it in Java.
