### ISSUE TITLE
How is paging achieved?

### ISSUE THREAD

**Issue by huangjj96** [minio/minio-java#1057]
Why is maxKeys invalid in the builder property of listObject api in my project?
![image](https://user-images.githubusercontent.com/70936420/92677332-2ca57780-f356-11ea-94ea-befcb9a0d618.png)

**Comment by harshavardhana** [comment]
paging is automatic you don't need to do anything we send an iterator and you just consume in your application.

**Comment by huangjj96** [comment]
> paging is automatic you don't need to do anything we send an iterator and you just consume in your application.

thanks,but I want to customize the number of paging.How can I achieve it?

**Comment by balamurugana** [comment]
@huangjj96 max-keys must be between 1 and 1000 in `ListObjectsArgs.maxKeys()`. What error are you getting?

**Comment by huangjj96** [comment]
> @huangjj96 max-keys must be between 1 and 1000 in `ListObjectsArgs.maxKeys()`. What error are you getting?

Why is maxKeys invalid in the builder property of listObject api in my project。
Do I need other configuration?
![image](https://user-images.githubusercontent.com/70936420/92685920-3c7b8680-f36b-11ea-9575-ca1f7632456f.png)

**Comment by balamurugana** [comment]
@huangjj96 What error are you getting?

**Comment by huangjj96** [comment]
> @huangjj96 What error are you getting?
There is no error, but the number of results returned is not the maxKeys I set

**Comment by harshavardhana** [comment]
> > There is no error, but the number of results returned is not the maxKeys I set

How do you know? @huangjj96 if you have more objects the iterator will continue to return more, maxKeys() is actual pagination per request internally used to exhaust the iterator.

**Comment by balamurugana** [comment]
@huangjj96 `max-keys` controls how many entries to be fetched on a request. As `listObjects()` returns an iterator, when you keep iterating, you keep getting results till the end using multiple fetch requests as per `max-keys`. You would need to use other parameters to control decided result or use low level API [listObjectV2()](https://minio-java.min.io/io/minio/MinioClient.html#listObjectsV2-java.lang.String-java.lang.String-java.lang.String-boolean-java.lang.String-int-java.lang.String-java.lang.String-boolean-boolean-com.google.common.collect.Multimap-com.google.common.collect.Multimap-) by inheriting `MinioClient`.

**Comment by nngo** [comment]
if `maxkeys` controls the page size, then the docs should be updated, e.g. in the examples (there are two examples saying it limits the list maximum to input value (i.e. of 100), so those two comments should change to page size, ideally we should add javadoc for `maxKeys(int)` to also say that it is max page size and not the max size/limit of returned objects)

https://github.com/minio/minio-java/blob/master/docs/API.md#listobjectslistobjectsargs-args (under Example)
```java
// Lists maximum 100 objects information whose names starts with 'E' and after 'ExampleGuide.pdf'.
Iterable<Result<Item>> results = minioClient.listObjects(
    ListObjectsArgs.builder()
        .bucket("my-bucketname")
        .startAfter("ExampleGuide.pdf")
        .prefix("E")
        .maxKeys(100)
        .build());
```
> `max-keys` controls how many entries to be fetched on a request. As `listObjects()` returns an iterator, when you keep iterating, you keep getting results till the end using multiple fetch requests as per `max-keys`. You would need to use other parameters to control decided result or use low level API [listObjectV2()](https://minio-java.min.io/io/minio/MinioClient.html#listObjectsV2-java.lang.String-java.lang.String-java.lang.String-boolean-java.lang.String-int-java.lang.String-java.lang.String-boolean-boolean-com.google.common.collect.Multimap-com.google.common.collect.Multimap-) by inheriting `MinioClient`.

**Comment by balamurugana** [comment]
@nngo Please feel free to send a fix

**Comment by Liudiey** [comment]
I had the same problem。Let me tell you a joke. It's hard for us to make money like this
