### ISSUE TITLE
How does Java API generate permanent valid outer chain

### ISSUE THREAD

**Issue by bjj520719** [minio/minio-java#1059]
HI
io.minio minio 3.0.8
How does Java API generate permanent valid outer chain？
Preseignedgetobject method can only generate 7-day-old external chain without encryption。

**Comment by balamurugana** [comment]
@bjj520719 You would need to configure bucket policy using [setBucketPolicy() API](https://minio-java.min.io/io/minio/MinioClient.html#setBucketPolicy-io.minio.SetBucketPolicyArgs-). You could use [Policy Generator](https://awspolicygen.s3.amazonaws.com/policygen.html) to policy configuration.
