### ISSUE TITLE
Cannot set Content-MD5 header

### ISSUE THREAD

**Issue by Termite** [minio/minio-java#1064]
Hi,

the java api overwrites my Content-MD5 header setting. 
I have millions of objects with allready calculated checksums, so I want the upload to fail if my own checksum doesn't match.
Moreover, in this case it's just not neccessary to calculate the checksum again.

I  do it like:
Map<String,String> myHeader = new HashMap<>();
myHeader.put("Content-MD5", "base64-md5sum");
PutObjectArgs args = PutObjectArgs.builder()....headers(myHeader).build();
client.putObject(args);

is this the correct way to do it? As it  does not work since the Content-MD5 header gets overwritten in MinioClient::createRequest

MinioClient is effectivly a final class (all consturctors are private), the builder is also final, that means I cannot subclass it to overwrite createRequest.

Is there a way for me to set my Content-MD5 header field? 

I think, the api should not overwrite my header field.

Thanks for helping,
 Michael

**Comment by balamurugana** [comment]
@Termite You cannot override content-md5 because uploading data to an object has different ways depending on parameters to `putObject()` API. Sending you own content-md5 is wrong accordingly to S3 specification. Any `PUT` with content-md5 is verified at S3 server-side.

If you want to customize entirely, its possible to inherit `MinioClient` and do whatever you want. You could also refer PR https://github.com/minio/minio-java/pull/1013

**Comment by Termite** [comment]
Thanks for the answer.

**Comment by Termite** [comment]
According to "https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html"
the usage of Content-MD5 is optional, so it is not required that you set it. That also means, that it is not wrong to set my own calculate md5 sum. 
I think the api schould not overwrite my header, espacially, if it's an optional headerfield.

**Comment by balamurugana** [comment]
@Termite Even though the specification says `Content-MD5` header is optional, its not true in practise. S3 service expects MD5 for many REST calls.

To public `putObject()` API, it handles many data upload cases based on data size like single upload or multi-part upload.

As you have non-standard use case, the ideal way to deal with is to inherit `MinioClient` and do whatever way you like to do.

**Comment by Termite** [comment]
Thanks for the answer.
I would like to inherit it, but all public constructors are marked deprecated and so not usable in a future version, if they get removed.
If you could make the main constructor (which is called by the builder) protected, that would allow me to inherit the `MinioClient`
Additional the builder should either be non-final or add a method to the builder, which allows to give a generator to build, which makes the MinioClient. This way one can easily give the builder the constructor of a derived class as generator.
This is not much code to change.

Otherwise, I cannot inherit MinioClient, since all is locked.

Thanks,
 Michael

**Comment by balamurugana** [comment]
That's the reason I asked you to refer the PR #1013. You will have protected constructor and many methods.

**Comment by Termite** [comment]
Oh, somehow I did not look at the diff of PR#1013 (only the title), sorry for overlooking it.
Yes, with this patch, it's no problem to inherit the class. 
Thanks for helping,
 Michael

**Comment by Termite** [comment]
just to be clear: of course PR#1013 helps.
But:  I regard it as plain wrong of the java api to IGNORE my Content-MD5 header. 
The api should check if the header is already set and if so, do nothing about it.
If it is not set, it can set (as it now does it).

That would be the right behaviour.
Cheers,
 Michael

**Comment by balamurugana** [comment]
As I mentioned above, you would need to inherit and use for non-standard use cases. We can't make such changes as defaults to break S3 specifications.

**Comment by Termite** [comment]
*Sigh*, if I *set* the Content-Md5 header, there is no breakage of S3 specification , since, as I said, it *is* included. 
Ignoring valid headers and overwriting them is buggy. At least it would be good to mention it in the api docs.

Thanks for answering
 Michael
