### ISSUE TITLE
java.lang.outofmemoryerror java heap space

### ISSUE THREAD

**Issue by crossnote** [minio/minio-java#1069]
hi,i have a problem when i set partsize more than 80Mb.
sdk version is 7.1.0
server are two linux os machine.
here is my code and console error
![P01010-105730(1)](https://user-images.githubusercontent.com/22958160/95644203-a3659a00-0ae7-11eb-9cf5-a2a8d3343424.jpg)
thank you for your reply！

**Comment by balamurugana** [comment]
It is a typical problem in java. You would need to increase heap size when you use more memory. Refer https://stackoverflow.com/questions/1565388/increase-heap-size-in-java

**Comment by lusson-luo** [comment]
This does not solve the problem well. If multiple users upload large files at the same time, adding more memory will not be enough.
I think it should be uploaded in chunks, rather than converted into a large byte[] object to upload.
@balamurugana

**Comment by balamurugana** [comment]
@lusson-luo You would need to optimize parameters in [PutObjectArgs.Builder.stream()](https://minio-java.min.io/io/minio/PutObjectArgs.Builder.html#stream-java.io.InputStream-long-long-)

**Comment by lusson-luo** [comment]
Thinks
