### ISSUE TITLE
java.net.socketexception:connection reset

### ISSUE THREAD

**Issue by crossnote** [minio/minio-java#1070]
hi,When I download files, I will encounter the problem of connection reset. This is not a frequent problem, but occasionally encountered. Is this due to network reasons?

javs sdk version :7.1.0
server are two linux os machine,four drivers under each machine.

**Comment by balamurugana** [comment]
It may be due to not reading data faster at client side and/or the server is responding slowly. You could adjust timeouts using [setTimeout()](https://minio.github.io/minio-java/io/minio/MinioClient.html#setTimeout-long-long-long-)
