### ISSUE TITLE
Support for downloading the entire folder located on a bucket 

### ISSUE THREAD

**Issue by Prafulljohri** [minio/minio-java#1073]
Directory download is a common practice and AWS S3 supports this feature. The DownloadObjectArgs should contain the prefix method (where we can pass the folder directory) as it's available in ListObjectsArgs.

Also, please try to provide the feature of downloading the zip file of the directory as it is available in the minio browser
 
For reference please refer to the below AWS S3 document:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#downloadDirectory-java.lang.String-java.lang.String-java.io.File-

**Comment by balamurugana** [comment]
Application/tool like feature has to build on top of `MinioClient`. It is purely application logic how to upload/download multiple files i.e. you would need to write `TransferManager` outside of `MinioClient`.

**Comment by DavidPerezIngeniero** [comment]
It may be easier to invoke from Java the `mc` command tool and use `mc cp` that to use the API.
