### ISSUE TITLE
userMetadata value exception: Unexpected char 0x5546 at 0 in x-amz-meta-tag value: 商品

### ISSUE THREAD

**Issue by jobmission** [minio/minio-java#1078]
// sample code
MinioClient minioClient = MinioClient.builder().endpoint("https://play.min.io").credentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG").build();
ByteArrayInputStream bais = new ByteArrayInputStream(“abcd”);
Map<String, String> userMetadata = new HashMap<>();
userMetadata.put("tag", "商品");
            ObjectWriteResponse objectWriteResponse = minioClient.putObject(
                PutObjectArgs.builder().bucket("zhangsan").object("my-objectname").stream(
                    bais, bais.available(), -1)
                    .userMetadata(userMetadata)
                    .build());

the method `.userMetadata(userMetadata)` call `requestBuilder.header(entry.getKey(), entry.getValue());` , okhttp check header name and value ascii, but my userMetadata value contains chineses words , okhttp Headers.Builder.addUnsafeNonAscii only check name ascii; 
@line https://github.com/minio/minio-java/blob/e52971733b5cc576941a3a6e4c6f277fa810b2ba/api/src/main/java/io/minio/MinioClient.java#L470 ,
Replacing Request.Builder.header(String name, String value)  with okhttp Headers.Builder.addUnsafeNonAscii  and Request.Builder.headers(Headers headers)  may solve my problem .

Hope to understand my poor English expression .

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/1079

**Comment by jobmission** [comment]
Thank you very much for such a quick code submission.
