### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1082]
io.minio.messages.Item.java
public ZonedDateTime lastModified() {
    return lastModified.zonedDateTime();
}
when lastModified is null then throw NullPointerException

**Comment by balamurugana** [comment]
@4714407 Please share your sample code along with HTTP traces by `MinioClient.traceOn()`.

**Comment by 4714407** [comment]
when item is dir,lastModified is null

**Comment by zqr95518** [comment]
The same problem. I prefer return null when the item is a storage or the lastModified is null .

**Comment by balamurugana** [comment]
According to AWS S3 specification, common prefixes do not have any information other than names. These common prefixes are often called as `directories`.

In `minio-java`, we fetches these information and provide as `Item`. For common prefixes, you don't get other than names. It is user responsibility to check `null`.

**Comment by zqr95518** [comment]
So if I check isDir is true, I only need the name?
Got it.

**Comment by 4714407** [comment]
Isn't it better to modify the code in this place to avoid null pointer errors
