### ISSUE TITLE
The application that uploaded the file using the Java API ran successfully but minio couldn't see the file

### ISSUE THREAD

**Issue by shenzgang** [minio/minio-java#1084]
The application that uploaded the file using the Java API ran successfully but minio couldn't see the file，
I used cluster mode, and finally found that because the disk was used 100%, the file was not uploaded successfully, but the program ran successfully, so should I throw an exception here?

**Comment by balamurugana** [comment]
@shenzgang What do you mean by `successfully`? Can you share `MinioClient.traceOn()` output?

If there is an error at server side, but it still returns success to the client, there is nothing can be done at client side.

**Comment by kannappanr** [comment]
@shenzgang please upload the sample code. Also the trace as requested by Bala
