### ISSUE TITLE
Unhandled HTTP code 301 when trying to create a bucket on Amazon S3 which already exists

### ISSUE THREAD

**Issue by florianrhomberg** [minio/minio-java#1085]
If you try to create a bucket on Amazon S3 with a name which already exists, the above error is displayed as part of an  internal exception.

Workaround:
`try {
if(this.minioClient.bucketExists(bucketName.toLowerCase()))
   throw new BucketAlreadyExistException();
}
catch(io.minio.errors.InternalException e) {
 e.printStackTrace();
 if(e.getMessage().contains("unhandled HTTP code 301."))
   throw new BucketAlreadyExistException();
 else
   throw e;
}`

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/1056
