### ISSUE TITLE
minioClient.presignedPutObject post return XMinioUnknownAPIRequest

### ISSUE THREAD

**Issue by tianzhenjiu** [minio/minio-java#1087]
https://docs.min.io/docs/javascript-client-api-reference.html#presignedPostPolicy
when i use this api  to get a sign for  post, i  use the return params  to post a file  to  Minio by curl ,it return  
<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /</Message><Resource>/</Resource><RequestId></RequestId><HostId>17f43007-8bec-4cd1-834e-c4a11d2ace0f</HostId></Error>

how can  i do for post a file  to  minio?

**Comment by balamurugana** [comment]
Please refer this example https://github.com/minio/minio-java/blob/release/examples/PresignedPostPolicy.java

**Comment by tianzhenjiu** [comment]
ok,i know. the url must be endwith bucketname,is right?
