### ISSUE TITLE
Why is it that when I delete all the files in a directory, the directory is automatically deleted?

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1092]
Why is it that when I delete all the files in a directory, the directory is automatically deleted? But it allows you to create an empty directory

**Comment by balamurugana** [comment]
If you created a prefix so called directory and you haven't included it on remove list, it will be there. But you haven't created the prefix, S3 service gives a view as directory of object keys.

Please refer AWS S3 documentation for more in-depth detail.

**Comment by 4714407** [comment]
In the first step, I created a directory, for example, "Tom /"

In the second step, I put a file in the directory, for example: "Tom / 1. XML"

In the third step, I delete "1. XML" from the directory "Tom", but the directory "Tom" is also deleted

Is there any way to keep the directory "Tom" empty like the first step, instead of being deleted together

**Comment by balamurugana** [comment]
Looks like it is S3 service issue. What S3 service/server are you using?

**Comment by 4714407** [comment]
I don't use S3 service, I use MinIo

**Comment by 4714407** [comment]
After using the version 2020-10-28t08:16:50z, the problem is solved
