### ISSUE TITLE
The item.isDir method returns abnormally in some cases

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1093]
When using the listObject method and setting recursive to true, the isDir method of all returned items will return false.If recursive is not set, it is normal.

**Comment by balamurugana** [comment]
Yes

**Comment by 4714407** [comment]
This is obviously an bug, the isDir method does not correctly determine the type of object returned

**Comment by balamurugana** [comment]
Accordingly to S3 spec, there is no directory in object storage. However S3 spec emulates common prefixes by delimiter `/` for user to visualize as directories. Please go through respective S3 specifications.

**Comment by 4714407** [comment]
idDire() return false when object name end with delimiter /,should return true!
