### ISSUE TITLE
what is the target file's file extension after using composeObject() ?

### ISSUE THREAD

**Issue by VOIDTOR** [minio/minio-java#1094]
hi,what is the file extension when  using composeObject api?
I can't open it with .zip extension. 
thanks a lot.

**Comment by balamurugana** [comment]
The API creates an object by concatenating data of source objects using server-side copy. To specific to zip files, it does not merge multiple zip files to one. It is user's responsibility to do so.

**Comment by VOIDTOR** [comment]
> The API creates an object by concatenating data of source objects using server-side copy. To specific to zip files, it does not merge multiple zip files to one. It is user's responsibility to do so.
thanks a lot. so, if i want to compress a list of files on the serverside, i must download them one by one and compress them to a zip file and upload the zipped file.  I think it will be convenient if this zip job can be done on the server side

**Comment by balamurugana** [comment]
According to S3 spec, It is not supported. It is user's responsibility to merge multiple compressed files to one file, then upload the final file as object.
