### ISSUE TITLE
Why are many methods missing in version 8.0?

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1096]
For example: removeIncompleteUpload, listIncompleteUploads, etc.

**Comment by harshavardhana** [comment]
That's why its called 8.0.0 - you don't need to upgrade unless you want to.

**Comment by harshavardhana** [comment]
Look at the newer APIs https://minio-java.min.io/io/minio/messages/AbortIncompleteMultipartUpload.html#AbortIncompleteMultipartUpload-java.lang.Integer-

**Comment by 4714407** [comment]
Thank you! It is recommended that you update the official documents in time, what an excellent upgrade. I want to ask if you were a Python programmer before?

**Comment by kiwikaki** [comment]
> Thank you! It is recommended that you update the official documents in time, what an excellent upgrade. I want to ask if you were a Python programmer before?

haha
