### ISSUE TITLE
Problem with the overload of Transition's constructor

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1098]
There is a problem with the overload of Transition's constructor. According to the example in the document (https://docs.min.io/docs/java-client-api-reference.html#setBucketLifecycle), it cannot be used

![image](https://user-images.githubusercontent.com/71766981/98338579-596bc780-2045-11eb-9fbb-94fa50d93e0d.png)

**Comment by 4714407** [comment]
By the way, minio does not seem to support the Transition tag

**Comment by harshavardhana** [comment]
> By the way, minio does not seem to support the Transition tag

https://github.com/minio/minio/pull/10565 will be supported here

**Comment by balamurugana** [comment]
Please describe the issue clearly what's not working.

**Comment by 4714407** [comment]
Can't you see the picture? The sample code in the documentation does not compile at all

**Comment by balamurugana** [comment]
Please provide java compiler (`javac`) error.

**Comment by 4714407** [comment]
![image](https://user-images.githubusercontent.com/71766981/98338579-596bc780-2045-11eb-9fbb-94fa50d93e0d.png)
