### ISSUE TITLE
Missing STS code as mentioned in https://github.com/minio/minio-java/issues/1032

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio-java#1099]
In continuation to https://github.com/minio/minio-java/issues/1032, the suggestion was to build the jar from master branch which was 7.1.0 at that time and test. I was able to build and test at that time. But now in release 7.1.4, I am unable to find any classes for  io.minio.credentials. Is the same removed or discontunued?

**Comment by balamurugana** [comment]
Please refer [examples](https://github.com/minio/minio-java/tree/master/examples) and [documentation](https://github.com/minio/minio-java/blob/master/docs/API.md)

**Comment by PSHREYASHOLLA** [comment]
Hi Bala, My question was "now in release 7.1.4, I am unable to find any classes for io.minio.credentials. Is the same removed or discontunued?"

So in which version is it supported ? 
As the same was working in 7.1.0

**Comment by balamurugana** [comment]
There is no `credentials`available in < 8.0.0

**Comment by PSHREYASHOLLA** [comment]
But you had mentioned the same is available as part of https://github.com/minio/minio-java/issues/1032.

So was it later removed?

Is 8.0.0 a released version ?

**Comment by balamurugana** [comment]
Just use `8.0.0`

**Comment by PSHREYASHOLLA** [comment]
Is 8.0.0 a released version ?

**Comment by PSHREYASHOLLA** [comment]
@balamurugana , Can you confirm, Is 8.0.0 a released version ? As mentioned do not want to get into this jumble again.

**Comment by harshavardhana** [comment]
@PSHREYASHOLLA you can check in maven, we have readme.md updated?

What more do you want?

**Comment by PSHREYASHOLLA** [comment]
@balamurugana Since it still points to master branch I am asking this. 

If you can see https://github.com/minio/minio-java/issues/1032, as suggested by you I had consumed 7.1.1 when it was master. But in the release now its missing. 

So the question is it planned for a change or is it the released one?
