### ISSUE TITLE
The getObjectUrl method has been deleted in 8.0. How can I get a URL address that does not expire?

### ISSUE THREAD

**Issue by 4714407** [minio/minio-java#1105]
The getObjectUrl method has been deleted in 8.0. How can I get a URL address that does not expire?

**Comment by balamurugana** [comment]
We do not support any utility functions like `getObjectUrl()` any more. You have two tricks to do that
* Create `MinioClient` object without credentials (anonymous client) and use `getPresignedObjectUrl()`
(or)
* Inherit `MinioClient` and use `buildUrl()`

**Comment by 4714407** [comment]
How to use getPresignedObjectUrl() to achieve non expiration?

**Comment by balamurugana** [comment]
With no credentials there is no pre-signing hence the URL looks like value returned like old `getObjectUrl()`
