### ISSUE TITLE
Ability to fetch all the objects in a bucket or path in a single API call

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio-java#1107]
How can we fetch all the objects in a bucket or path in a single API call?

**Comment by balamurugana** [comment]
Refer [listObjects()](https://minio-java.min.io/io/minio/MinioClient.html#listObjects-io.minio.ListObjectsArgs-) method

**Comment by PSHREYASHOLLA** [comment]
@balamurugana Thanks for the API details, but this API gives the object details, how to get the actual object which we get in getObject() API?
Our requirement is to retrieve all Objects from a bucket.

**Comment by balamurugana** [comment]
Use `listObjects()` method to fetch object information then use that information with `getObject()` or `downloadObject()` methods.

**Comment by PSHREYASHOLLA** [comment]
@balamurugana, Our requirement is to get all Objects contents in one single call, as multiple calls to MinIO will cause performance issues.

Can you please let me know how we can achieve the same?

**Comment by balamurugana** [comment]
@PSHREYASHOLLA Write your own method with the  logic I mentioned above.

**Comment by harshavardhana** [comment]
@PSHREYASHOLLA we cannot write code for you - you should learn the SDKs primitives to write the application logic yourself. 

If you are looking for white-glove service you are more than welcome to buy a subscription with us https://min.io/pricing

**Comment by PSHREYASHOLLA** [comment]
@balamurugana, Thanks for the update.

@harshavardhana  I do not understand where did this come from "we cannot write code for you". I did not ask to write code for me, I just asked is there a way today to achieve the same. 

Regarding subscription yes we will buy it if we feel its fitting our business requirement. To propose it to our customers first I have to see if we are able to achieve our functionalities. That is what I am doing by exploring MinIO functionalities and requesting for support.

You need to get the context right before making statements like "we cannot write code for you ".
