### ISSUE TITLE
IamAwsProvider can't fetch ECS task role credentials

### ISSUE THREAD

**Issue by cbutcosk** [minio/minio-java#1108]
In using the new credentials interface I noticed that although `IamAwsProvider` covers the EC2 metadata auth flow. But when I try to use it in an ECS task role the auth flow is getting tripped up [here](https://github.com/minio/minio-java/blob/691e1088249c8323d3dcfce601122cf1f06fc8e9/api/src/main/java/io/minio/credentials/IamAwsProvider.java#L119). 

According to the AWS docs around IAM Task Roles [the expected response](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) from the container metadata endpoint lacks the `Code` property checked in that line:
```json
{
    "AccessKeyId": "XXX",
    "Expiration": "2020-11-07T01:28:43Z",
    "RoleArn": "arn:aws:iam::XXX:role/role-name-here",
    "SecretAccessKey": "XXX",
    "Token": "XXX"
}
```

**Comment by balamurugana** [comment]
@cbutcosk Could you confirm AWS_CONTAINER_CREDENTIALS_FULL_URI way to fetch credentials return same JSON structure?

**Comment by cbutcosk** [comment]
@balamurugana Hm, good question--I actually can't reproduce an environment on my end that sets AWS_CONTAINER_CREDENTIALS_FULL_URI. Not sure if that is due to the deployment type I'm using or something.

That said the AWS SDK appears to [use the same endpoint](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java) regardless of which environment variable is used to construct the URI since the entire refresh() method is in the superclass there.

**Comment by balamurugana** [comment]
@cbutcosk No problem. I have made `Code` property check optional.
