### ISSUE TITLE
examples of GetPresignedObjectUrl request method error

### ISSUE THREAD

**Issue by amrxjks** [minio/minio-java#1131]
String url =
          minioClient.getPresignedObjectUrl(
              GetPresignedObjectUrlArgs.builder()
                  .method(Method.DELETE)
                  .bucket("my-bucketname")
                  .object("my-objectname")
                  .expiry(60 * 60 * 24)
                  .build());
if use aboue i get  error 
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
<Key>upload/20201130/20201130215925at1Kx5T3.mp4</Key>
<BucketName>dyzx</BucketName>
<Resource>/dyzx/upload/20201130/20201130215925at1Kx5T3.mp4</Resource>
<RequestId>164C4FD24BF717C4</RequestId>
<HostId>407400c6-72c7-40a4-8126-7615f6207f77</HostId>
</Error>
it should be 
String url =
          minioClient.getPresignedObjectUrl(
              GetPresignedObjectUrlArgs.builder()
                  .method(Method.GET)
                  .bucket("my-bucketname")
                  .object("my-objectname")
                  .expiry(60 * 60 * 24)
                  .build());

Method.DELETE->Method.GET

**Comment by balamurugana** [comment]
@amrxjks What exactly are you trying to do? Are you trying to generate pre-signed url to delete `my-objectname` in `my-bucketname` (the example is about that) ? 

If you want to do get object, you supposes to use `GET` method.
