### ISSUE TITLE
AssumeRole example build error

### ISSUE THREAD

**Issue by jack-jun** [minio/minio-java#1139]
Try to run the AssumeRole example with sdk v8.0.3, get the following error:

```java
Exception in thread "main" java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
```

Check the source file AssumeRoleProvider.java, line 106
```java
                RequestBody.create(data, MediaType.parse("application/x-www-form-urlencoded")))
```
here it calls a method with String and Mediatype as parameters, but in okhttp3 the method's parameters should be Mediatype and String, the order is reversed....

**Comment by balamurugana** [comment]
@jack-jun Feel free to send a fix

**Comment by balamurugana** [comment]
@jack-jun It seems you are using wrong version of okhttp4. `minio-java` depends on okhttp v4.8.1. Reopen if you see a problem with appropriate dependencies.
