### ISSUE TITLE
getPresignedObjectUrl return broken link

### ISSUE THREAD

**Issue by JajaComp** [minio/minio-java#1146]
Hi! When i use getPresignedObjectUrl with WebIdentityProvider all other api work fine, but this function return broken link. When i open it got next:
```
<Error>
<Code>InvalidTokenId</Code>
<Message>The security token included in the request is invalid</Message>
<Key>test.file</Key>
<BucketName>test</BucketName>
<Resource>/test/test.file</Resource>
<RequestId>165A1C68D830D7EA</RequestId>
<HostId>e1c4bedf-3977-4763-8fef-03f1559852e2</HostId>
</Error>
```

If i use accessKey/secretKey all work fine.
Also if i use web interface with token authorization - i got correct share link.
minio-java version: 8.0.3

**Comment by balamurugana** [comment]
@JajaComp  Can you provide the code you used to generate presigned URL along with S3 service configuration?

**Comment by JajaComp** [comment]
I use latest minio server 
This is simple on kotlin:
[Test.txt](https://github.com/minio/minio-java/files/5816104/Test.txt)

**Comment by balamurugana** [comment]
@JajaComp The fix https://github.com/minio/minio-java/pull/1147 is available. Please try and let me know whether it is working for you.

**Comment by JajaComp** [comment]
@balamurugana Worked! Thx!
