### ISSUE TITLE
MinioClient.composeObjects  size less than MIN_MULTIPART_SIZE 

### ISSUE THREAD

**Issue by jconlon** [minio/minio-java#1149]
The idea of composing objects  from existing ones on the server rather than downloading both or more, then composing them and last re-uploading them seems to be a good use case.  While trying out MinioClient.composeObject I ran into an exception with the objects I was attempting to compose.  There too small?  

Is there a workaround to prevent this exception?  What is the rational for limiting the size of sources for compose?

Java.lang.IllegalArgumentException: source test-contacts/contacts.ndjson: size 72769 must be greater than 5242880
	at io.minio.MinioClient.calculatePartCount(MinioClient.java:1269)
MinioClient.java:1269
	at io.minio.MinioClient.composeObject(MinioClient.java:1384)
MinioClient.java:1384

**Comment by balamurugana** [comment]
As per AWS S3 specification, In multipart upload each part size must be > 5MiB except last part. `composeObject()` uses multipart upload for more than one source is given.

If your sources are < 5MiB, you have no option other than downloading/concatenating them locally.
