### ISSUE TITLE
Why is the uploadPart method modified by protected？

### ISSUE THREAD

**Issue by neko-zhu** [minio/minio-java#1150]
The uploadPart method modified by protected，if i want to use the multipart upload function, what should I do?

I hope the uploadPart method and its related methods to be modified by public

Looking forward to your reply！

**Comment by harshavardhana** [comment]
Moving to relevant repo @neko-zhu

**Comment by neko-zhu** [comment]
I want to upload the fragment files by myself and submit a merge request at the end. This should be a reasonable demand, and many object storage services are supported. Hope you think about it! @balamurugana

**Comment by balamurugana** [comment]
@neko-zhu Low level S3 APIs are marked `protected` on purpose to advanced usage. In normal/common use cases, `public` methods are good enough to achieve everything. If your use case is peculiar, you would need to inherit `MinioClient` and use `public` and `protected` methods.

**Comment by neko-zhu** [comment]
Ok, I will implement the function by myself, thanks for the reply
