### ISSUE TITLE
About Url can only have 7 days

### ISSUE THREAD

**Issue by YellowKang** [minio/minio-java#1151]
Why can the generated URL expire only 7 days? If the user wants to customize it, how to modify it
Source code:
  // default expiration for a presigned URL is 7 days in seconds
  public static final int DEFAULT_EXPIRY_TIME = (int) TimeUnit.DAYS.toSeconds(7);
Amazon S3 SDK can customize the timeout time, whether it is necessary to consider allowing users to define the Url expiration time.

**Comment by balamurugana** [comment]
@YellowKang According to [AWS S3 specification](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html#auth-methods-intro), presigned URL is valid up to 7 days. If you have custom non-standard S3 service, inherit `MinioClient` and generate presigned URL yourself.
