### ISSUE TITLE
 MD5 changed after MinioClient.composeObjects

### ISSUE THREAD

**Issue by kristekw** [minio/minio-java#1152]
The idea is  multipart uploading a big file to minio through presignUrl api and  composing them by MinioClient.composeObjects.   However, it seems that the md5  has been changed after composing action. 

Here is my console log for file slicing:
---File size: 9746651 
---part 0 size :5242880
---part 1 size :4503771

**Comment by balamurugana** [comment]
I don't understand. Are you saying md5sum of newly created object does not match md5sum of concatenated part1 and part2 objects?

Reopen the issue with relevant information.

**Comment by kristekw** [comment]
> I don't understand. Are you saying md5sum of newly created object does not match md5sum of concatenated part1 and part2 objects?
> 
> Reopen the issue with relevant information.

just got the problem  thank u so much
