### ISSUE TITLE
method:listParts  throw io.minio.errors.XmlParserException: null 	at io.minio.Xml.unmarshal(Xml.java:55)

### ISSUE THREAD

**Issue by tuine** [minio/minio-java#1155]
```
<?xml version="1.0" encoding="UTF-8"?>
<ListPartsResult
    xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Bucket>test</Bucket>
    <Key>test</Key>
    <UploadId>424f9267-386b-4392-8673-8439a7a8e87e</UploadId>
    <Initiator>
        <ID>02d6176db274dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID>
        <DisplayName></DisplayName>
    </Initiator>
    <Owner>
        <ID>02d6176db274dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID>
        <DisplayName></DisplayName>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
    <PartNumberMarker>1</PartNumberMarker>
    <NextPartNumberMarker>0</NextPartNumberMarker>
    <MaxParts>1000</MaxParts>
    <IsTruncated>false</IsTruncated>
</ListPartsResult>
```

I found the error reasons：
class io.minio.messages.Initiator -> DisplayName  can't Empty
**How can I set the value ?**

**Comment by balamurugana** [comment]
I wonder why your server does not send display name. You would need to check the server to comply with the AWS S3 specification.

**Comment by tuine** [comment]
> I wonder why your server does not send display name. You would need to check the server to comply with the AWS S3 specification.

AWS S3 DisplayName filed  Required:no ,
[API_Initiator](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Initiator.html)

DisplayName
Name of the Principal.
Type: String
Required: No

**Comment by balamurugana** [comment]
@tuine It is known that AWS S3 specification page contains errors. You would need to check with AWS SDK Java or AWS CLI.

**Comment by tuine** [comment]
@balamurugana
I tested it on "https://play.minio.io:9000", the returned field is still empty, or is there a problem with the code I wrote, thanks for answering
```
                Multimap<String, String> headers = HashMultimap.create();
                headers.put("Content-Type", "application/octet-stream");
                CreateMultipartUploadResponse multipartUpload = minioClient.createMultipartUpload(bucketName, region, objectName, headers, null);
                String uploadId = multipartUpload.result().uploadId();

                BufferedInputStream bis = stream instanceof BufferedInputStream ? (BufferedInputStream) stream : new BufferedInputStream(stream);
                UploadPartResponse response = minioClient.uploadPart(bucketName, region, objectName, bis, (int) fileSize, uploadId, partNumber, headers, null);
                String etag = response.etag();

                Part[] parts = new Part[10];
                parts[partNumber - 1] = new Part(partNumber, etag);

                ListPartsResponse cncc1 = minioClient.listParts(bucketName, region, objectName, null, 1, uploadId, null, null);
```

**Comment by balamurugana** [comment]
@tuine It is a bug in the server. Please open an issue accordingly.

**Comment by harshavardhana** [comment]
> @tuine It is a bug in the server. Please open an issue accordingly.

@balamurugana https://github.com/minio/minio/issues/11408#issuecomment-771421594

It is actually a bug in the client - it is allowed for these fields to be optional in AWS S3 implementation

**Comment by balamurugana** [comment]
@harshavardhana According to https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html#AmazonS3-ListParts-response-Initiator, we need to populate the values. What I understand is, either we need to populate the values or `Initiator` tag is optional. The problem is we are populating `ID` and empty `DisplayName`.
