### ISSUE TITLE
NullPointerException on MinioClient.putObject(PutObjectArgs args)

### ISSUE THREAD

**Issue by cgaglio-fr** [minio/minio-java#1159]
Minio java client version: 8.0.3
During upgrading to Minio servers version: RELEASE.2020-12-12T08-39-07Z 
we have seen some java.lang.NullPointerException :
`Caused by: java.lang.NullPointerException:Cannot invoke "String.replaceAll(String, String)" 
because the return value of "okhttp3.Response.header(String)" is null
	at io.minio.MinioClient.putObject(MinioClient.java:4561)
	at io.minio.MinioClient.putObject(MinioClient.java:2713)
	at io.minio.MinioClient.putObject(MinioClient.java:2830)`

Looks like this line is the culprit : 
`response.header("ETag").replaceAll("\"", "")`
I don't know why the header was null
But our Minio servers was not in good state during the upgrading. We were experiencing some downtime and HTTP 503

**Comment by balamurugana** [comment]
The server must return `ETag`. Please open an issue in minio server accordingly.

**Comment by cgaglio-fr** [comment]
I gonna try to reproduce with the last Minio server version and open an issue
But I think throwing an `MinioException` because `ETag` is null 
It's better than `NullPointerException`

**Comment by balamurugana** [comment]
It is user's responsibility to handle any runtime exceptions. There are many possibilities to get them and it is a bad idea to workaround inside minio-java.

**Comment by kannappanr** [comment]
@cgaglio-fr If you can provide the sample code to reproduce the issue, and the corresponding trace from minio and paste it on a new issue in minio, we can take a look at it.

**Comment by cgaglio-fr** [comment]
Sure, I'm gonna try to reproduce using the last version of minio
I will let you know

**Comment by cgaglio-fr** [comment]
I tried to reproduce using latest minio version and official helm chart but no success
While upgrading the replicaset many times I received some 503 but never an empty ETag header
Thanks for your quick support
👍

**Comment by youngledo** [comment]
> The server must return `ETag`. Please open an issue in minio server accordingly.

Excuse me, is this a server error? Do I need to update the server version?
