### ISSUE TITLE
the userMetadata value is null from minioClient.listObjects()

### ISSUE THREAD

**Issue by shuangovo** [minio/minio-java#1160]
I have tried minioClient.statObject(),the userMetadata value is returned normally
java client version 8.0.3

**Comment by balamurugana** [comment]
You have to use [ListObjectsArgs.includeUserMetadata()](https://minio-java.min.io/io/minio/ListObjectsArgs.html#includeUserMetadata--). Note that it works only in minio server and ListObjects Version 2 S3 API.
