### ISSUE TITLE
java.security.ProviderException: STS service failed with HTTP status code 403

### ISSUE THREAD

**Issue by ngcin** [minio/minio-java#1164]
Use the url "https://play.minio.io:9000/",it can works. But use the server deployment myself , throws the exception.

-  use https://play.minio.io:9000/

```
Provider provider =
                new AssumeRoleProvider(
                        "https://play.minio.io:9000/",
                        "minio",
                        "minio123",
                        null, // Duration seconds if available.
                        null, // Policy if available.
                        null, // Region if available.
                        null, // Role ARN if available.
                        null, // Role session name if available.
                        null, // External ID if available.
                        null);
        Credentials credentials = provider.fetch();
        String s = ReflectionToStringBuilder.toString(credentials);
        System.out.println(s);
```

-  use http://127.0.0.1:9000/

```
Provider provider =
                new AssumeRoleProvider(
                        "http://127.0.0.1:9000/",
                        "minioadmin",
                        "minioadmin",
                        null, // Duration seconds if available.
                        null, // Policy if available.
                        null, // Region if available.
                        null, // Role ARN if available.
                        null, // Role session name if available.
                        null, // External ID if available.
                        null);
        Credentials credentials = provider.fetch();
        String s = ReflectionToStringBuilder.toString(credentials);
        System.out.println(s);

```
![image](https://user-images.githubusercontent.com/38023239/108972441-4812fd80-76be-11eb-953b-05a0226efe4e.png)

![image](https://user-images.githubusercontent.com/38023239/108972302-1e59d680-76be-11eb-93da-a03a7bfe8ef0.png)

Is there anything else I need to configure？

**Comment by harshavardhana** [comment]
> Provider provider =
>                 new AssumeRoleProvider(
>                         "http://127.0.0.1:9000/",
>                         "minioadmin",
>                         "minioadmin",
>                         null, // Duration seconds if available.
>                         null, // Policy if available.
>                         null, // Region if available.
>                         null, // Role ARN if available.
>                         null, // Role session name if available.
>                         null, // External ID if available.
>                         null);
>         Credentials credentials = provider.fetch();
>         String s = ReflectionToStringBuilder.toString(credentials);
>         System.out.println(s);

root credentials are not allowed to perform assume-role - create a sub-user https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html
