### ISSUE TITLE
listObjects does not return the continuation string

### ISSUE THREAD

**Issue by lem21h** [minio/minio-java#1169]
When calling for the list of objects with the `listObjects` method there is no way of extracting the `continuationToken` as the response from the MinioAPI is "hidden".
From the library:

method `private Iterable<Result<Item>> listObjectsV2(ListObjectsArgs args)`
```
ListObjectsV2Response response =
                listObjectsV2(
                    args.bucket(),
                    args.region(),
                    args.delimiter(),
                    args.useUrlEncodingType() ? "url" : null,
                    args.startAfter(),
                    args.maxKeys(),
                    args.prefix(),
                    (result == null) ? args.continuationToken() : result.nextContinuationToken(),
                    args.fetchOwner(),
                    args.includeUserMetadata(),
                    args.extraHeaders(),
                    args.extraQueryParams());
            result = response.result();
            this.listObjectsResult = response.result();
 ```

The "fastest" solution would be to add to `ObjectIterator` a getter method for `listObjectsResult`

**Comment by balamurugana** [comment]
Inherit `MinioClient` and use protected [listObjectsV2()](https://minio-java.min.io/io/minio/MinioClient.html#listObjectsV2-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.Integer-java.lang.String-java.lang.String-boolean-boolean-com.google.common.collect.Multimap-com.google.common.collect.Multimap-) for low level access.
