### ISSUE TITLE
Unable to request bucket details or get object with latest (v8.1.0) api

### ISSUE THREAD

**Issue by tejzpr** [minio/minio-java#1171]
I have a Minio Server hosted behind a SSO authentication service provider. When I try to access this Minio Service by passing the Client Secret / Key but I am unable to get Bucket details or get objects because in the v8.x of the API the Java client passes Authorization headers by default and the SSO idp throws 401 because the passed Authorization header is specific to AWS and is invalid according to SSO idp.

e.g. Headers passed by the Minio Java client API
```
Accept-Encoding: identity
User-Agent: MinIO (Mac OS X; x86_64) minio-java/8.1.0
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20210318T185519Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210318/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
```
This Authorization header is invalid for a local Minio setup.

**Comment by balamurugana** [comment]
I am not able to understand the problem you are facing. Please describe clearly with a code along with HTTP traces.
