### ISSUE TITLE
Minio Gateway Azure mode throws API Not Implemented Error for getObjectTags()

### ISSUE THREAD

**Issue by bipin-khakha** [minio/minio-java#1173]
Deployment details :  Minio - v8.0.3  in gateway azure mode .

Problem Description : When I try to use the method minioClient.getObjectTags() Minio returns API Not Implemented Error

io.minio.errors.ErrorResponseException: A header you provided implies functionality that is not implemented
at io.minio.MinioClient.execute(MinioClient.java:775) ~[minio-8.0.3.jar:8.0.3]

Is this a known limitation as mentioned in the official doc ->https://docs.min.io/docs/minio-gateway-for-azure.html
_Only read-only bucket policy supported at bucket level, all other variations will return API Notimplemented error._

Could you please confirm if it supports tag operation in minio gateway mode ?

**Comment by harshavardhana** [comment]
Correct object tagging is not going to be implemented for all gateways.
