### ISSUE TITLE
Hello, about io.minio.messages.Initiator.displayName, the missing issue 

### ISSUE THREAD

**Issue by goodready** [minio/minio-java#1177]
About calling listParts(), query the uploaded part list interface. Report the following error 

org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=DisplayName, type=void, data=false, required=true) on field 'displayName' private java.lang.String io.minio.messages.Initiator.displayName in class io.minio.messages.Initiator at line 2
	at io.minio.Xml.unmarshal(Xml.java:55)
	at io.minio.MinioClient.listParts(MinioClient.java:4729)

It is found that the definition of java sdk is different from that of Amazon S3 ，https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/API/API_Initiator.html Contents DisplayName Name of the Principal. Type: String Required: No ID If the principal is an AWS account, it provides the Canonical User ID. If the principal is an IAM User, it provides a user ARN value. Type: String Required: No 。DisplayName Not required ，but  minio-java sdk Must be defined 。I don’t know how to configure it, if I don’t configure it, how can I solve it

**Comment by balamurugana** [comment]
`Initiator` has to be provided for `ListParts` S3 API. The specification of `Initiator` is generic for various S3 APIs. Cross check with AWS S3 service.
