### ISSUE TITLE
How can Upload a FilePart with java SDK

### ISSUE THREAD

**Issue by ArminNrz** [minio/minio-java#1185]
I want to upload a FilePart with java SDK but how can I do it? I found a method which call uploadMono(FilePart) but there is not any sample of it
Can you help me?1

**Comment by balamurugana** [comment]
Please go through [API documentation](https://docs.min.io/docs/java-client-api-reference.html), [Javadoc](https://minio-java.min.io/) and [examples](https://github.com/minio/minio-java/tree/master/examples)
