### ISSUE TITLE
Java remove object

### ISSUE THREAD

**Issue by jeremiahjp** [minio/minio-java#1190]
When attempting to remove an object, I'm not provided any information as to if that deletion was successful.
Is this intended? How are we to determine if the deletion was successful, other than querying to see if the file exists after attempted deletion?

**Comment by balamurugana** [comment]
According to S3 specification, [DeleteObject API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html) returns 2xx HTTP status for success; else respective HTTP status is returned along with optional error message.  `minio-java` throws an exception for non 2xx HTTP status code. If no exception means the call succeeded. 

Most of S3 servers are eventual consistency i.e. after successful delete object call, the object may appear for a while and disappears.

**Comment by jeremiahjp** [comment]
If I attempt to delete a object that does not exist, I am not getting any exceptions. This is intended? 

I apologize for asking this question here in the issues tracker. I wasn't having any luck over on stackoverflow

**Comment by jeremiahjp** [comment]
> According to S3 specification, [DeleteObject API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html) returns 2xx HTTP status for success; else respective HTTP status is returned along with optional error message. `minio-java` throws an exception for non 2xx HTTP status code. If no exception means the call succeeded.
> 
> Most of S3 servers are eventual consistency i.e. after successful delete object call, the object may appear for a while and disappears.

If I attempt to delete a object that does not exist, I am not getting any exceptions. This is intended?

I apologize for asking this question here in the issues tracker. I wasn't having any luck over on stackoverflow

**Comment by balamurugana** [comment]
Please go through the specification.
