### ISSUE TITLE
no path allowed in endpoint

### ISSUE THREAD

**Issue by yangqi12345** [minio/minio-java#1195]
my endpoint is  :  http://file.test.com/oss
 
An error occurred during runtime ：

![image](https://user-images.githubusercontent.com/16695153/121151110-abdcc300-c876-11eb-9520-e4d11732f1e9.png)

How to solve this？

**Comment by balamurugana** [comment]
Configure your reverse proxy or gateway or server accordingly.

**Comment by balamurugana** [comment]
Yes

**Comment by yangqi12345** [comment]
Hope the next version can allow！
Because there are multiple applications on the same server ~
thank you very much

**Comment by balamurugana** [comment]
As per S3 specification, it is not possible. Configure your server accordingly.

**Comment by zsinba** [comment]
the same issue.
