### ISSUE TITLE
Content-md5 header in copy-object request causes error for OVH S3

### ISSUE THREAD

**Issue by takicichy** [minio/minio-java#1200]
Hello,
I have an issue when using minio-java with OVH object storage. I am not sure if it's not OVH fault, so maybe someone here will know :) 
When I try to do copyobject with minio-java I get "BadDigest, message = The Content-MD5 you specified did not match what we received." 

Error:
```request={method=PUT, url=https://s3.sbg.cloud.ovh.net/975ad647-a2c0-4814-a98b-6c6c4fa87ecd/20210614_122527-recording_20210531%20%281%29uuu.mp4, headers=x-amz-copy-source: /975ad647-a2c0-4814-a98b-6c6c4fa87ecd/20210614_122527-recording_20210531%20%281%29.mp4
Host: s3.sbg.cloud.ovh.net
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.2.1
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20210614T102537Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210614/SBG/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=x-amz-id-2: tx72343af9279c49d3b03d9-0060c72ea1
x-amz-request-id: tx72343af9279c49d3b03d9-0060c72ea1
Content-Type: application/xml
X-Trans-Id: tx72343af9279c49d3b03d9-0060c72ea1
X-Openstack-Request-Id: tx72343af9279c49d3b03d9-0060c72ea1
Date: Mon, 14 Jun 2021 10:25:37 GMT
Transfer-Encoding: chunked
X-IPLB-Request-ID: C12E2F01:B3F6_3626E64C:01BB_60C72EA1_F5D52B:832A
X-IPLB-Instance: 40198
}
```

```Caused by: io.minio.errors.ErrorResponseException: The Content-MD5 you specified did not match what we received.
  at io.minio.S3Base.execute(S3Base.java:667)
  at io.minio.S3Base.execute(S3Base.java:460)
  at io.minio.S3Base.executePut(S3Base.java:794)
  at io.minio.MinioClient.copyObject(MinioClient.java:480)
```

It only happens with objects that are larger than 5MB (small ones work) and only for objects which were not copied before (after they are copied it starts working for them).

Aws-Cli client is not sending Content-MD5 with the PUT request in this case and there are no problems, but I am not sure what is proper behaviour in this case.

**Comment by balamurugana** [comment]
@takicichy According to S3 specification, sending valid `content-md5` header should be sent when `x-amz-content-sha256` header value is `UNSIGNED-PAYLOAD`. It is sever issue and needs to be fixed at server side.

If you want to use `minio-java` for custom implementation of server, you could inherit and override respective methods.
