### ISSUE TITLE
removeIncompleteUpload is missing,how to remove a bucket

### ISSUE THREAD

**Issue by X5207** [minio/minio-java#1202]
before when I remove a bucket,I will deleteObject、removeIncompleteUpload and removeBucket at V7.1.0 
now I use V8.1.0 removeIncompleteUpload is missing

**Comment by balamurugana** [comment]
Inherit `MinioClient` and use [abortMultipartUpload()](https://minio-java.min.io/io/minio/S3Base.html#abortMultipartUpload-java.lang.String-java.lang.String-java.lang.String-java.lang.String-com.google.common.collect.Multimap-com.google.common.collect.Multimap-)

Note: `minio-java` doesn't leave any stale incomplete uploads.

**Comment by X5207** [comment]
do you have an example?

**Comment by X5207** [comment]
before I do it：
boolean exists = minioClient.bucketExists(BucketExistsArgs.builder().bucket(bucketName).build());
            if (exists) {
                deleteObject(minioClient, bucketName, ""); // 先将内部文件全部删除
                 minioClient.removeIncompleteUpload(
                 RemoveIncompleteUploadArgs.builder().bucket(bucketName).object("/").build());
                minioClient.removeBucket(RemoveBucketArgs.builder().bucket(bucketName).build());
            }

now I will how to do  in 8.1

**Comment by balamurugana** [comment]
Refer https://minio-java.min.io/io/minio/S3Base.html#abortMultipartUpload-java.lang.String-java.lang.String-java.lang.String-java.lang.String-com.google.common.collect.Multimap-com.google.common.collect.Multimap-
