### ISSUE TITLE
Uploading files using the Java SDK results in a Resetting to invalid mark error when part size is more than 2gb.

### ISSUE THREAD

**Issue by ivanmgb** [minio/minio-java#1203]
We are building the Put objects argument builder as follows:

`PutObjectArgs.builder()
                .bucket("test-bucket")
                .object("test-identifier")
                .stream(stream, -1, 3000000000)
                .contentType("application/octet-stream")
                .build();`

This works well for both Minio server and Amazon S3 but we noticed that when we set the part size to more than 2gb, in this case its 3000000000 it throws an error when uploading.

Part sizes lesser than or equal to 2gb works.

The stream we are passing is a bufferedinputstream.

Uploading via presigned urls works even if the part size is more than 2gb.

This happens whether the file size we are uploading is greater than or lesser than the part size.

## Expected Behavior
Should be able to upload a file in Minio/S3

## Current Behavior
Upload fails with the error:

`Caused by: java.io.IOException: Resetting to invalid mark
at java.base/java.io.BufferedInputStream.reset(BufferedInputStream.java:454)
at io.minio.S3Base.getAvailableSize(S3Base.java:1230)
at io.minio.S3Base.putObject(S3Base.java:1134)
at io.minio.MinioClient.putObject(MinioClient.java:1666)`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
Minio 8.2.1

**Comment by balamurugana** [comment]
@ivanmgb If I understand correctly you are trying to upload ~3TB data; when part size is set > 2GIB, you are getting `IOException` on `Resetting to invalid mark at java.base/java.io.BufferedInputStream.reset(BufferedInputStream.java:454)`. I hope you are aware what you are doing in terms of memory usage if part size is higher and higher.

As the exception occurred at java library, you may need to tweak memory parameters to JRE. You could refer below java arguments for more information regarding this.
```
-Xmn<size>        sets the initial and maximum size (in bytes) of the heap for the young generation (nursery)
-Xms<size>        set initial Java heap size
-Xmx<size>        set maximum Java heap size
```

**Comment by ivanmgb** [comment]
Hi @balamurugana, thanks for the response.

Uploading files regardless of size results in the same error.

**Comment by klauspost** [comment]
@balamurugana I am not java expert, but it would seem to me that you are overflowing the int conversion when > 2G here:

https://github.com/minio/minio-java/blob/836359242f62c5add495a873d26a7c071f182a02/api/src/main/java/io/minio/S3Base.java#L1218

So sending negative size?

**Comment by balamurugana** [comment]
> @balamurugana I am not java expert, but it would seem to me that you are overflowing the int conversion when > 2G here:
> 
> https://github.com/minio/minio-java/blob/836359242f62c5add495a873d26a7c071f182a02/api/src/main/java/io/minio/S3Base.java#L1218
> 
> So sending negative size?

@klauspost 
After few checks, `int` in java is 32 bits always and [BufferedInputStream.mark()](https://docs.oracle.com/javase/8/docs/api/java/io/BufferedInputStream.html#mark-int-) accepts `int` which limits to 2GB, hence there is no solution with `BufferedInputStream` i.e. user has to use 2GB part size max. This check can be added in `minio-java`.

**Comment by ivanmgb** [comment]
Thanks for checking @balamurugana and @klauspost. We will use 2gb as our max part size value.

**Comment by klauspost** [comment]
@balamurugana Is the buffer essential to have the same size as the part size?

**Comment by balamurugana** [comment]
@ivanmgb As per the limitation in `java` (Refer: https://github.com/minio/minio-java/issues/1203#issuecomment-867688002), you cannot use 2GB part size for unknown sized stream.

Solutions:
1. Use maximum part size as 2GiB in this case.
2. Leave part size to be auto-calculated by `minio-java`.
3. If you are particular on part size more than 2GiB, upload desired part size from the stream as new objects and use [composeObject()](https://minio-java.min.io/io/minio/MinioClient.html#composeObject-io.minio.ComposeObjectArgs-) for final object.

**Comment by balamurugana** [comment]
> @balamurugana Is the buffer essential to have the same size as the part size?

Yes, for unknown sized stream.

**Comment by balamurugana** [comment]
> @balamurugana Is the buffer essential to have the same size as the part size?

@klauspost FYI https://github.com/minio/minio-java/issues/1204
