### ISSUE TITLE
Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE)

### ISSUE THREAD

**Issue by cunkoulidaye** [minio/minio-java#1206]
我在使用Minioclient的时候，报错：A connection to http://localhost:9000/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE)

**Comment by balamurugana** [comment]
Please provide necessary information along with stack and HTTP traces.
