### ISSUE TITLE
Failed to authenticate with proxy

### ISSUE THREAD

**Issue by jeffreism** [minio/minio-java#1207]
Hi there,

Is there a way to configure the MinIO Java API to access a server behind a proxy? I'm sorry if this is basic, but I couldn't find any reference on how to make MinIO properly authenticate and connect to the endpoint, I keep seeing the error "java.io.IOException: Failed to authenticate with proxy".

Thanks in advance for any insight!

**Comment by balamurugana** [comment]
Use custom http client [here](https://minio-java.min.io/io/minio/MinioClient.Builder.html#httpClient-okhttp3.OkHttpClient-) to be created like [here](https://stackoverflow.com/questions/37866902/okhttp-proxy-settings)

**Comment by jeffreism** [comment]
> Use custom http client [here](https://minio-java.min.io/io/minio/MinioClient.Builder.html#httpClient-okhttp3.OkHttpClient-) to be created like [here](https://stackoverflow.com/questions/37866902/okhttp-proxy-settings)

It easily solved the problem, thank you!
