### ISSUE TITLE
Support DurationSeconds in LdapIdentityProvider

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#1210]
https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/credentials/LdapIdentityProvider.java

**Comment by balamurugana** [comment]
@harshavardhana `minio-go` does not have this support. is it intentional to make this support in `minio-java`?

**Comment by harshavardhana** [comment]
> @harshavardhana `minio-go` does not have this support. is it intentional to make this support in `minio-java`?

We should make minio-go also support it @balamurugana server already supports it anyways.
