### ISSUE TITLE
Update Guava dependency to > 30.0-jre causing boot issue

### ISSUE THREAD

**Issue by irizzant** [minio/minio-java#1216]
Hello
I found the following error while booting Jboss EAP 7.3 with Jandex:

```
ERROR: Could not index com/google/common/util/concurrent/ClosingFuture.class: Class extends type annotation appeared on a non class target
```

According to this issue https://github.com/wildfly/jandex/issues/93 updating Guava dependency to 30.1-jre fixed the problem.

Can you please update the dependency version?

Thanks

**Comment by balamurugana** [comment]
@irizzant Are you seeing referred problem when using `minio-java`?

**Comment by irizzant** [comment]
@balamurugana sorry why is this issue closed? 
Anyway I'm using the following in my Maven dependencies:
```
<!-- https://mvnrepository.com/artifact/io.minio/minio -->
<dependency>
    <groupId>io.minio</groupId>
    <artifactId>minio</artifactId>
    <version>8.3.0</version>
</dependency>
```

**Comment by balamurugana** [comment]
@irizzant Updating guava is not a problem. The question is, as  we use limited usage on guava. does `minio-java` exhibit the issue you mentioned due to guava 30.0-jre?

**Comment by irizzant** [comment]
@balamurugana the problem with `minio-java` arises because of its dependency on 30.0-jre. 
Updating to 30.1-jre fixed the boot issue I reported.
