### ISSUE TITLE
Method did not exist okhttp3.RequestBody.create(byte[], okhttp3.MediaType)

### ISSUE THREAD

**Issue by Dacesilian** [minio/minio-java#1222]
I have a problem when starting Spring app and creating MinioClient. Why is it using okhttp 3.14.9 although I specify version 4.8.1?

```
MinioClient.builder().endpoint(endpoint).credentials(accessKey, secretKey).build();
```

```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.minio.S3Base.<clinit>(S3Base.java:105)

The following method did not exist:

    'okhttp3.RequestBody okhttp3.RequestBody.create(byte[], okhttp3.MediaType)'

The method's class, okhttp3.RequestBody, is available from the following locations:

    jar:file:/C:/Java/m2repo/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar!/okhttp3/RequestBody.class

The class hierarchy was loaded from the following locations:

    okhttp3.RequestBody: file:/C:/Java/m2repo/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of okhttp3.RequestBody

```

Using these version:
![image](https://user-images.githubusercontent.com/823994/130237536-53628455-c8c3-4cdf-8c7a-517bb0ff6ebd.png)
![image](https://user-images.githubusercontent.com/823994/130237752-495699e2-de16-47df-991f-b337d8c4f147.png)
It's not working with default setting neither.

Thanks.

**Comment by balamurugana** [comment]
You would need to resolve `okhttp` dependency appropriately. This [doc](https://www.baeldung.com/maven-plugin-override-parent) might be useful.

**Comment by Dacesilian** [comment]
Yes, version is overriden by Spring, I had to add property:

`<okhttp3.version>4.9.1</okhttp3.version>`
