### ISSUE TITLE
Can i use the same client object for multiple requests ?

### ISSUE THREAD

**Issue by seb-saletes** [minio/minio-java#1226]
Hi,

Is it ok to use a singleton with the same client object for multiple request ?

```
@Singleton
public class S3Service {

  private final MinioClient mc;

  @Inject
  public S3Service(Config config) {
    this.mc = MinioClient.builder()
                         .endpoint("https://s3.amazonaws.com")
                         .credentials("-", "-")
                         .build();
  }

  public void createObject(String bucketName, String name, InputStream file) {
    try {
      this.mc.putObject(
          PutObjectArgs.builder()
                       .bucket(bucketName)
                       .object(name)
                       .stream(file, -1, 10485760)
                       .contentType("application/pdf")
                       .build()
      );
    } catch (MinioException | InvalidKeyException | IOException | NoSuchAlgorithmException e) {
      e.printStackTrace();
    }
  }
}
```

Using this code I have sporadic errors (unexpected end of stream, \n not found: limit=0 content=…) and I was wondering if using the same client could be the cause ?

**Comment by balamurugana** [comment]
Yes. You can use same `MinioClient` is multiple threads. We already have [functional test](https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L788) for that. WRT `putObject()`, you should not use same `stream` in multiple threads.

**Comment by seb-saletes** [comment]
Thank you for your quick answer. 

Please could you clarify what do you mean by 

> you should not use same stream in multiple threads

In my example, do you notice something that could lead to unexpected end of stream, \n not found: limit=0 content=… ?

Thanks for your time

**Comment by balamurugana** [comment]
I mean `InputStream` is not thread safe. I find no problem in your code snippet. As the error is not S3 error, I don't understand it as well.
