### ISSUE TITLE
Difference between StatObjectResponse and Item

### ISSUE THREAD

**Issue by bwgjoseph** [minio/minio-java#1229]
Hi,

I'm working on a project that grab a list of [Item](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/messages/Item.java) via [listObjects](https://docs.min.io/docs/java-client-api-reference#listObjects) API and a single item ([StatObjectResponse](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/StatObjectResponse.java)) via [statObject](https://docs.min.io/docs/java-client-api-reference#statObject) API.

However, I noticed that when fetching the `metadata`, `StatObjectResponse` strips off `x-amz-meta` prefix

https://github.com/minio/minio-java/blob/9d5b365b6cc9849220ba12fe9ca3fe2c35cbd650/api/src/main/java/io/minio/StatObjectResponse.java#L64-L71

but `Item` seem to use as is.

Is there any reason for it? Was it mentioned in the docs?

Thanks

**Comment by balamurugana** [comment]
`StatObject` is S3 specification complaint whereas user metadata through `ListObject` is `MinIO` specific extension i.e. this option is not available other than `MinIO` server.

**Comment by bwgjoseph** [comment]
So when reading the metadata, depending on the API I use, I have to read the `metadata` differently? 

`ListObjects` - read as is `x-amz-meta-xxx`  
`Item` - read `xxx`

Is that right?

**Comment by balamurugana** [comment]
You could have a wrapper method to strip/prepend `x-amz-meta-` according to your use case.
