### ISSUE TITLE
minio sdk调用removeObjects() 批量删除文件超过1000问题。 

### ISSUE THREAD

**Issue by dzpxlz** [minio/minio-java#1237]
你好,我测试了7.0.2的版本,如果批量删除文件超过1000 ,只会删除1000个文件。后续文件会被丢弃，导致调用者认为调用成功。不好排查问题。 今天我升级了minio到了8.3.0的版本 我看源码还是存在这个问题。建议能否和阿里的OSS SDK一样如果超过1000 给出一个优化的提示。
例子:
if (keys.size() > DELETE_OBJECTS_ONETIME_LIMIT) {
            throw new IllegalArgumentException(
                    "The count of keys to delete exceed max limit " + DELETE_OBJECTS_ONETIME_LIMIT);
        }

**Comment by balamurugana** [comment]
Please share your code. Also enable `traceOn()` and share the output here.

**Comment by dzpxlz** [comment]
minioClient.removeObjects(bucketName, list)  我就这样用的 但我的list 大于了1000,  1000以内的是删除了，但1000后的没有被删除掉。 设计就是这样的嘛。。。。

**Comment by balamurugana** [comment]
This issue got fixed in the latest release. If you still face the problem in the latest release, enable `traceOn()` and share the output here.
