### ISSUE TITLE
SHA256 hash computation penalty when using sidekick

### ISSUE THREAD

**Issue by davoustp** [minio/minio-java#1262]
Hi,

When running an app using the minio-java client to connect to a minio cluster via a sidekick sidecar container (running in Kubernetes), the app is suffering from the cost of  computing the SHA256 hash when invoking `putObject`.

This is fairly easy to see why:

https://github.com/minio/sidekick is designed as a proxy providing TLS termination - the app connects using plain HTTP onto the sidecar (TLS support has been denied, see [#24 ](https://github.com/minio/sidekick/issues/24))

And the minio-java client is using the scheme of the target URI to determine whether it should compute the sha256 hash or not, in `io.minio.S3Base.putObject(PutObjectBaseArgs, Object, long, long, int, String)` (line 1121):
```
        PartSource partSource = partReader.getPart(!this.baseUrl.isHttps());
```
where the boolean argument to `PartReader.getPart(boolean computeSha256)` is obviously true when scheme is `http`.

Any way to avoid the cost of this hash computation when using sidekick?

**Comment by balamurugana** [comment]
As per S3 specification, sha256 hash needs to be calculated/used/sent. If you use TLS i.e. HTTPS, in many cases, `UNSIGNED-PAYLOAD` is the value used instead of actual sha256 hash. This way you can void sha256 calculation in most of the places.

**Comment by harshavardhana** [comment]
> https://github.com/minio/sidekick is designed as a proxy providing TLS termination - the app connects using plain HTTP onto the sidecar (TLS support has been denied, see [#24 ](https://github.com/minio/sidekick/issues/24))

You can use `sidekick` with local certs, so that you can talk over TLS locally. 

```
  --cert value                        server certificate file
  --key value                         server private key file
```

**Comment by davoustp** [comment]
That's great news, thanks!
The option description could be a little bit more explicit so that user knows more easily they control client-side TLS support (I should have guessed, but guessing is hardly a reliable documentation process).
Anyway, this closes this issue. 👍 
Thanks again!
