### ISSUE TITLE
PostPolicy doesn't support the file length greater than 1GB.

### ISSUE THREAD

**Issue by ypji** [minio/minio-java#1269]
https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/PostPolicy.java

Integer.MAX_VALUE can only represent a file whose length not greater than 1GB.

**Comment by harshavardhana** [comment]
@ypji that is an okay limit - use PresignedPutObject instead.

**Comment by balamurugana** [comment]
Why do you have 1GB limit in your java?

**Comment by ypji** [comment]
I want to pre-sign a file upload which size between 1B and 5GB. The website uses this policy, upload the file via multipart/form-data.

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-java/pull/1270
