### ISSUE TITLE
Error occurred:io.minio.errors.InternalException: unhandled HTTP code 429

### ISSUE THREAD

**Issue by wahyuwidagdo** [minio/minio-java#1274]
Hi, I just got an error when trying hit my service that using minio to store my object.
I don't really know what is going on but on my console it only display : Error occurred:io.minio.errors.InternalException: unhandled HTTP code 429.  Please report this issue at https://github.com/minio/minio-java/issues

 I am using Minio 8.2.2 version by the way, before using Minio 8.2.2, I was using Minio 8.3.3 and 8.3.0 but got an error : Unsupported Okhttp library found. Must use okhttp >= 4.8.1
 
 Thank you~

**Comment by balamurugana** [comment]
Use the latest release of `minio-java` and reopen if the issue still exhibits.
