### ISSUE TITLE
Can't download files with presigned URL

### ISSUE THREAD

**Issue by innovationhub-asia** [minio/minio-java#1275]
After upgrading to 8.3.4 version, any attempt to download a file with presigned URLs fails with error:

```
<Error>
<Code>AccessDenied</Code>
<Message>There were headers present in the request which were not signed</Message>
<Key>6142949676471660040_121.jpg</Key>
<BucketName>testing-incoming</BucketName>
<Resource>/6142949676471660040_121.jpg</Resource>
<RequestId>16BCEA5AC683F9AE</RequestId>
<HostId>bf97ca14-e8b3-414f-9dea-de47d980c1c8</HostId>
</Error>
```

Same java library is used to generate the URL and then download.

**Comment by harshavardhana** [comment]
> <Error>
> <Code>AccessDenied</Code>
> <Message>There were headers present in the request which were not signed</Message>
> <Key>6142949676471660040_121.jpg</Key>
> <BucketName>testing-incoming</BucketName>
> <Resource>/6142949676471660040_121.jpg</Resource>
> <RequestId>16BCEA5AC683F9AE</RequestId>
> <HostId>bf97ca14-e8b3-414f-9dea-de47d980c1c8</HostId>
> </Error

share your presigned-urls @innovationhub-asia ?

**Comment by innovationhub-asia** [comment]
https://hosname/bucket/6142949676471660040_121.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XZ30XDZPCHXZDXG3DFKM%2F20211202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211202T100303Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=a3ccc260c55ff8dc668e7eb953e0c90c26ae27a88834f40e59ee0a8cbdf38615

BTW, downgrading to 8.3.3 seems to help.

**Comment by innovationhub-asia** [comment]
Same works for 8.3.4 if we force add content-type header:

curl --location --request GET 'https://hosname/bucket/6142949676471660040_121.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XZ30XDZPCHXZDXG3DFKM%2F20211202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211202T100303Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=a3ccc260c55ff8dc668e7eb953e0c90c26ae27a88834f40e59ee0a8cbdf38615' \
--header 'Content-Type: image/jpeg'

**Comment by balamurugana** [comment]
Yep. You would need to pass `Content-Length` and `Content-Type` from `minio-java v8.3.4` onward.

**Comment by harshavardhana** [comment]
> Same works for 8.3.4 if we force add content-type header:
> 
> curl --location --request GET 'https://hosname/bucket/6142949676471660040_121.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XZ30XDZPCHXZDXG3DFKM%2F20211202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211202T100303Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=a3ccc260c55ff8dc668e7eb953e0c90c26ae27a88834f40e59ee0a8cbdf38615' \
> --header 'Content-Type: image/jpeg'

Since you set content-type as requirement for presigned upload you need to specify that during upload.

**Comment by innovationhub-asia** [comment]
I see, so behavior changed somehow.

This is the code I use:

```
var objectUrl = minioClient.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder()
        .bucket(bucketName)
        .method(Method.GET)
        .extraHeaders(Map.of("Content-Type", contentType))
        .object(fileName).build());
``` 

without setting Content-Type header, the downloaded file has no content type, but before, in prior versions, setting extra headers was not a condition/requirement for downloading.

**Comment by harshavardhana** [comment]
> .extraHeaders(Map.of("Content-Type", contentType))

yes you shouldn't set this @innovationhub-asia - this not correct for GET request.

**Comment by innovationhub-asia** [comment]
Will try without it, but without setting this header, at least before, the downloaded file was missing content-type, which confuses many clients.

**Comment by harshavardhana** [comment]
> Will try without it, but without setting this header, at least before, the downloaded file was missing content-type, which confuses many clients.

The previous implementation was not correct we fixed it properly with the correct requirements. Your usage of presignedURLs is wrong.

Two ways to fix content-type

- Your object when it was uploaded should have the correct content-type set i.e during PUT operation.
-  You can also set something called as `response-content-type` value which is not going to be signed as part of the HTTP headers and it should passed as a query param which allows server to override the content-type in the response.

**Comment by innovationhub-asia** [comment]
Thanks, will follow this guidance.

**Comment by harshavardhana** [comment]
See the example here 

https://docs.min.io/docs/java-client-api-reference.html#getPresignedObjectUrl

```java
// Get presigned URL string to upload 'my-objectname' in 'my-bucketname' 
// with response-content-type as application/json and life time as one day.
Map<String, String> reqParams = new HashMap<String, String>();
reqParams.put("response-content-type", "application/json");

String url =
    minioClient.getPresignedObjectUrl(
        GetPresignedObjectUrlArgs.builder()
            .method(Method.PUT)
            .bucket("my-bucketname")
            .object("my-objectname")
            .expiry(1, TimeUnit.DAYS)
            .extraQueryParams(reqParams)
            .build());
System.out.println(url);
```
