### ISSUE TITLE
minio client's listObjects api doesn't retrieve more than 1000 objects at once from s3

### ISSUE THREAD

**Issue by avinash-zemoso** [minio/minio-java#1278]
We have more than a million objects in our s3 bucket. These objects have different prefixes e.g AA, BB...II.  Our usecase is to retrieve objects that match a specific prefix. However, since minoclient listObjects api doesn't retrieve more than 1000 objects in s3, the listObjects call is taking significantly large amount of time ~ 2min to return all the objects matching prefix. 

Is there a work around to avoid huge response times?

**Comment by harshavardhana** [comment]
> We have more than a million objects in our s3 bucket. These objects have different prefixes e.g AA, BB...II. Our usecase is to retrieve objects that match a specific prefix. However, since minoclient listObjects api doesn't retrieve more than 1000 objects in s3, the listObjects call is taking significantly large amount of time ~ 2min to return all the objects matching prefix.

The performance listing is based on the performance of your backend @avinash-zemoso - make sure you are using good setup. 

Please explain your setup.

**Comment by balamurugana** [comment]
As per S3 specification, S3 service returns maximum 1000 objects in a batch. Nothing can be done at client side. Another option is you could retrieve different prefixes using multiple `listObjects()` in parallel to minimize response time.

**Comment by avinash-zemoso** [comment]
@balamurugana The issue here is that, because of the limitation of S3, retrieving objects with one particular prefix is itself taking few minutes. Is there a way to solve this problem on client side?

**Comment by avinash-zemoso** [comment]
> > We have more than a million objects in our s3 bucket. These objects have different prefixes e.g AA, BB...II. Our usecase is to retrieve objects that match a specific prefix. However, since minoclient listObjects api doesn't retrieve more than 1000 objects in s3, the listObjects call is taking significantly large amount of time ~ 2min to return all the objects matching prefix.
> 
> The performance listing is based on the performance of your backend @avinash-zemoso - make sure you are using good setup.
> 
> Please explain your setup.

We have an application using minio client to retrieve S3 objects starting with a specific prefix. Can you please provide more information on what you would like to know when you say setup?

**Comment by harshavardhana** [comment]
> > > We have more than a million objects in our s3 bucket. These objects have different prefixes e.g AA, BB...II. Our usecase is to retrieve objects that match a specific prefix. However, since minoclient listObjects api doesn't retrieve more than 1000 objects in s3, the listObjects call is taking significantly large amount of time ~ 2min to return all the objects matching prefix.
> > 
> > The performance listing is based on the performance of your backend @avinash-zemoso - make sure you are using good setup.
> > 
> > Please explain your setup.
> 
> @harshavardhana We have an application using minio client to retrieve S3 objects starting with a specific prefix. Can you please provide more information on what you would like to know when you say setup?

Yes I meant where is the server ?

**Comment by balamurugana** [comment]
> @balamurugana The issue here is that, because of the limitation of S3, retrieving objects with one particular prefix is itself taking few minutes. Is there a way to solve this problem on client side?

As your server is slow, nothing can be done at client side.

**Comment by avinash-zemoso** [comment]
> > > > We have more than a million objects in our s3 bucket. These objects have different prefixes e.g AA, BB...II. Our usecase is to retrieve objects that match a specific prefix. However, since minoclient listObjects api doesn't retrieve more than 1000 objects in s3, the listObjects call is taking significantly large amount of time ~ 2min to return all the objects matching prefix.
> > > 
> > > 
> > > The performance listing is based on the performance of your backend @avinash-zemoso - make sure you are using good setup.
> > > Please explain your setup.
> > 
> > 
> > @harshavardhana We have an application using minio client to retrieve S3 objects starting with a specific prefix. Can you please provide more information on what you would like to know when you say setup?
> 
> Yes I meant where is the server ?

The server is on-premises. It's in-house.

**Comment by harshavardhana** [comment]
> The server is on-premises. It's in-house.

Is it MinIO ? who is the vendor?

**Comment by avinash-zemoso** [comment]
we are using MinIo as a client. We ourselves are maintaining s3.

**Comment by harshavardhana** [comment]
> we are using MinIo as a client. We ourselves are maintaining s3.

Then the issue server implementation here @avinash-zemoso - the client cannot help you gain performance.
