### ISSUE TITLE
No virtual method getParameterCount() error on android 

### ISSUE THREAD

**Issue by iamkhan001** [minio/minio-java#1280]
Hi,
We are using minio in android app but it keeps crashing when tired to create instance. 
please help on this

`    java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Constructor; or its super classes (declaration of 'java.lang.reflect.Constructor' appears in /system/framework/core-oj.jar)`

**Comment by balamurugana** [comment]
It seems like your Android SDK doesn't have respective java 8 methods. You would need to use API level >= 26.

**Comment by antonymarion** [comment]
And what if I am using a device where I do not have the control over the Android version used which is 25 ?

Is there any working alternative for minio client on java/kotlin?
