### ISSUE TITLE
so, why 8.2.2 is fine, 8.3.0+ fails?

### ISSUE THREAD

**Issue by Angelica-dahurica** [minio/minio-java#1282]
when i use 8.2.2 with spring boot 2.0, all works fine.

```xml
        <!--minio-->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>8.2.2</version>
        </dependency>
```

but when i switch to 8.3.0+,for example
```xml
        <!--minio-->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>8.3.4</version>
        </dependency>
```
my application can compile and run, but will fail when i upload file.
it shows that `nested exception is java.lang.ExceptionInInitializerError`, 
in detail, `okhttp Could not initialize class io.minio.MinioClient`.
it seems that because of the okhttp version.
with
```xml
       <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.0</version>
        </dependency>
```
8.3.0 is also ok.

all these two(8.2.2, 8.3.4) are use com.squareup.okhttp3:okhttp:jar:3.14.9:compile
because in mino pom, the scope is compile.
```xml
   <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>4.8.1</version>
      <scope>compile</scope>
    </dependency>
```
and in spring boot 2.0, the default okhttp3 version is 3.14.9

so, why 8.2.2 is fine, 8.3.0+ fails?

**Comment by Angelica-dahurica** [comment]
also see https://github.com/minio/minio-java/issues/1238

**Comment by balamurugana** [comment]
You should use okhttp v4.8.1. minio-java >= 8.3 has explicit check at run time too.
