### ISSUE TITLE
Bug for Minio client in lifecycle set expiredObjectDeleteMarker

### ISSUE THREAD

**Issue by matpil** [minio/minio-java#1285]
Hi,
I found this issue in minio 8.3.4 version.
If I follow the [example](https://github.com/minio/minio-java/blob/master/examples/SetBucketLifecycle.java) it works.
but if I set to "true" the expiredObjectDeleteMarker field in Expiration class it fails with error:

```
io.minio.errors.ErrorResponseException: The XML you provided was not well-formed or did not validate against our published schema
	at io.minio.S3Base.execute(S3Base.java:645) ~[minio-8.3.4.jar!/:8.3.4]
	at io.minio.S3Base.execute(S3Base.java:440) ~[minio-8.3.4.jar!/:8.3.4]
	at io.minio.S3Base.executePut(S3Base.java:772) ~[minio-8.3.4.jar!/:8.3.4]
	at io.minio.MinioClient.setBucketLifecycle(MinioClient.java:1886) ~[minio-8.3.4.jar!/:8.3.4]
```

I've tried use Expiration constructor with date or days with same result.

To reprouce this issue you can change in the example the row
`new Expiration((ZonedDateTime) null, 365, null),`
with
`new Expiration((ZonedDateTime) null, 365, true),`

Can you check this function?

Regards
--
matpil

**Comment by balamurugana** [comment]
Please enable `traceOn()` and share the output.

**Comment by matpil** [comment]
Sure!
<code>
---------START-HTTP---------
PUT /?lifecycle= HTTP/1.1
Host: xpcache-repo-dev.s3.eu-central-1.amazonaws.com
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.3.4
Content-MD5: SVRO4MvqL4jQioJrGBhh5w==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20220105T173205Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20220105/eu-central-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Days>120</Days><ExpiredObjectDeleteMarker>true</ExpiredObjectDeleteMarker></Expiration><Filter><Prefix>sito_corporate/</Prefix></Filter><ID>sito_corporate</ID><Status>Enabled</Status></Rule></LifecycleConfiguration>
HTTP/1.1 400
x-amz-id-2: yhhA95p2aNWsq/gmfpmqh5FFuAKJNu/OUgWTxDrHrRYcYUMbW1vnvccF57lzLGNXrA1Y2uk/y0c=
x-amz-request-id: RZQR7DEFT0WCDDR9
Date: Wed, 05 Jan 2022 17:32:06 GMT
x-amz-request-id: RZQR7DEFT0WCDDR9
x-amz-id-2: yhhA95p2aNWsq/gmfpmqh5FFuAKJNu/OUgWTxDrHrRYcYUMbW1vnvccF57lzLGNXrA1Y2uk/y0c=
Content-Type: application/xml
Server: AmazonS3
Content-Length: 280
Connection: close

<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>RZQR7DEFT0WCDDR9</RequestId><HostId>yhhA95p2aNWsq/gmfpmqh5FFuAKJNu/OUgWTxDrHrRYcYUMbW1vnvccF57lzLGNXrA1Y2uk/y0c=</HostId></Error>
----------END-HTTP----------
</code>

Is it enough?

Regards
--
matpil

**Comment by balamurugana** [comment]
As per [the specification](https://docs.aws.amazon.com/AmazonS3/latest/API/API_LifecycleExpiration.html#AmazonS3-Type-LifecycleExpiration-ExpiredObjectDeleteMarker), you are not allowed to set `Days`/`Date` with `ExpiredObjectDeleteMarker`

**Comment by harshavardhana** [comment]
> As per [the specification](https://docs.aws.amazon.com/AmazonS3/latest/API/API_LifecycleExpiration.html#AmazonS3-Type-LifecycleExpiration-ExpiredObjectDeleteMarker), you are not allowed to set `Days`/`Date` with `ExpiredObjectDeleteMarker`

@balamurugana how about we throw a client exception in this case?

**Comment by balamurugana** [comment]
Need to check the code who are all using `Expiration` class.
