### ISSUE TITLE
Mockito can't mock MinioClient

### ISSUE THREAD

**Issue by lenzls** [minio/minio-java#1287]
Good afternoon,

since version 8.3.0, I receive the following error during my integration tests. Version 8.2.2 works just fine. Version 8.3.5 still has the issue.

```
Mockito cannot mock this class: class io.minio.MinioClient.
If you're not sure why you're getting this error, please report to the mailing list.
Java               : 17
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 17.0.1+12
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.1+12
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.11.0-44-generic
You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.
Underlying exception : org.mockito.exceptions.base.MockitoException: Cannot instrument class io.minio.MinioClient because it or one of its supertypes could not be initialized
```

Any idea what could be at fault here?

I'm creating the mock via `mock(MinioClient.class);` and I'm using Mockito version 4.2.0.

Kind regards

**Comment by balamurugana** [comment]
1. `minio-java` is not supported Java 17 yet.
2. No idea about `org.mockito.exceptions.base.MockitoException: Cannot instrument class io.minio.MinioClient because it or one of its supertypes could not be initialized`. You would need to check `Mockito` the meaning and reason for the error.

**Comment by lenzls** [comment]
I see. Thanks for the response.

For what is worth, version 8.2.2 seems to work fine with Java 17. At least the features I'm using.
