### ISSUE TITLE
Is removeObject asynchronous

### ISSUE THREAD

**Issue by ace-bill** [minio/minio-java#1290]
I call removeObject method to delete one object, but sometimes it doesn't be removed immediately because when I call listObjects method, the object still exists. so I wanna know if the removeObject method is asynchronous? if it is, is there other method asynchronous too?

**Comment by balamurugana** [comment]
If `removeObject()` succeeded, the object is deleted successfully at client side. However most of S3 services/servers are eventual consistency i.e. the objects will disappear eventually.
