### ISSUE TITLE
headObject method

### ISSUE THREAD

**Issue by bogdartysh** [minio/minio-java#1291]
Hi,
do we have headObject -like functionality? So one could check object headers/meta/existence without actually reading it?

see https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#headObject

> The HEAD action retrieves metadata from an object without returning the object itself. This action is useful if you're only interested in an object's metadata. To use HEAD, you must have READ access to the object.
> 
> A HEAD request has the same options as a GET action on an object. The response is identical to the GET response except that there is no response body. Because of this, if the HEAD request generates an error, it returns a generic 404 Not Found or 403 Forbidden code. It is not possible to retrieve the exact exception beyond these error codes._

**Comment by balamurugana** [comment]
https://github.com/minio/minio-java/blob/master/docs/API.md#statObject
