### ISSUE TITLE
Lifecycle rule cannot be executed

### ISSUE THREAD

**Issue by danboming** [minio/minio-java#1292]
I added an lifecycle rule to delete the file after one day,but the file is still in the bucket when one day passed. do you have any solution to fix this problem?

**Comment by klauspost** [comment]
Since you don't provide any information whatsoever, I will guess on the cause:

My guess is that you do not know when an object expires:

> Amazon S3 calculates the time by adding the number of days specified in the rule to the time when the new successor version of the object is created and rounding the resulting time to the next day midnight UTC. For example, in your bucket, suppose that you have a current version of an object that was created at 1/1/2014 10:30 AM UTC. If the new version of the object that replaces the current version is created at 1/15/2014 10:30 AM UTC, and you specify 3 days in a transition rule, the transition date of the object is calculated as 1/19/2014 00:00 UTC.

From https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html

**Comment by danboming** [comment]
Thank you! I configed th rule as your description. The current version of object's last modified time is 2022-01-20 12:11:25 UTC。The rule is to delete the current version object after one day of object's last modified time.The Minio defaut timezone is US time zone。Is it the time zone caused the problem?

**Comment by harshavardhana** [comment]
> Thank you! I configed th rule as your description. The current version of object's last modified time is 2022-01-20 12:11:25 UTC。The rule is to delete the current version object after one day of object's last modified time.The Minio defaut timezone is US time zone。Is it the time zone caused the problem?

All expirations happen at UTC midnight from the time the rule was applied and the object has expired.
