### ISSUE TITLE
Get Object numbers and usage in a bucket

### ISSUE THREAD

**Issue by ace-bill** [minio/minio-java#1293]
Is there a method to get the object numbers and usage(including history versions) in a bucket? just like the console on bucket list page.

**Comment by balamurugana** [comment]
Please clearly explain your issue or request.

**Comment by ace-bill** [comment]
<img width="1125" alt="截屏2022-01-26 下午7 03 49" src="https://user-images.githubusercontent.com/92312765/151152924-7a083fbe-9d0a-4b49-8a0c-2e205b308095.png">
Hi
I wanna get the two information as the screenshot, is there an API?

**Comment by balamurugana** [comment]
No. You would need to do `listObjects()` and do respective computations.
