### ISSUE TITLE
Enabling bucket versioning in minio v.8.3.5

### ISSUE THREAD

**Issue by LSmyrnaios** [minio/minio-java#1294]
Hi, I am using the minio-java version 8.3.5 and I want to enable bucket versioning.

In the [Documentation](https://docs.min.io/docs/minio-bucket-versioning-guide.html), it says to use this:

```
minioClient.enableVersioning(EnableVersioningArgs.builder().bucket("my-bucketname").build());
```

But, the "enableVersioning()" and "EnableVersioningArgs" are not there anymore. I tried various ways to enable it including the following, but I get errors.

```
minioClient.setBucketVersioning(SetBucketVersioningArgs.builder().config(new VersioningConfiguration()).region(region).bucket(bucketName).build());
```

What is the right way to do that?

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-java/blob/master/docs/API.md#setBucketVersioning and reopen the issue with error you are getting.

@harshavardhana @ravindk89  https://docs.min.io/docs/minio-bucket-versioning-guide.html needs a fix.

**Comment by LSmyrnaios** [comment]
Thank you for the reference, although I still have some issues.

Firstly, the is no documentation about the "config" which is used. I tried the following:

```
VersioningConfiguration config= new VersioningConfiguration(VersioningConfiguration.Status.ENABLED, false);
```

Secondly, I do not know what the "mfaDelete" argument is, in `VersioningConfiguration()`, I set it to `false` for now.

Thirdly, I tried to enable versioning by using this:
```
VersioningConfiguration config = new VersioningConfiguration(VersioningConfiguration.Status.ENABLED, false);
minioClient.setBucketVersioning(SetBucketVersioningArgs.builder().bucket(bucketName).config(config).build());
```
But, I get the following error:
```
io.minio.errors.ErrorResponseException: A header you provided implies functionality that is not implemented
	at io.minio.S3Base.execute(S3Base.java:645)
	at io.minio.S3Base.execute(S3Base.java:440)
	at io.minio.S3Base.executePut(S3Base.java:772)
	at io.minio.MinioClient.setBucketVersioning(MinioClient.java:1236)
```

Tha same error appears, if I set the "mfaDelete" argument to "true".

**Comment by balamurugana** [comment]
This means your S3 server/service does not support bucket versioning. You would need to consult the server/service.

Please go through java docs and respective S3 specifications for complete understanding of APIs.

**Comment by ravindk89** [comment]
> Refer https://github.com/minio/minio-java/blob/master/docs/API.md#setBucketVersioning and reopen the issue with error you are getting.
> 
> @harshavardhana @ravindk89 https://docs.min.io/docs/minio-bucket-versioning-guide.html needs a fix.

Thanks for the heads up Bala. Will fix, though not sure if our gluegun builder is working.
