### ISSUE TITLE
 org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed

### ISSUE THREAD

**Issue by a1ekseev** [minio/minio-java#1295]
I'm trying to run a test on GitLab CI, but have run into a problem.
```
    org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed
    	at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source)
    	at io.minio.admin.Crypto.decrypt(Crypto.java:189)
    	at io.minio.admin.MinioAdminClient.listUsers(MinioAdminClient.java:242)
```
So far it has not been possible to reproduce the problem locally.
Do you have any thoughts?

**Comment by balamurugana** [comment]
Seems like a network issue. Refer https://github.com/bcgit/bc-java/issues/1019

**Comment by pbrw** [comment]
This is possibly the same issue as in Python SDK https://github.com/minio/minio-py/issues/1343

**Comment by rafiulahad** [comment]
I m getting the same error using minio Java admin client. The server is running on my MacBook Pro with Apple M3 max chip running Sequoia 15.0.1. Tried everything I find on the issue but still getting the error in the call to listUsers() in the following code (calls to other methods in the API works)
    public boolean userExists(String userName) {
        Map<String,UserInfo> userInfoMap;
        try {
            userInfoMap =  minioAdminClient.listUsers();
            if(userInfoMap == null || userInfoMap.isEmpty()) return false;
            else return true;
        } catch (NoSuchAlgorithmException | InvalidKeyException | IOException | InvalidCipherTextException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by rafiulahad** [comment]
I am having the same error with minio Java admin client. The server is running on my MacBook Pro with Apple M3 max chip on MacOS Sequoia 15.0.1. The call to listUsers() in the following code returns the error org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed'
All other method calls are okay.
    public boolean userExists(String userName) {
        Map<String,UserInfo> userInfoMap;
        try {
            userInfoMap =  minioAdminClient.listUsers();
            return userInfoMap != null && userInfoMap.get(userName) != null;
        } catch (NoSuchAlgorithmException | InvalidKeyException | IOException | InvalidCipherTextException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by balamurugana** [comment]
I am able to reproduce the bug with current `minio-java` code.

**Comment by rafiulahad** [comment]
Also, In my opinion, UserInfo getUserInfo(String accessKey) should not throw an error when the user does not exist. It should return null.

**Comment by balamurugana** [comment]
> @balamurugana here's a clue, user reporting that changing the MinIO build architecture from ARM to x86 fixes the problem, in this discussion here: [minio/minio#20658](https://github.com/minio/minio/discussions/20658)

@marktheunissen There is a different issue I found in my local testing.
