### ISSUE TITLE
Does Minio Java Client auto prefix when interacting with S3?

### ISSUE THREAD

**Issue by dawickizer** [minio/minio-java#1303]
Hello,

I was told to create an issue here based off of this discussion I started: https://github.com/minio/minio/discussions/14343

Connecting to S3/Minio and can confirm this connection is working for both. We can interact with our S3 bucket/Minio via java:
```
 public MinioClient buildClient(
      String endpoint, String region, String accessKey, String secretKey) {
    minioClient =
        MinioClient.builder()
            .endpoint(endpoint)
            .region(region)
            .credentials(accessKey, secretKey)
            .build();
    return minioClient;
  }
```
But we are having an issue when connecting to Minio locally vs S3 in our DEV environment when it comes to some CRUD like operations. For example, this code is successfully working for me when interacting with Minio being served on localhost:9001
```
public void uploadFile(String objectName, MultipartFile file) throws IOException, NoSuchAlgorithmException, InvalidKeyException, MinioException {
    minioClient.putObject(
        PutObjectArgs.builder()
        .bucket(bucketName)
        .object(objectName)
        .stream(file.getInputStream(), file.getSize(), -1)
        .contentType(file.getContentType())
        .build());
  }
```
For example if `bucketName` is `my-bucket` and `objectName` is `my/path/to/file.jpg` and i run the above code...I can navigate to Minio and see that an object has been posted in bucket `my-bucket` with a path of `my/path/to/file.jpg`

However, when we run this code against our DEV environment its connecting to an actual S3 bucket from AWS, and this same exact code will show that a path of `my-bucket/my/path/to/file.jpg` is being created inside of `my-bucket`. So it ends up looking like `my-bucket/my-bucket/my/path/to/file.jpg`. It seems it is automatically adding an extra `my-bucket`. I have debugged everything to confirm that the `objectName` and `bucketName` are as expected in our code so its not our code accidentally adding an extra `my-bucket`.

Not sure if I am doing something wrong, if this is a Minio bug, or if this is an AWS bug, or perhaps a fundamental difference in how AWS stores files vs how Minio stores files

**Comment by harshavardhana** [comment]
> public MinioClient buildClient(
>       String endpoint, String region, String accessKey, String secretKey) {
>     minioClient =
>         MinioClient.builder()
>             .endpoint(endpoint)
>             .region(region)
>             .credentials(accessKey, secretKey)
>             .build();
>     return minioClient;
>   }

what is the input for the `endpoint` here? @dawickizer

**Comment by harshavardhana** [comment]
> I have renamed the endpoint for security reasons but it looks like: `https://my-bucket-s3.s3-our-region-1.amazonaws.com`

you should only add `s3-our-region-1.amazonaws.com` not `my-bucket-s3` as part of the constructor itself.

**Comment by dawickizer** [comment]
Ok that fixed the problem. Thank you! I think we thought the endpoint was supposed to include the bucket name itself, but that was a wrong assumption on our end.
