### ISSUE TITLE
How to get temporary credentials for front-end（app or js）

### ISSUE THREAD

**Issue by liu-xinhui** [minio/minio-java#1307]
if I save accessKey and secretKey in front-end，its not secure。
So I want get temporary credentials for front-end。

I dont know its the right way，or did you have best way。

**Comment by balamurugana** [comment]
Irrelevant to `minio-java`

**Comment by liu-xinhui** [comment]
@balamurugana I think the java sdk should provide the way to get temporary credentials and give the example。

**Comment by balamurugana** [comment]
Refer [Credentials javadoc](https://minio-java.min.io/io/minio/credentials/package-summary.html) and refer [examples](https://github.com/minio/minio-java/tree/master/examples)
