### ISSUE TITLE
Problem when installing the SDK with gradle

### ISSUE THREAD

**Issue by Unaimend** [minio/minio-java#1312]
Good evening I have a slight problem with installing the SDK on my machine, maybe you are able to help me.
It seems to be related to the java module system introduced in Java 9

I added the SDK to my Gradle file like this.
![image](https://user-images.githubusercontent.com/7808379/158867568-0a7f7037-85de-4b50-bcfc-fc0d2e224701.png)
And then added minio to the module-info.java
![image](https://user-images.githubusercontent.com/7808379/158867718-823fdd4a-70f0-4027-b999-25582c46d1b7.png)

Which results in this error 
```
> Task :HelloApplication.main() FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module minio not found, required by com.medinfo.highmed
```

Thank you for your help
Thomas Dost

**Comment by Unaimend** [comment]
I tried it with maven to day and everything worked fine, I will set up a clean gradle project later to see if this also works fine. I assume I must have screwed up sth. in my project settings

**Comment by harshavardhana** [comment]
> I tried it with maven to day and everything worked fine, I will set up a clean gradle project later to see if this also works fine. I assume I must have screwed up sth. in my project settings

Closing @Unaimend
