### ISSUE TITLE
Check if object exists

### ISSUE THREAD

**Issue by padmalcom** [minio/minio-java#1317]
Hi, first of all thanks for you effort and this great library.

I read two posts about checking if an object exists in minio:
- https://github.com/minio/minio-java/issues/799
- https://github.com/minio/minio-java/issues/639

Both seem a bit outdated because the api has changed. I understand that I have to go with _statObject_ but here I struggle. The biggest issue I have is that the class _ErrorCode_ does not seem to exist anymore and I don't know how to check the ErrorReponseException possibly thrown by _statObject_ for the error codes:
- ErrorCode.NO_SUCH_OBJECT
- ErrorCode.NO_SUCH_KEY

Can you give me a hint?

Thank you

**Comment by balamurugana** [comment]
`ErrorResponseException.errorResponse()` returns `ErrorResponse` message documented [here](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html). Handle respective code accordingly.
