### ISSUE TITLE
file name too long ( > 100 bytes)

### ISSUE THREAD

**Issue by wushunqing** [minio/minio-java#1318]
hi，when i use thsi api,minioClient.uploadSnowballObjects,my filename is too long,the TarArchiveOutputStream is error.
": file name '3d/2022-04-02/a45e27e5-1712-4f1a-80c3-5b811d40a7b2/Mat_4920_Dumpleton_Hall_Locomotive_baseColor_.jpg' is too long ( > 100 bytes)
"

It's normal to solve it here

![image](https://user-images.githubusercontent.com/20431475/161368177-26d165c5-cd60-45cf-a74d-ebb24a788a23.png)

tarOutputStream.setLongFileMode(TarArchiveOutputStream.LONGFILE_GNU);

**Comment by balamurugana** [comment]
@wushunqing Please try this fix https://github.com/minio/minio-java/pull/1319

**Comment by wushunqing** [comment]
When will it be released?
