### ISSUE TITLE
Can I use the admin apis right now?

### ISSUE THREAD

**Issue by jaggerwang** [minio/minio-java#1320]
I see there is an adminapi directory in the repository, and it supplys some admin apis in class `MinioAdminClient`, including user and policy management. But it lacks some important admin apis, like change user password, set bucket quota, etc. Is there any plan to supply full admin apis in the future?

**Comment by balamurugana** [comment]
Yes. `MinioAdminClient` is ready for regular usage. If you are expecting some more feature, feel free to send PRs.
