### ISSUE TITLE
s3-fips endpoints aren't supported

### ISSUE THREAD

**Issue by aaronterry73** [minio/minio-java#1329]
Using endpoints like:
`s3-fips.us-gov-west-1.amazonaws.com`
`s3-fips.dualstack.us-gov-west-1.amazonaws.com`
results in the following errors:
> io.minio.errors.ErrorResponseException: Couldn't parse the specified URI	at
> io.minio.MinioClient.execute(MinioClient.java:1135)	at io.minio.MinioClient.execute(MinioClient.java:935)	at
> io.minio.MinioClient.executeHead(MinioClient.java:1204)	at io.minio.MinioClient.bucketExists(MinioClient.java:3592)

Looks like the `MinioAsyncClient.isAwsEndpoint` doesn't detect `s3-fips` as a valid AWS endpoint. I'm not sure what else may be broken as well (maybe the region detecting code).

```
private boolean isAwsEndpoint(String endpoint) {
  return (endpoint.startsWith("s3.") || isAwsAccelerateEndpoint(endpoint))
      && (endpoint.endsWith(".amazonaws.com") || endpoint.endsWith(".amazonaws.com.cn"));
}
``` 

This sounds similar to an issue that was fixed in minio-go a few years back.
[https://github.com/minio/minio-go/issues/1033](https://github.com/minio/minio-go/issues/1033)

Minio Java Version: 7.1.4 (although checked 8.4.0 and it doesn't explicitly support s3-fips endpoints either)

**Comment by balamurugana** [comment]
@aaronterry73 Please try PR https://github.com/minio/minio-java/pull/1334 and let me know whether it fixes the problem.

**Comment by aaronterry73** [comment]
@balamurugana Thanks for putting the PR together. Looking over the changes, everything looks great. I'm unable to test this myself as our application had dependency conflicts with the lastest minio java branch. I was able to find a solution on the 7.1.4 by manually setting the following when constructing my MinioClient:
```scala
  def minioClient(endpoint: String, accessKey: String, secretKey: String, httpClient: Option[OkHttpClient]): MinioClient = {
    val httpUrl = HttpUrl.parse(endpoint)
    val secureHttpUrl = httpUrl.newBuilder().scheme(if (endpoint.startsWith("https://")) "https" else "http").build()

    val builder = MinioClient.builder()
      .endpoint(secureHttpUrl)
      .credentials(accessKey, secretKey)

    if (httpClient.isDefined)
      builder.httpClient(httpClient.get)

    val regionOpt = parseS3Region(endpoint)
    if (regionOpt.isDefined) {
      builder.region(regionOpt.get)
    }

    val client = builder.build()
    if (endpoint.contains("fips")) {
      // This is required for fips endpoints in S3 (puts the bucket in the host url, instead of as a path argument (See MinioClient.buildUrl)
      client.enableVirtualStyleEndpoint()
    }
    client
  }

  def parseS3Region(endpoint: String): Option[String] = {
    val parts: Seq[String] = endpoint.split("\\.").toSeq
    val awsToken = parts.zipWithIndex.find { case (s, i) => s.equalsIgnoreCase("amazonaws") }
    if (awsToken.isDefined) {
      val region = parts(awsToken.get._2 - 1) // previous token is the region
      Some(region)
    } else {
      None
    }
  }
```

The two pieces that I had to manually set for s3-fips to work were
```scala
builder.region(regionOpt.get)
```
and
```
// This is required for fips endpoints in S3 (puts the bucket in the host url, instead of as a path argument (See MinioClient.buildUrl)

client.enableVirtualStyleEndpoint()
```

The AWS [documentation](https://aws.amazon.com/compliance/fips/) calls out the following for fips:
```
Note: These Endpoints can only be used with Virtual Hosted-Style addressing.
For example: https://bucket.s3-fips.us-east-2.amazonaws.com. Visit the [Amazon S3 Documentation page](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html) for more information.
```
I believe it would be prudent to include/validate that users are explicitly using `enableVirtualStyleEndpoint`, otherwise the AWS won't allow requests to go through.
