### ISSUE TITLE
MinIO Java SDK is much slower compared to both `mc` and AWS S3 Java SDK

### ISSUE THREAD

**Issue by arman-yekkehkhani** [minio/minio-java#1332]
I am using Java 8 and trying to upload a 1 Gb file on a local MinIO server. Here is the amount of time it took for each of the following methods:
```
MinIO Java SDK: 17s
AWS Java SDK: 11s
AWS Java SDK(with Transfer Manager): 7s
mc client: 3.5s
```
I wonder what makes MinIO SDK slower and how can I improve the speed.

**Comment by balamurugana** [comment]
How are you trying to upload?

**Comment by arman-yekkehkhani** [comment]
Using MinIO SDK:
```java
minioClient.uploadObject(
        UploadObjectArgs.builder()
        .bucket("test_bucket")
        .object("test")
        .filename("/path_to_some_file")
        .build()
);
```

Using S3 SDK:
```java
TransferManager tm = TransferManagerBuilder.standard()
         .withS3Client(s3Client)
         .build();

Upload upload = tm.upload("test_bucket", "test", file);
upload.waitForCompletion();
```

`mc`:
```bash
./mc cp {file_path} {bucket_path}
```

**Comment by balamurugana** [comment]
Use part size using this [filename](https://minio-java.min.io/io/minio/UploadObjectArgs.Builder.html#filename-java.lang.String-long-] and tweak part size value as per your requirement.

**Comment by arman-yekkehkhani** [comment]
Tried different values: `5Mb, 10Mb, 30Mb, 50Mb, 100Mb, and 1Gb`. Same or even worse performance.

**Comment by balamurugana** [comment]
How was `MinioClient` created? Are you running `mc` and `minio-java` on same machine?

**Comment by arman-yekkehkhani** [comment]
Here is the code:
```java
MinioClient minioClient =
                    MinioClient.builder()
                            .endpoint("http://127.0.0.1:9000")
                            .credentials("minioadmin", "minioadmin")
                            .build();
```
Yes. They are both on the same machine(my local machine).

**Comment by balamurugana** [comment]
As expected, SHA256 and MD5 checksum calculation are slow. Probably I will move away from Java built-in SHA256/MD5 hasher.
