### ISSUE TITLE
Use both sync and async client

### ISSUE THREAD

**Issue by mmadoo** [minio/minio-java#1341]
I want to use both sync and async API with a single HTTP stack.
As MinioClient constructor is private, this is not easily possible.
Is there a specific reason to have a private constructor on this class ? or is it possible to have a the method ` public AsyncClient getAsyncClient()` ?

A workaround could be to use a code like:
```
OkHttpClient httpClient = HttpUtils
				.newDefaultHttpClient(TimeUnit.MINUTES.toMillis(5), TimeUnit.MINUTES.toMillis(5), TimeUnit.MINUTES.toMillis(5));
		this.minioAsyncClient = MinioAsyncClient.builder()
				.endpoint(host)
				.region(region)
				.credentials(accesskey, secretkey)
				.httpClient(httpClient)
				.build();
		this.minioClient = MinioClient.builder()
				.endpoint(host)
				.region(region)
				.credentials(accesskey, secretkey)
				.httpClient(httpClient)
				.build();
```
but it is error prone

**Comment by balamurugana** [comment]
If this is what your requirement, the code shared by you is good to go. If you see a problem with `OkHttpClient`, you would need to check with `okhttp` project.
