### ISSUE TITLE
Some question about SignatureDoesNotMatch with Java sdk

### ISSUE THREAD

**Issue by SpinSi** [minio/minio-java#1342]
start with docker , below is my docker run cmd

   docker run \
     -p 9000:9000 \
     -p 9090:9090 \
     --name minio \
     -v /opt/soft/data/miniodata:/data \
     -v /etc/localtime:/etc/localtime:ro \
     -e "MINIO_ROOT_USER=minioadmin" \
     -e "MINIO_ROOT_PASSWORD=minioadmin" \
     -e "MINIO_SERVER_URL=http://192.160.90.160:9000" \
     minio/minio server /data --console-address ":9090"

1. use minio with java sdk  putObject 

  MinioClient  minioClient =
                MinioClient.builder()
                        .endpoint(endpoint)
                        .credentials("minioadmin", "minioadmin")
                        .build();
minioClient.putObject(
                    PutObjectArgs.builder()
                            .bucket(bucketName)
                            .object(fileName)
                            .stream(fileInputStream, fileInputStream.available(), -1)
                            .contentType(fileType)
                            .build());
result Exception
error occurred
ErrorResponse(code = SignatureDoesNotMatch, message = The request signature we calculated does not match the signature you provided. Check your key and signing method., like below picture
![image](https://user-images.githubusercontent.com/12402442/175198585-5dd901f3-4e9b-4f71-bff5-832e2477514d.png)

2. use minio with java sdk  getPresignedObjectUrl 

resource /bucketname/法大大彩色logo.png is existed
![image](https://user-images.githubusercontent.com/12402442/175197740-6da1212c-7633-4e3e-9c71-000ab405fcdc.png)

String url =
                minioClient.getPresignedObjectUrl(
                        GetPresignedObjectUrlArgs.builder()
                                .method(Method.PUT)
                                .bucket("bucketname")
                                .object("法大大彩色logo.png")
                                .expiry(2, TimeUnit.HOURS)
                                .build());
but open the url with browser 
get error below .
![image](https://user-images.githubusercontent.com/12402442/175197889-2ef26ff4-7938-4952-b76d-718dc33d983d.png)

java sdk like below 
![image](https://user-images.githubusercontent.com/12402442/175198853-cffe16dd-5b40-4c35-9238-e51cab1beab3.png)

and minio version
minio --version
minio version RELEASE.2022-06-20T23-13-45Z (commit-id=b3ebc69034bff982ca2c1a6ca43afd20838e99d5)
Runtime: go1.18.3 linux/arm64
Copyright (c) 2015-2022 MinIO, Inc.
Licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

uname -a
Linux e7a559217913 5.10.76-linuxkit minio/minio#1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

I want to know the reason about SignatureDoesNotMatch  and how to resolve it .
Who can help me ? ths !!

**Comment by vadmeste** [comment]
@SpinSi you are not using a load balancer, right ?

Can you try with a simple file name such as 'testfile' ?

**Comment by balamurugana** [comment]
Please enable `traceOn()` and share the output.
