### ISSUE TITLE
Method execution takes a long time

### ISSUE THREAD

**Issue by SK-XFY** [minio/minio-java#1347]
### A Mian method，use openJDK 17.0.1

![image](https://user-images.githubusercontent.com/16585995/178176411-2ec65d7e-82f8-4fd1-bc97-4d31fee819c4.png)

### After all the code is executed, it takes 2 minutes for the JVM to shut down. I use version 7.0. I don't mention this
![image](https://user-images.githubusercontent.com/16585995/178175754-70462b71-0810-4872-8d8a-dff688acede0.png)

**Comment by SK-XFY** [comment]
The same is true with jdk8. The JVM cannot exit immediately after the program is executed

**Comment by SK-XFY** [comment]
### It seems that okhttp has been waiting for the thread
![image](https://user-images.githubusercontent.com/16585995/178182251-cfd42d52-9849-4f4d-bce1-7efa02192e10.png)

**Comment by alonso-estevam** [comment]
How did you solve this, issue?
