### ISSUE TITLE
minio 8.4.3 Simple-xml-safe-2.7.1 Vulnerability in jar

### ISSUE THREAD

**Issue by xmt1139057136** [minio/minio-java#1348]
minio 8.4.3 Simple-xml-safe-2.7.1 Vulnerability in jar

Vulnerability security scan failed

Our foreign teams have high security requirements. Can the vulnerability in simple-xml-safe-2.7.1 be repaired

https://mvnrepository.com/artifact/com.carrotsearch.thirdparty/simple-xml-safe/2.7.1

**Comment by balamurugana** [comment]
What vulnerability issue are you facing?
