### ISSUE TITLE
Missing Java Listener

### ISSUE THREAD

**Issue by AlexandreBarde** [minio/minio-java#1349]
Official doc mentions the following listeners

![image](https://user-images.githubusercontent.com/19241664/179518916-81d21160-830e-4cd4-bfc1-a792fb2767b6.png)

They are implemented in Goland, but for java, nothing.
Is there a reason for that ?

Golang : https://docs.min.io/docs/golang-client-api-reference.html#ListenNotification

**Comment by balamurugana** [comment]
Feel free to send a PR
