### ISSUE TITLE
create service account

### ISSUE THREAD

**Issue by hanhfgia** [minio/minio-java#1354]
Hi,
Any function/api to "create service account" in minio-java? guide to create?

thanks advance!

**Comment by balamurugana** [comment]
How is this related to S3 APIs?

**Comment by hanhfgia** [comment]
How do you know this relate to S3 API?

See: minio-java/adminapi, there are some functions, look at: 
[    ADD_USER("add-user"),](https://github.com/minio/minio-java/blob/65f5ffeb2c25ef39cbcc49e71b8f3221c609ac15/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L65)

Q: why did not service-account functions support?, see: https://github.com/minio/minio/blob/2393a13f86ab9f28f1fa4b692ef1e0a8a7a92164/cmd/admin-router.go#L134

I think that some basic functions related service-account should be supported.

thanks,

**Comment by balamurugana** [comment]
It's not yet supported. Feel free to send a PR.
