### ISSUE TITLE
MinioAdminClient.addUser do not set policy or membersOf

### ISSUE THREAD

**Issue by mmadoo** [minio/minio-java#1355]
When I use Java MinioAdminClient 8.4.3 with minio server (using the docker image quay.io/minio/minio:RELEASE.2022-08-08T18-34-09Z) and do 
`adminClient.addUser(user, Status.ENABLED, accessKey, policyName, List.of("myGroup"));`
the new user does not have any policy set and does not belong to any groups.

## Possible Solution
I have been able to set policy using `adminClient.setPolicy(user, false, policyName);`  but I found no way to set the groups.

**Comment by balamurugana** [comment]
Please look into https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L417
