### ISSUE TITLE
PutObject sometimes fails to upload files

### ISSUE THREAD

**Issue by 440981** [minio/minio-java#1356]
The information returned is
`ErrorResponse(code = InvalidRequest, message = Invalid Request (request has multiple authentication types, please use one), bucketName = null, objectName = null, resource = /njxf//app/im/VID_20220820_0959441560808499619823616.mp4, requestId = null, hostId = 4b437249-dd58-45c8-b976-390d44d07fee)`
The minioClient creation works fine,It's an occasional problem

**Comment by balamurugana** [comment]
You are using wrong authentication credentials or credential providers.

**Comment by 440981** [comment]
> You are using wrong authentication credentials or credential providers.
But uploading small files is no problem, only uploading large files will happen by accident

**Comment by 440981** [comment]
But uploading small files is no problem, only uploading large files will happen by accident

**Comment by liangyuanpeng** [comment]
@440981  Provide some code to reproduce it would be great.

**Comment by song-cc-rock** [comment]
I also encountered the same problem, small files are Ok, but large files over 5M will report this exception.

**Comment by 440981** [comment]
> I also encountered the same problem, small files are Ok, but large files over 5M will report this exception.

Check whether your request header is multipart/form-data. If so, set it to null before uploading
