### ISSUE TITLE
7.1.3 tag missing

### ISSUE THREAD

**Issue by CChengjie** [minio/minio-java#1359]
We found that version 7.1.3 was released in Maven, but there was no corresponding tag in github

1）What is the reason for tag's absence?（Find relevant release commit message for 7.1.3）

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?

**['9337c053dd360039ca7e6f5a9857d6d5e79a8e5e', 'a455c11bbb19ee47780ede8be5244daa7640c229', 'f5e60e1371e546a51ddd9678023b8abfe1182dec', 'c2577614af721ecb4b834e5d069a490840884245']**

This question is very important to our research. Thank you for your time!

**Comment by harshavardhana** [comment]
Let's check

**Comment by harshavardhana** [comment]
Okay, that must be quite some time ago, we are not going to retroactively fix it now since we have moved on to v8.x.x versions.

**Comment by harshavardhana** [comment]
> * c、Forgot to tag

^^ this.

**Comment by CChengjie** [comment]
> > * c、Forgot to tag
> 
> ^^ this.

Thank you~
