### ISSUE TITLE
PutObject sometimes fails to upload files

### ISSUE THREAD

**Issue by 440981** [minio/minio-java#1360]
The information returned is
ErrorResponse(code = InvalidRequest, message = Invalid Request (request has multiple authentication types, please use one), bucketName = null, objectName = null, resource = /njxf//app/im/VID_20220820_0959441560808499619823616.mp4, requestId = null, hostId = 4b437249-dd58-45c8-b976-390d44d07fee)
The minioClient creation works fine,It's an occasional problem
But uploading small files is no problem, only uploading large files will happen by accident
It can't be about the credentials

**Comment by 440981** [comment]
`request={method=POST, url=http://192.168.117.198:9000/njxf//app/im/VID_20220820_1157041560838007844503552.mp4?uploads=, headers=Content-Type: multipart/form-data;charset=utf-8
Host: 192.168.117.198:9000
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.3.3
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20220820T035554Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20220820/china/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=Accept-Ranges: bytes
Content-Length: 328
Content-Type: application/xml
Server: MinIO
Vary: Origin
Date: Sat, 20 Aug 2022 03:57:16 GMT
}`

**Comment by klauspost** [comment]
On MinIO this triggers both `isRequestSignatureV4` and `isRequestPostPolicySignatureV4`. 

AFAICT the auth fields should be in the form and not in the header when using multipart/formdata POST.

**Comment by balamurugana** [comment]
It looks like hand crafted request and using low level methods to do the execution by extending `MinioClient`. @440981 share your code along with trace out by enabling `traceOn()`.
