### ISSUE TITLE
Upload folder contents in a loop

### ISSUE THREAD

**Issue by hjx44599** [minio/minio-java#1365]
When I upload all the files in the folder in a loop using the methods in PutObjectProgressBar, I output 100% progress on the console after the last file has been uploaded, and I cannot release resources，and No errors are thrown.

`public static void uploadMinio(File file, String fileId) throws Exception {

        MinioClient minioClient = MinioUtil.initMinio();

        if (minioClient.bucketExists(BucketExistsArgs.builder().bucket(MinioUtil.getBucketName()).build())) {
        } else {
            minioClient.makeBucket(MakeBucketArgs.builder().bucket(MinioUtil.getBucketName()).build());
        }

        if (file.isFile()) {
            String filePath = file.getAbsolutePath();
            filePath = FilenameUtils.normalize(filePath, true);
            filePath = filePath.replaceFirst(FilenameUtils.getPrefix(filePath), "");

            try {
                StatObjectResponse stat =
                        minioClient.statObject(
                                StatObjectArgs.builder()
                                        .bucket(MinioUtil.getBucketName())
                                        .object(filePath)
                                        .build());
                if (stat.size() == file.length()) {
                    log.info(file.getName() + " exist");
                    return;
                } else if (stat.size() > file.length()) {
                    minioClient.removeObject(RemoveObjectArgs.builder().bucket(MinioUtil.getBucketName()).object(filePath).build());
                }
            } catch (Exception e) {
                log.info("file state： " + e.getMessage());
            }

            FileInputStream stream = null;
            ProgressStream in = null;
            InputStream is = null;
            try {
                stream = new FileInputStream(file);
                in = new ProgressStream(fileId + "___" + file.getName(), ProgressBarStyle.ASCII, file.length(), stream);
                is = new BufferedInputStream(in);
                minioClient.putObject(
                        PutObjectArgs.builder().bucket(MinioUtil.getBucketName()).object(filePath).stream(
                                        is, file.length(), -1)
                                .build());
            } finally {
                if (is != null) {
                    try {
                        is.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }

        } else {
            File[] files = file.listFiles();
            if (files == null || files.length == 0) {
                String filePath = file.getAbsolutePath();
                filePath = FilenameUtils.normalize(filePath, true);
                filePath = filePath.replace(FilenameUtils.getPrefix(filePath), "");
                minioClient.putObject(
                        PutObjectArgs.builder().bucket(MinioUtil.getBucketName()).object(filePath + "/").stream(
                                        new ByteArrayInputStream(new byte[]{}), 0, -1)
                                .build());
            } else {
                for (File file1 : files) {
                    uploadMinio(file1,fileId);
                }

            }
        }
    }`

**Comment by balamurugana** [comment]
`examples/ProgressStream.java` is an example code or guideline how progress can be achieved. You could implement your own progress by understand the logic.
