### ISSUE TITLE
Problems with fetching added metadata to a file

### ISSUE THREAD

**Issue by kad-willej** [minio/minio-java#1368]
Problem:

When I add metadata to a file, it will correctly store the metadata but incorrectly retrieve the metadata.

Fetch by:

```java
    minioClient.listObjects(
                    ListObjectsArgs.builder()
                            .bucket(properties.getBucket())
                            .recursive(true)
                            .prefix(prefixUrl)
                            .includeUserMetadata(true)
                            .build()
```

Result from returned Item object:
```
userMetadata = {Metadata@10820} 
 map = {Collections$UnmodifiableMap@10823}  size = 3
  "Value" -> "A4"
  "Items" -> null
  "Key" -> "X-Amz-Meta-Pdftype"
```
The key should be "X-Amz-Meta-Pdftype" and not "Key", and result should be "A4". This seems malformed, I'm not sure if this is caused by the SDK, since it seem to happen with the upgrade of Minio server.

Tried versions (with Docker):
minio.RELEASE.2022-07-04T21-02-54Z <- Works
minio.RELEASE.2022-08-26T19-53-15Z <- Fails

So even though the problem appears with the change of the Minio server instead of the SDK, I upload the issue here as well since it happens when using the SDK.

**Comment by balamurugana** [comment]
As you have mentioned, if server upgrade makes the failure, its nothing to do with minio-java
