### ISSUE TITLE
REOPEN - Minio disable SSL with java client not working !

### ISSUE THREAD

**Issue by vaibhavpatil123** [minio/minio-java#1370]
## ISSUE 
Minio disable SSL with java client not working !

## Expected Behavior
Minio disable SSL with java client should work with disable SSL flag
## Current Behavior
Minio disable SSL with java client not working with disable SSL flag

## Steps to Reproduce (for bugs)

Use maven java client 

```


        String serviceUrl = "minio9.s3test.sdsdsd.com";
        String accessKey = "dfgdfgdg";

        String secretKey = "sdfsdfs+sdfsdfsd";

        String bucketName = "mymb2";
        MinioClient minioClient  = MinioClient.builder().endpoint(serviceUrl,9000,false).credentials(accessKey, secretKey).build();
        try {
            ///System.out.println(minioClient.listBuckets());
            minioClient.setTimeout(new Long("121212"),new Long("121212"),new Long("121212"));
            minioClient.makeBucket(
                    MakeBucketArgs.builder()
                            .bucket("my-bucketname")
                            .region("us-east-1")
                            .build());
        } catch ( Exception exception){
            System.out.print(exception.getMessage());
        }
```

Getting socket timeout error 

Sep 27, 2022 7:14:33 PM okhttp3.internal.platform.Platform log
INFO: Callback failure for call to http://minio9.s3test.sdfsdf.com:9000/...
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
## Context

<dependency>
      <groupId>io.minio</groupId>
      <artifactId>minio</artifactId>
      <version>8.4.5</version>
    </dependency>

**Comment by balamurugana** [comment]
If the server is not responding, nothing can be done at client side.

**Comment by vaibhavpatil123** [comment]
Hi colleagues we have cloud setup for miniO, using browser console I am able to create bucket and even using POSTMAN collection I can access APIS
There is no point of connection issue , I request you can you setup locally and check above point , I think thier an issue

**Comment by vaibhavpatil123** [comment]
+ Also just some time I have used link https://hub.docker.com/r/minio/minio/ to check locally and setup it on WINDOWS to verify it locally 
getting timeout even for login 


![minio](https://user-images.githubusercontent.com/9848325/192576735-95e2b011-c344-4ffe-a8f6-8432c389bf59.gif)

**Comment by vaibhavpatil123** [comment]
I have locally setup instance now using docker now 

_https://blog.knoldus.com/how-to-run-minio-as-a-docker-container/?subscribe=many_pending_subs#subscribe-blog-blog_subscription-4_

```
import io.minio.BucketExistsArgs
import io.minio.MakeBucketArgs
import io.minio.MinioClient

static void main(String[] args) {
  println "Hello world!"
    // Create a minioClient with the MinIO server playground, its access key and secret key.
    MinioClient minioClient =
            MinioClient.builder()
                    .endpoint("http://172.17.0.2:9000")
                    .credentials("ivuRYs6HLwfGafk8", "zuf+Km2VIWS4OP3iAomCZ3CYjn7wtgHF0BUs")
                    .build();

    // Make 'asiatrip' bucket if not exist.
    boolean found =
            minioClient.bucketExists(BucketExistsArgs.builder().bucket("asiatrip").build());
    if (!found) {
      // Make a new bucket called 'asiatrip'.
      minioClient.makeBucket(MakeBucketArgs.builder().bucket("asiatrip").build());
    } else {
      System.out.println("Bucket 'asiatrip' already exists.");
    }
}



```

ERROR 

Caught: java.net.ConnectException: Failed to connect to /172.17.0.2:9000
java.net.ConnectException: Failed to connect to /172.17.0.2:9000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

**Comment by vaibhavpatil123** [comment]
Refer example here if required https://github.com/minio/minio-java

**Comment by vaibhavpatil123** [comment]
import io.minio.BucketExistsArgs;
import io.minio.MakeBucketArgs;
import io.minio.MinioClient;
import io.minio.errors.*;

import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

public class TestClientMinio {
    public static void main(String[] args) throws ServerException, InsufficientDataException, ErrorResponseException, IOException, NoSuchAlgorithmException, InvalidKeyException, InvalidResponseException, XmlParserException, InternalException {
        // Create a minioClient with the MinIO server playground, its access key and secret key.
        MinioClient minioClient =
                MinioClient.builder().endpoint("http://172.17.0.2",9000,false)
                .credentials("ivuRYs6HLwfGafk8", "zuf+Km2VIWS4OP3iAomCZ3CYjn7wtgHF0BUs")
                .build();

        // Make 'asiatrip' bucket if not exist.
        boolean found =
                minioClient.bucketExists(BucketExistsArgs.builder().bucket("asiatrip").build());
        if (!found) {
            // Make a new bucket called 'asiatrip'.
            minioClient.makeBucket(MakeBucketArgs.builder().bucket("asiatrip").build());
        } else {
            System.out.println("Bucket 'asiatrip' already exists.");
        }
    }
}

**Comment by vaibhavpatil123** [comment]
SAME ERROR !!!

**Comment by harshavardhana** [comment]
@vaibhavpatil123 where are you running your java code from ? And is your docker on macOS?

**Comment by vaibhavpatil123** [comment]
@all  thanks for quickly responses 


correct solution is to set timeout on connection finally iI am able to fix issue below is updated code :)


import io.minio.MinioClient;
import io.minio.errors.*;

import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

public class TestClientMinio {
    public static void main(String[] args) throws ServerException, InsufficientDataException, ErrorResponseException, IOException, NoSuchAlgorithmException, InvalidKeyException, InvalidResponseException, XmlParserException, InternalException {
        // Create a minioClient with the MinIO server playground, its access key and secret key.
        MinioClient minioClient =
                MinioClient.builder().endpoint("127.0.0.1",9000,false)
                .credentials("8NdCy0t58hg7qfqb", "NnaOWeoRLxs1rPoSDiuNYrYEZrUZQj2B")
                .build();
        **minioClient.setTimeout(121l,1212l,12212l);**
        // Make 'asiatrip' bucket if not exist.
        minioClient.makeBucket(MakeBucketArgs.builder().bucket("asiatrip").build());
    }
}
