### ISSUE TITLE
How to create a MinioClient with credentials inclusive of SessionToken

### ISSUE THREAD

**Issue by rsivakanth** [minio/minio-java#1373]
Hello,
All the examples of creating MinioClient using builder are just with credentials(accessKey, secretKey). Is there not a way to build the client with credentials(accessKey, secretKey, sessionToken)? Although I see the Credentials class is having the constructor with all the above. But the MinioClient builder neither has a credentials() method that takes sessionToken attribute nor a Credentials object :

public Credentials(
      @Nonnull @Element(name = "AccessKeyId") String accessKey,
      @Nonnull @Element(name = "SecretAccessKey") String secretKey,
      @Nullable @Element(name = "SessionToken") String sessionToken,
      @Nullable @Element(name = "Expiration") ResponseDate expiration) {
    this.accessKey = Objects.requireNonNull(accessKey, "AccessKey must not be null");
    this.secretKey = Objects.requireNonNull(secretKey, "SecretKey must not be null");
    if (accessKey.isEmpty() || secretKey.isEmpty()) {
      throw new IllegalArgumentException("AccessKey and SecretKey must not be empty");
    }
    **this.sessionToken = sessionToken**;
    this.expiration = expiration;
  }
  
Could you please clarify or direct me to an example that uses sessionToken to get MinioClient?
Thanks,
Sivakanth.

**Comment by balamurugana** [comment]
Refer various credential providers [here](https://github.com/minio/minio-java/tree/master/api/src/main/java/io/minio/credentials) and what are trying to achieve here?

**Comment by rsivakanth** [comment]
Ok, thanks for the reference @balamurugana. Will have a look and get back if still having doubts.
