### ISSUE TITLE
MultipartUpload Response

### ISSUE THREAD

**Issue by lnnwvr** [minio/minio-java#1376]
Multipart upload (putObject) seems not to handle latest server response including checksums correctly. I think fields are missing in CompleteMultipartUploadOutput.java

**Comment by balamurugana** [comment]
Feel free to send a PR

**Comment by klauspost** [comment]
@balamurugana It should not fail on unknown fields. These will likely be returned from S3 as well.

See "Response Syntax": https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

**Comment by harshavardhana** [comment]
CheckSum is optional @balamurugana it may be something to add and update the library. 

Working on native support for this may need time.

**Comment by mmadoo** [comment]
Fixed in  #1377
