### ISSUE TITLE
Provide client metrics

### ISSUE THREAD

**Issue by jtama** [minio/minio-java#1380]
As of now, the only way I found to get client metrics is to recreate the OkHttpClient from ground using `io.micrometer.core.instrument.binder.okhttp3.OkHttpMetricsEventListener` which isn't great as the default HttpClient as lots of configuration. 

It would be great to either be able to register the Listener without rebuild the entire client, or provide an SPI that we could then implement.

**Comment by balamurugana** [comment]
You could use your own custom http client by https://minio-java.min.io/io/minio/MinioAsyncClient.Builder.html#httpClient-okhttp3.OkHttpClient-

**Comment by jtama** [comment]
yes this is what I do. A simple `listener` could be a first step, but it doesn't exists, so I have to kind of redo this : https://github.com/minio/minio-java/blob/328c49d95231e20d4453efd60e6b5d8c6b09eaa5/api/src/main/java/io/minio/http/HttpUtils.java#L178
