### ISSUE TITLE
> hello, getPresignedPostFormData: This method sets how to test the upload type. My test does not work

### ISSUE THREAD

**Issue by sujiangtao123** [minio/minio-java#1383]
> hello, getPresignedPostFormData: This method sets how to test the upload type. My test does not work

https://github.com/minio/minio-java/blob/master/examples/GetPresignedPostFormData.java

_Originally posted by @balamurugana in https://github.com/minio/minio-java/issues/1048#issuecomment-1320884882_
      
### **policy.addStartsWithCondition("Content-Type", "image/");**
  My backend java generates POST signatures，Use Postman to directly transfer files to the mini server according to form-data simulation，want to limit the type of files，But this line of code doesn't seem to limit the file type，such as: Added content type, the type is image/png，The jpg file can also be uploaded successfully

**Comment by balamurugana** [comment]
Open the issue with the server you are using. Nothing can be done at client side.

**Comment by sujiangtao123** [comment]
> Open the issue with the server you are using. Nothing can be done at client side.
**### policy.addStartsWithCondition("Content-Type", "image/");**
Thank the author very much，But I want to know what this line of code means，I think your comment means that you can only transfer pictures after setting？
// Add condition that 'Content-Type' starts with 'image/'.

**Comment by balamurugana** [comment]
Refer https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

**Comment by sujiangtao123** [comment]
> Thank the author very much

see light suddenly
