### ISSUE TITLE
How quickly we can delete non Empty large bucket?

### ISSUE THREAD

**Issue by AjayShivanagol** [minio/minio-java#1384]
Using recursive object delete for the large bucket is this a feasible solution?
or is there any alternative?

and also wanted to understand how much time takes to delete 1GB to 30GB of data delete.

**Comment by balamurugana** [comment]
[removeObjects()](https://minio-java.min.io/io/minio/MinioAsyncClient.html#removeObjects-io.minio.RemoveObjectsArgs-) is meant for that. There are many variables to guess time for completion.

**Comment by AjayShivanagol** [comment]
@balamurugana Thanks for the input..
since I am new to this Minio world your help will be very much appreciated.

Time is taken for the completion of the delegation of all the objects how do we determine this?
removeObjects() as we are integrating this as API I wanted to understand the timeout for this for the Large bucket.
removing large Objects also depends upon the system configuration as well ?

Thanks in Advance

**Comment by balamurugana** [comment]
You would need to consider below
1. number of objects on the bucket
2. your network speed
3. your minio inter-node speed
4. your disk drive speed
5. Overall your machine performance

Go through https://docs.min.io
