### ISSUE TITLE
Unable to satisfy @org.simpleframework.xml.Element when call listParts

### ISSUE THREAD

**Issue by lentitude2tk** [minio/minio-java#1391]
when extends the MinioClient and call listParts，throws error

Unable to satisfy @org.simpleframework.xml.Element(name=Initiator, data=false, type=void, required=true) on field 'initiator' private io.minio.messages.Initiator io.minio.messages.ListPartsResult.initiator for class io.minio.messages.ListPartsResult at line 1

![image](https://user-images.githubusercontent.com/108672767/206461659-da05f795-a0e4-4c1b-98cd-13fa16910497.png)

need to fix the field initiator to "require false"
![image](https://user-images.githubusercontent.com/108672767/206461929-d2aac0fc-3a63-4507-8655-dc2da3688499.png)

**Comment by lentitude2tk** [comment]
No, this server uses minIO to initiate a request to gcp. This server is google cloud storage. I understand that minIO is adapted to gcp?

As a user, I cannot modify the return of the gcp server

**Comment by lentitude2tk** [comment]
I found the official gcp document, and the return indicated in it does not have this field: https://cloud.google.com/storage/docs/xml-api/get-object-multipart

![image](https://user-images.githubusercontent.com/108672767/206489582-2193da9f-63ae-45a6-8e00-e7da43b0252e.png)

**Comment by balamurugana** [comment]
`minio-java` is meant for S3 compatible object storage servers like MinIO/AWS S3.  Google Cloud Storage is not S3 compatible

**Comment by lentitude2tk** [comment]
First, I checked the listParts interface of aws, and the return field of the xml api interface does not include this field Initiator @balamurugana :
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html

![image](https://user-images.githubusercontent.com/108672767/206492345-a120f3ee-8f0b-4d95-9757-916ea0499fc4.png)

**Comment by lentitude2tk** [comment]
Secondly, I used minIO, which is compatible with Google Cloud Storage, because the access analysis is done through xml-api. Of course, we can first look at the problem of this interface for aws

**Comment by arvkonstantin** [comment]
Same with SeaweedFS
