### ISSUE TITLE
listObjectsV2Async / listObjectVersionsAsync are protected

### ISSUE THREAD

**Issue by ahjohannessen** [minio/minio-java#1394]
I wondered if it was possible to make `listObjectsV2Async` public or make a variant of `listObjects` that is non-blocking?

The same deal with `listObjectVersionsAsync`, it is protected and it is not used by the `MinioAsyncClient`. There is only a blocking one, `listObjectVersions` on `S3Base`. The docs state `Deprecated: This method is no longer supported. Use listObjectVersionsAsync.`

**Comment by balamurugana** [comment]
As [listObjects()](https://minio-java.min.io/io/minio/MinioAsyncClient.html#listObjects-io.minio.ListObjectsArgs-) is lazy and it works for most of the cases to get all objects iteratively. If you are looking for specific to low level APIs, you would need to inherit `MinioAsyncClient`  for your custom requirements.

**Comment by ahjohannessen** [comment]
That is what I went with, extended the MinioAsyncClient and defined two async methods that just delegate to `S3Base`.
