### ISSUE TITLE
How to create user policy using java SDK ?

### ISSUE THREAD

**Issue by gredwhite** [minio/minio-java#1395]
I tried to create IAM policy using amazon s3 sdk but I was answered that it is not implemented by purpose
https://stackoverflow.com/a/74662111/2674303

So I tried to use mino java sdk

https://min.io/docs/minio/linux/developers/java/minio-java.html#minio-java-quickstart

But I don't understand how can I
1.Create policy
2. Create User
3. Assign policy to user

Is there way to do it ?

Also I haven't found any example here: https://github.com/minio/minio-java/tree/master/examples

Related topic on SO: https://stackoverflow.com/questions/74810155/is-there-way-to-setup-user-policy-using-minio-java-client-api

**Comment by balamurugana** [comment]
Use [AWS Policy Generator](https://awspolicygen.s3.amazonaws.com/policygen.html) to get policy JSON, then use [setBucketPolicy() API](https://minio-java.min.io/io/minio/MinioAsyncClient.html#setBucketPolicy-io.minio.SetBucketPolicyArgs-)

**Comment by gredwhite** [comment]
> [na](/balamurugana)

I don't need bucket policy! I want to setup user policy!

**Comment by balamurugana** [comment]
`minio-java` does not support user IAM policy.

**Comment by gredwhite** [comment]
> `minio-java` does not support user IAM policy.

So what option do I have if I want to restrict access to bucket for particular user ?

**Comment by balamurugana** [comment]
If I understand correctly, you are looking for minio admin APIs. `minio-java` has limited support on that and you could explore from the source code [here](https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java)

**Comment by gredwhite** [comment]
> If I understand correctly, you are looking for minio admin APIs. `minio-java` has limited support on that and you could explore from the source code [here](https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java)

Ohhh, it looks like a good thing to investigate. Will do it.

looks like it could work for me   [public void addCannedPolicy(@Nonnull String name, @Nonnull String policy)](https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L489)

**Comment by Mert18** [comment]
@gredwhite were you able to assign a policy to a user using this api, or did you find any other solutions to implement this?
