### ISSUE TITLE
Use [AWS Policy Generator](https://awspolicygen.s3.amazonaws.com/policygen.html) to get policy JSON, then use [setBucketPolicy() API](https://minio-java.min.io/io/minio/MinioAsyncClient.html#setBucketPolicy-io.minio.SetBucketPolicyArgs-)

### ISSUE THREAD

**Issue by gredwhite** [minio/minio-java#1396]
Use [AWS Policy Generator](https://awspolicygen.s3.amazonaws.com/policygen.html) to get policy JSON, then use [setBucketPolicy() API](https://minio-java.min.io/io/minio/MinioAsyncClient.html#setBucketPolicy-io.minio.SetBucketPolicyArgs-)

_Originally posted by @balamurugana in https://github.com/minio/minio-java/issues/1395#issuecomment-1352993929_
      

For some reasons [my issue](https://github.com/minio/minio-java/issues/1395#issuecomment-1352993929) was closed but!

I don't need bucket policy! I want to setup user policy! How can I achieve it using minio java SDK ?

**Comment by balamurugana** [comment]
`minio-java` does not support user policy.

**Comment by gredwhite** [comment]
> `minio-java` does not support user policy.
So what option do I have if I want to restrict access to bucket particular user ?

**Comment by harshavardhana** [comment]
> So what option do I have if I want to restrict access to bucket particular user ?

Use `mc` @gredwhite

**Comment by gredwhite** [comment]
> > So what option do I have if I want to restrict access to bucket particular user ?
> 
> Use `mc` @gredwhite

Is it possible to use mc from java code ?
