### ISSUE TITLE
listParts error

### ISSUE THREAD

**Issue by sujiangtao123** [minio/minio-java#1397]
Upload large files to obtain uploaded fragments  error：
call metho name：listParts
minio version：8.2.2

error message：
 org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=DisplayName, type=void, data=false, required=true) on field 'displayName' private java.lang.String io.minio.messages.Initiator.displayName in class

**Comment by balamurugana** [comment]
This is fixed in the latest version. Please upgrade your `minio-java` to the latest version.

**Comment by balamurugana** [comment]
> > This is fixed in the latest version. Please upgrade your `minio-java` to the latest version.
> 
> upgrade ，Is it compatible with the old version？

It is compatible with the version you mentioned above.
