### ISSUE TITLE
demo Broken pipe

### ISSUE THREAD

**Issue by simazilin** [minio/minio-java#1398]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/39558873/208675644-84875c53-8272-49f2-9501-1d3c7cb9f10a.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/39558873/208675713-045c6919-cf1a-4d7c-bc70-69c00fb0b65d.png">

please. i don't know why?

**Comment by balamurugana** [comment]
This means the server closes the connection abnormally.
