### ISSUE TITLE
minio whether callback is supported

### ISSUE THREAD

**Issue by sujiangtao123** [minio/minio-java#1403]
minio SDK version 8.4.6, the last version!

now, upload file，front use Presignature Upload file directly to minio，the upload action, server don't  know，minio whether callback is supported？ Try to let the server know，because I need to know when uploaded it, to make records, Is it implemented？

**Comment by balamurugana** [comment]
What do you mean by `front use Presignature Upload file directly to minio，the upload action, server don't know`?

Presigned URL means the request had been signed using provided access/secret keys and later someone uses the url to upload/download/operate on the URL. Each and every requests are handled and served by S3 server.

If you don't want to use presigned URL, use bucket policy.

**Comment by sujiangtao123** [comment]
>  OK， later someone uses the url to upload/download/operate on the URL.
presigned URL need My file service is required to generate，
so , I provide authorized servers，How do you know when someone uploaded it? 
S3 server Can I have a callback?  Can I provide a callback of the signed service？

**Comment by balamurugana** [comment]
Sharing presigned URL is equally sharing your access/secret keys to perform a specific operation. It is up to you to decide whether you want to share the URL.

To get notification on object operations, refer https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html

**Comment by sujiangtao123** [comment]
thank you， I know what you mean， Maybe I'm not accurate， I want  to  know ，minio SDK  method:  
getPresignedPostFormData:   Post Policy whether  can set callBack?
Implementation like this refer： [https://help.aliyun.com/document_detail/31927.html](url)

**Comment by balamurugana** [comment]
I strongly recommend to go through [java doc](https://minio-java.min.io/) and links to S3 specifications. `minio-java` is meant for S3 compatible server/service. If you are looking beyond that, extend `MinioClient` to implement you own.
