### ISSUE TITLE
Minio reactive client feature request

### ISSUE THREAD

**Issue by gredwhite** [minio/minio-java#1404]
If I am not mistaken...without reactive minio client I can't avoid MinioClient creation for every http call in scenario described here:

https://stackoverflow.com/questions/74875058/how-to-get-jwt-token-value-in-spring-webflux-to-exchange-it-with-minio-sts-tok

It should be considered to add reactive minio client

**Comment by balamurugana** [comment]
`ClientGrantsProvider`/`WebIdentityProvider` accepts a callback function to get JWT token is used in `fetch()` method. How this callback function implemented is up to the user i.e. `minio-java` has no control on that. If you are using `spring-webflux` to get JWT token is beyond control of `minio-java` and you would need to seek advice on respective project.

**Comment by gredwhite** [comment]
> `ClientGrantsProvider`/`WebIdentityProvider` accepts a callback function to get JWT token is used in `fetch()` method. How this callback function implemented is up to the user i.e. `minio-java` has no control on that. If you are using `spring-webflux` to get JWT token is beyond control of `minio-java` and you would need to seek advice on respective project.

If I understand them properly - they don't want to provide way to get raw token because of nature of reactive programming so I requested the feature
