### ISSUE TITLE
Some questions about setBucketReplication

### ISSUE THREAD

**Issue by ZCM-624** [minio/minio-java#1405]
only one Replication rule can be kept in server?

The replication rule I set last time is overridden when I tried to call setBucketReplication again.

This only happens when I call setBucketReplication. I can have more than one , if I set replication rule through Minio Console.

Thank you for your answer!

**Comment by balamurugana** [comment]
Refer https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketReplication.html#AmazonS3-PutBucketReplication-request-Rules.

You have to append rules and call `setBucketReplication`
