### ISSUE TITLE
Nested folder existence control

### ISSUE THREAD

**Issue by Mert18** [minio/minio-java#1408]
I am trying to check if some nested folders exists. `StatObject` always throws 404 even if I have the folder(and I put "/" at the end of the name to denote it is a folder).

How can I check if a folder inside a folder exists? If I list the objects, It only lists the top level objects, and I cant go deep.

Thanks in advance.

This is what I have tried so far:
```
  try {
            StatObjectArgs statObjectArgs = StatObjectArgs.builder().bucket("x")
                    .object(x + "/" + y+ "/").build();
            minioClient.statObject(statObjectArgs);
        } catch (ErrorResponseException e) {
            System.out.println("error: " + e.errorResponse().code());
            if (e.errorResponse().code().equals("NoSuchKey")) {
                throw new ApplicationException("x does not exist. First create the x folder on minio.");
            } else {
                throw new ApplicationException("Error while checking if the region exists.");
            }
        }
```

**Comment by balamurugana** [comment]
There is no _folder_ as per S3 specification. An object name may contain zero or more `/` character in it. If you had created an object whose name is ending with `/` can get stat information. Otherwise it is literally `404 Not Found`.
