### ISSUE TITLE
Bucket policies with LDAP users or groups.

### ISSUE THREAD

**Issue by Mert18** [minio/minio-java#1410]
So I have a Private Cloud Minio Server (not aws), I have integrated FreeIPA Ldap server, and set admin policy for a user:
`mc admin policy set mycloud consoleAdmin user='uid=mert,cn=users,cn=accounts,dc=x,dc=y'`
I want to do this operation with this Java SDK, is this possible yet?

Or Can I create, delete, or assign a policy to a user using this SDK?

setBucketPolicy offers something like this:
```
// Assume policyJson contains below JSON string;
// {
//     "Statement": [
//         {
//             "Action": [
//                 "s3:GetBucketLocation",
//                 "s3:ListBucket"
//             ],
//             "Effect": "Allow",
//             "Principal": "*",
//             "Resource": "arn:aws:s3:::my-bucketname"
//         },
//         {
//             "Action": "s3:GetObject",
//             "Effect": "Allow",
//             "Principal": "*",
//             "Resource": "arn:aws:s3:::my-bucketname/myobject*"
//         }
//     ],
//     "Version": "2012-10-17"
// }
//
minioClient.setBucketPolicy(
    SetBucketPolicyArgs.builder().bucket("my-bucketname").config(policyJson).build());
```
Can I put my "ldap dn" path in "Principal" object and expect it to work?

There are some questions related to this one aged 3 years. Maybe something changed?

**Comment by balamurugana** [comment]
Limited support of admin operations can be found in [MinioAdminClient](https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java). Feel free to send a PR if any missing functionality you are expecting.
