### ISSUE TITLE
Allow to use httpClient other that OKHTTP

### ISSUE THREAD

**Issue by jtama** [minio/minio-java#1414]
OkHttp4 v4 has been written in kotlin and thus the library depends on kotin stdlib.

It would be great to be able to provide and httpclient that is not okhttp, to prevent depending kotlin.

Being maintainer of the quarkus-minio extension, I can't update to latest versions of minio-java, and I am stuck with 3.23.1 release.

**Comment by balamurugana** [comment]
We have no plan to move away from okhttp
