### ISSUE TITLE
How to download the folder from minio as zip file?

### ISSUE THREAD

**Issue by AjayShivanagol** [minio/minio-java#1415]
The steps I followed for this are.

1. get all objects from recursive objects
`Iterable<Result<Item>> results = minioClient.listObjects(ListObjectsArgs.builder()
    .bucket(bucketName).recursive(true).build());`
    
2. Then getting all streams of matching the prefix
` InputStream stream = minioClient.getObject(GetObjectArgs.builder()
.bucket(bucketName).object(objectName).build());`

the list of multiple streams got by the InputStream stream How do we convert it into zip file ?

tried the following code but it's (zipOut) coming as null. downloading empty zip, How do we fix this ?

`ByteArrayOutputStream fos = new ByteArrayOutputStream();
ZipOutputStream zipOut = new ZipOutputStream(fos);
ZipEntry zipEntry1 = new ZipEntry(objectName);
zipEntry1.setSize(resource.contentLength());
zipEntry1.setTime(System.currentTimeMillis());
zipOut.putNextEntry(zipEntry1);
StreamUtils.copy(stream.readAllBytes(), zipOut);
zipOut.closeEntry();`

Thanks in advance.

**Comment by balamurugana** [comment]
Refer https://stackoverflow.com/questions/1091788/how-to-create-a-zip-file-in-java how do add entries to zip file.
