### ISSUE TITLE
Parallel downloading of the same file is not supported

### ISSUE THREAD

**Issue by melin** [minio/minio-java#1416]
Two threads downloading the same file at the same time，

![image](https://user-images.githubusercontent.com/1145830/212240324-40962f06-e773-4f2d-92d8-9512d4b364cb.png)

**Comment by harshavardhana** [comment]
If you want to download two concurrent stream you should use a different API without the filename. 

You can get your own stream for each and manage it however you like.

We cannot possibly allow you to download same object to same filename locally it doesn't make sense.
