### ISSUE TITLE
How can i set s3:BypassGovernanceRetention permission for users

### ISSUE THREAD

**Issue by ZCM-624** [minio/minio-java#1417]
i want to delete objects which has setted Retention.
I read S3 protocol and found that can only deleted in Governance mode and user must have the s3:BypassGovernanceRetention permission.
How can i give user this permission?

thank you for your answer!

**Comment by balamurugana** [comment]
Refer https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html
