### ISSUE TITLE
Consider storing response code in a field in InvalidResponseException

### ISSUE THREAD

**Issue by jgolda** [minio/minio-java#1420]
Hello, 

During communication with S3 i'm occasionally getting an HTTP 503 response which ends up with minio client throwing an io.minio.errors.InvalidResponseException. In case of 5xx errors i'm retrying a part of the process executed on application side. Currently the only way of determining the response code after catching this exception is parsing the error message created in constructor. 

Please consider adding a field in the exception, which would hold the response code for easier access.

Best regards, 
Jacek

**Comment by balamurugana** [comment]
`InvalidResponseException` is raised if server doesn't send XML error response which should not happen.  If you are trying only for HTTP status code 503 i.e. low level access, feel free to inherit respective class and use it.

**Comment by jgolda** [comment]
Do you mean inheriting MinioAsyncClient and overwriting executeAsync(), just in order to throw another implementation of InvalidResponseException? Or is there another simpler way? It sounds like a lot of hassle for a quite simple task
