### ISSUE TITLE
How to use client get bucket size?

### ISSUE THREAD

**Issue by PeixyJ** [minio/minio-java#1421]
你好,怎么使用连接进行获取桶的已经使用的大小和桶的信息?
-------
hi,How to use the connection to obtain the used size and bucket information of the bucket?

**Comment by balamurugana** [comment]
Please describe your issue in English clearly.

**Comment by PeixyJ** [comment]
hi,How to use the connection to obtain the used size and bucket information of the bucket?
In my project, I need to check the size of each bucket? But I didn't find the relevant method in MinioClient?
