### ISSUE TITLE
How to use client get bucket size?

### ISSUE THREAD

**Issue by PeixyJ** [minio/minio-java#1422]
hi,How to use the connection to obtain the used size and bucket information of the bucket?
In my project, I need to check the size of each bucket? But I didn't find the relevant method in MinioClient?

**Comment by balamurugana** [comment]
You could check [getDataUsageInfo()](https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L593)

**Comment by PeixyJ** [comment]
@balamurugana Thank you for your help
