### ISSUE TITLE
When I use the removeObject in the java SDK to delete an empty folder, it cannot be deleted, and the response is successful

### ISSUE THREAD

**Issue by ZCM-624** [minio/minio-java#1426]
When I use the removeObject in the java SDK to delete an empty folder, it cannot be deleted, and the response is successful

Thank you for your answer!

**Comment by balamurugana** [comment]
It can be remvoed only if it was created using `PutObject` or `UploadObject`

**Comment by javaCR7** [comment]
> It can be remvoed only if it was created using `PutObject` or `UploadObject`

object was created using PutObject，but it still can not be removed.

**Comment by balamurugana** [comment]
You would need to check your S3 server. Nothing can be done at client side
