### ISSUE TITLE
Can I generate a presigned Url which I can use it to download different Objects (satisfy some policy)?

### ISSUE THREAD

**Issue by cret0103** [minio/minio-java#1428]
I want to generate something like a token on the server side and send it to the frontend. This token contains some policies (e.g. objectId starts with `xxx/`), and then I can use this token on the frontend to directly download multiple objects on minio that satisfy these policies.
What should I do? Or, is there an alternative?

**Comment by harshavardhana** [comment]
No that is not possible in S3 API @cret0103
