### ISSUE TITLE
How to get "my-versionid"?

### ISSUE THREAD

**Issue by hukang6677** [minio/minio-java#1429]
minioClient.removeObject(
                    RemoveObjectArgs.builder()
                            .bucket("my-bucketname")
                            .object("my-versioned-objectname")
                            .versionId("my-versionid")
                            .build());

**Comment by balamurugana** [comment]
Use https://minio-java.min.io/io/minio/MinioAsyncClient.html#statObject-io.minio.StatObjectArgs-
