### ISSUE TITLE
SetBucketLifecycle not in effect

### ISSUE THREAD

**Issue by hukang6677** [minio/minio-java#1430]
Lifecycle was set at 9:40 yesterday morning.

![1DF687FF-7DD3-462a-851D-66ED05FF3B8C](https://user-images.githubusercontent.com/102129512/224878754-4b6875c0-4a4d-4dd8-a856-0c36508ac2d1.png)
![C09853D0-5213-4772-B399-8853D5E927E5](https://user-images.githubusercontent.com/102129512/224879059-73e09612-c8d2-41cd-ba66-1a7fa593c8d2.png)
![C09853D0-5213-4772-B399-8853D5E927E5](https://user-images.githubusercontent.com/102129512/224879151-5d60706c-bf70-4f39-99e1-c151b705272e.png)

**Comment by hukang6677** [comment]
![7FAC6CDA-89F9-4e9b-A8CC-97910A0E4C76](https://user-images.githubusercontent.com/102129512/224879796-e048d821-7faa-4574-ac19-1b3366957961.png)

**Comment by hukang6677** [comment]
![6DC8E19C-EC5B-4381-8012-C398006B8A70](https://user-images.githubusercontent.com/102129512/224880036-844d95dc-cce1-4dfb-968c-37b3bf31b816.png)

**Comment by balamurugana** [comment]
Nothing can be done client side here. Open the issue in minio server.

**Comment by hukang6677** [comment]
@balamurugana 
What do you mean?
