### ISSUE TITLE
Client blocks main thread upon shutdown

### ISSUE THREAD

**Issue by szgergo** [minio/minio-java#1431]
**Symptom:**
When I use the MinioClient with anything (for example listBuckets) in a simple main method without any hassle, the application keeps running after the last line was executed for another 15-20 seconds.

**How to reproduce**

1. Start a Minio instance
2. Create an Access key
3. clone the following repo: https://github.com/szgergo/huge-file-splitter-minio
4. Change the dummy credentials
5. Start the application

**What's causing the issue**
It looks like the underlying OkHttpClient's ThreadPoolExecutor is the culprit.When I create a custom one with lowered keepAliveMs (from 60 to 1 second for example), the application exits correctly in time.

**Working environment**

**OS**
Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

**Java version**
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)

**Client version**
8.4.3

**Possible solution**
Introduce a custom ThreadPoolExecutor and OkHttp Dispatcher in HttpUtils#newDefaultHttpClient with reduced keepAliveMs

**Comment by balamurugana** [comment]
As you mentioned `okhttp` is waiting for timeout, this is not `minio-java` issue.
