### ISSUE TITLE
Trying to addUser

### ISSUE THREAD

**Issue by fdabrao** [minio/minio-java#1432]
I'm trying to create a new user into S3 Compatible enviroment, but I'm getting this:
; Execution error at io.minio.admin.MinioAdminClient/execute (MinioAdminClient.java:206).
; Request failed with response: <?xml version="1.0" encoding="UTF-8"?>
; <Error><Code>BucketAccountInactive</Code><Message>The account that owns this bucket is not active.</Message><OwnerAccountCanonicalId>38FB034676FB9667398C4C447E0F1F9C9752975B34DF64CB67270689173296AC</OwnerAccountCanonicalId><RequestId>3D34ACCEF52687E4</RequestId><HostId>28QoxrgnQ8F6TSpxQyeFeKOaBrqlHhgqF3ANdDKC85wB+pM3J2ytqME6ZG4stAfDIh/CozSEr09v</HostId></Error>

**Comment by balamurugana** [comment]
As server returns the error, you would need to consult with your S3 server/service.
