### ISSUE TITLE
How to implement mv bucket in minio when use java sdk

### ISSUE THREAD

**Issue by lfygh** [minio/minio-java#1435]
I have seen the solution by minio client.

```shell
mc mb myminio/newbucket
mc mirror myminio/oldbucket myminio/newbucket
mc rm -r --force myminio/oldbucket
```
but, how to implement the above command using SDK

My original requirement was to implement soft deletion of buckets，Do you have any suggestions?

**Comment by balamurugana** [comment]
Hint is, `makeBucket()`, `listObjects()`, `listObjectVersions()`, `getObject()`, `putObject()` and `removeObjects()` methods of `MinioAsyncClient` need to be used.

You would need to build up the logic using mentioned APIs.
