### ISSUE TITLE
Why the official MinIO Java driver?

### ISSUE THREAD

**Issue by Mechite** [minio/minio-java#1438]
### Discussed in https://github.com/minio/minio/discussions/17002

<div type='discussions-op-text'>

<sup>Originally posted by **Mechite** April  9, 2023</sup>
Heya! I'd like to ask what the advantages are to using the official MinIO Java driver versus using the S3 module from the Amazon AWS SDK.

I have already written my infrastructure around the official MinIO driver which seems to essentially be a "worse" version of the S3 driver where you have this stinky overly employed polymorphism everywhere with argument builders, etc; but while this doesn't really affect usability, my main gripe is the inability to have multiple endpoints! Should I be using the S3 driver, or is there really some performance advantage or something for this driver?

Only being able to define one connection endpoint is horrible, though I'm making the bold assumption the client automatically discovers subsequent nodes and will load balance and have reliable failover built in. This is likely the case, but wouldn't it still be better to have this functionality so that a container won't simply crash if the single endpoint provided happened to be offline? Ephemeral uses of MinIO are actually probably quite a common use case, so being able to define multiple endpoints would lead to better sleep.

I asked this question in the official Slack channel but nobody seemed to respond.

![image](https://user-images.githubusercontent.com/50027352/230798243-cc5570fc-6c15-430e-b391-96ccd1ee7c6e.png)</div>

**Comment by balamurugana** [comment]
You could use Amazon AWS Java SDK or any SDK implementing S3 specification. In this case, you will be loosing MinIO specific options/APIs/features. It is our design choice to go with argument builders as each API has many variables to perform and many of them are optional.

WRT MinIO server setup, you would need to use load balancer or a specific endpoint to one client in MinIO SDKs. If you want to have client side load balancing, it is not a good idea as attempt to execute an API would have read your input data ready which is not possible to read again e.g. `PutObject` S3 API call.  This means it is not possible to give a general purpose solution and you would need to look your own way here.

**Comment by Mechite** [comment]
> You could use Amazon AWS Java SDK or any SDK implementing S3 specification. In this case, you will be loosing MinIO specific options/APIs/features. It is our design choice to go with argument builders as each API has many variables to perform and many of them are optional.
> 
> WRT MinIO server setup, you would need to use load balancer or a specific endpoint to one client in MinIO SDKs. If you want to have client side load balancing, it is not a good idea as attempt to execute an API would have read your input data ready which is not possible to read again e.g. `PutObject` S3 API call. This means it is not possible to give a general purpose solution and you would need to look your own way here.

What MinIO specific features are there? The driver seems extremely trivial.
Also, I would argue that optional variables would be better handled by simply overloading API methods.

Either way, my main concern is the inability to have multiple endpoints, I don't care enough for API design here so long as I can have a reliable client. This is something that would usually only be done for failover, and in this case it should be available because it would easily cause any ephemeral runs to fail should the _only_ provided node qualifier be dead. Using a middle-man load balancer to prevent this would be too centralised.
