### ISSUE TITLE
Issue: Client starts giving AccessDenied when upgrading 7.1.4 to 8.x.x

### ISSUE THREAD

**Issue by m3rkator** [minio/minio-java#1441]
Hi

When upgrading my Maven dependencies from 7.1.4 to any 8.x.x minio starts respondig with "access denied" on any operation.

I've supplied to traces. One with 7.1.4, the other with 8.5.2.

[dump7.txt](https://github.com/minio/minio-java/files/11230123/dump7.txt)

[dump8.txt](https://github.com/minio/minio-java/files/11230124/dump8.txt)

The differences appear following the line "Check exists" where i check if a certain bucket is in existence.

System.out.println(client.bucketExists(BucketExistsArgs.builder().bucket("kalo-file-transfer-ws").build()));

**This is the behaviour of the 7.1.4:**

Check exists
---------START-HTTP---------
HEAD /kalo-file-transfer-ws HTTP/1.1
Host: minio-dev.lb.kgrp.net
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/1.7.22-release-288(1.7.22)
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20230414T073057Z
Authorization: ██

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Date: Fri, 14 Apr 2023 07:30:57 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1755BCA606545410
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

----------END-HTTP----------

**And here the 8.5.2**

Check exists
---------START-HTTP---------
GET /kalo-file-transfer-ws?location= HTTP/1.1
Host: minio-dev.lb.kgrp.net
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.5.2
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20230414T073153Z
Authorization: ██

[Lots of SSL tracing]

Exception in thread "main" error occurred
ErrorResponse(code = AccessDenied, message = Access Denied., bucketName = kalo-file-transfer-ws, objectName = null, resource = /kalo-file-transfer-ws, requestId = 1755BCB3324A1098, hostId = 26c2ad53-c3e1-42b7-a86c-9708610c187d)
request={method=GET, url=https://minio-dev.lb.kgrp.net/kalo-file-transfer-ws?location=, headers=Host: minio-dev.lb.kgrp.net
Accept-Encoding: identity
User-Agent: MinIO (Windows 10; amd64) minio-java/8.5.2
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20230414T073153Z
Authorization: ██
}
response={code=403, headers=Accept-Ranges: bytes
Content-Length: 293
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 14 Apr 2023 07:31:53 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1755BCB3324A1098
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
}

	at io.minio.S3Base$1.onResponse(S3Base.java:690)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
HTTP/1.1 403
Accept-Ranges: bytes
Content-Length: 293
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 14 Apr 2023 07:31:53 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 1755BCB3324A1098
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>kalo-file-transfer-ws</BucketName><Resource>/kalo-file-transfer-ws</Resource><RequestId>1755BCB3324A1098</RequestId><HostId>26c2ad53-c3e1-42b7-a86c-9708610c187d</HostId></Error>
----------END-HTTP----------

**Comment by balamurugana** [comment]
I see ` GET /kalo-file-transfer-ws?location= HTTP/1.1` is failing. You need to enable `GetBucketLocation` access in the server or pass the region to `MinioClient` or `BucketExistsArgs`
