### ISSUE TITLE
Integrate minio into Springboot Maven

### ISSUE THREAD

**Issue by yangmingli08** [minio/minio-java#1442]
I want to integrate minio into Java Spring Project. I added this into pom.xml

	  	<dependency>
			<groupId>io.minio</groupId>
			<artifactId>minio</artifactId>
			<version>8.4.3</version>
		</dependency>

When I did a demo upload, errors occour as follows,

[NoClassDefFoundError: Could not initialize class MinioAsyncClient]

I searched dependencies, then found that okhttp version is 2.5.0

My project didn't use okhttp except minio. Strangely, in minio.pom  it clearly states that

    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>4.8.1</version>
      <scope>compile</scope>
    </dependency>

I don't know how it comes with wrong version and I am sure that my previous project without springboot works perfectly and its okhttp version is 4.8.1, so I did this

		<dependency>
			<groupId>io.minio</groupId>
			<artifactId>minio</artifactId>
			<version>8.4.3</version>
			<exclusions>
				<exclusion>
					<groupId>com.squareup.okhttp3</groupId>
					<artifactId>okhttp</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.8.1</version>
		</dependency>

Problem solved.

There must be something spooky happened and I don't know what it is. Many thanks to anyone can help me explain this otherwise I will use my method instread.

**Comment by balamurugana** [comment]
minio-java depends on okhttp `v4.8.1`, but spring boot depends on different okhttp version. you would need to solve the dependency issue like you mentioned.
