### ISSUE TITLE
download 403

### ISSUE THREAD

**Issue by javaCR7** [minio/minio-java#1447]
## NOTE
I request  the
"minioClient.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder().method(Method.GET).bucket(bucketName).object(objectName).expiry(expires, TimeUnit.DAYS).build());"
response a download url
I used "file-saver" to save the docment which is a  extension ".txt" .
response error 403. and open a new tab
![image](https://user-images.githubusercontent.com/38103065/235089708-0814d11b-ce3d-4608-ba94-14d6eaad7e70.png)
![image](https://user-images.githubusercontent.com/38103065/235089761-0b5c23c0-ea9f-47cf-a207-5e83fa9e8ce9.png)

what's this problem?

* 8.5.2
* Java ,vue,file-saver

**Comment by balamurugana** [comment]
You created presigned URL for `GET` method, but called for `HEAD`.

**Comment by javaCR7** [comment]
I see .Thanks
