### ISSUE TITLE
request has multiple authentication types, please use one

### ISSUE THREAD

**Issue by song-cc-rock** [minio/minio-java#1448]
Client Version: 8.5.2
Description: I have a problem that when I upload a file, small files are Ok, but large files over 5M will cause this exception. 
I solved this problem by dropping the contentType and using the default application/octet-stream type, but this caused the uploaded file types to be indistinguishable. So How do I handle the problem well. (Note: The file content type is multipart/formdata when I upload)
The Code 👍 
![image](https://user-images.githubusercontent.com/40567414/235090349-c59f4dc9-f8a7-4472-9b7b-1e051aa94bf1.png)

**Comment by harshavardhana** [comment]
@song-cc-rock can you enable trace on and share with us the client request trace?

**Comment by song-cc-rock** [comment]
> @song-cc-rock can you enable trace on and share with us the client request trace?

you mean the call tracing of the minio api ?

i can show you the http trace: 

------------------------------------------------------
---------START-HTTP---------
POST /metersphere/9d6dafad-90ea-404c-8833-c3289185ace4/MeterSphere_v2.8.0_TestPlan-2023-04-24%2010_01_40.html?uploads= HTTP/1.1
Content-Type: multipart/form-data
Host: 192.168.0.41:9000
Accept-Encoding: identity
User-Agent: MinIO (Windows 11; amd64) minio-java/8.5.2
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20230428T080900Z
Authorization: ██

HTTP/1.1 400
Accept-Ranges: bytes
Content-Length: 338
Content-Type: application/xml
Server: MinIO
Vary: Origin
Date: Fri, 28 Apr 2023 08:09:00 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Invalid Request (request has multiple authentication types, please use one)</Message><Resource>/metersphere/9d6dafad-90ea-404c-8833-c3289185ace4/MeterSphere_v2.8.0_TestPlan-2023-04-24 10_01_40.html</Resource><RequestId></RequestId><HostId></HostId></Error>
----------END-HTTP----------
