### ISSUE TITLE
Introduce a method for extracting region id from url

### ISSUE THREAD

**Issue by jgolda** [minio/minio-java#1450]
(Sorry for creating a new issue, but i cannot reopen the previous one https://github.com/minio/minio-java/issues/1449, since you closed it as a maintainer)
If you're not willing to fix this problem, then could you at least provide a public method, which will extract the region id from url? I have no problem with setting it myself, but i need to get the region id from urls. I already have client's configurations with this form of urls - it will be hard to persuade all the clients to reconfigure all their processes manually

**Comment by jgolda** [comment]
I'm currently still using version 8.3.9 and i'm creating the client in the following way:
`MinioClient client = MinioClient.builder()`
`                .httpClient(httpClientCreatedAndConfiguredSomewhereElse)`
`                .endpoint("https://s3.eu-central-1.amazonaws.com/")`
`                .credentials("someAccessKey", "someSecretKey")`
`                .build();`

Of course the urls and credentials are now hardcoded, but could be configured by clients. I'm aware that there is a newer version of minio, but to my best knowledge nothing changed in it in terms of handling the region id on url.

**Comment by balamurugana** [comment]
Use below logic to extract region from Amazon AWS S3 endpoint. I have no plans to have it as separate method.
```java
    String region = null;
    String[] tokens = host.split("\\.");
    String token = tokens[1];
    // If token is "dualstack", then region might be in next token.
    if (token.equal("dualstack")) {
      token = tokens[2];
    }
    // If token is not "amazonaws", then region is passed in the host.
    if (!token.equal("amazonaws")) {
      region = token;
    }
```
