### ISSUE TITLE
getPresignedObjectUrl uses wrong domain name

### ISSUE THREAD

**Issue by call-a3** [minio/minio-java#1451]
## Context

I have a piece of software that interfaces with Minio. Both my software and Minio are run in docker containers within the same docker network. As a consequence, my software connects to Minio at `http://minio:9000`.
I expose both my software and the Minio API through a reverse proxy, so from the public internet my application would be reachable at `https://app.example.com` and Minio at `https://minio.example.com`. This situation is reflected in the Minio server settings by setting `MINIO_SERVER_URL=https://minio.example.com`.

## Used Feature
I want to generate a presigned URL from my software, that can be shared with a user on the public internet.

## Expected behaviour
I expect the result of [getPresignedObjectUrl](https://minio-java.min.io/io/minio/MinioClient.html#getPresignedObjectUrl-io.minio.GetPresignedObjectUrlArgs-) to use the public server URL as the baseurl, as configured in Minio (`https://minio.example.com/:bucket/:objectpath?...params`).

## Actual behaviour
The result of `getPresignedObjectUrl` uses the baseURL from the client configuration (`http://minio:9000/:bucket/:objectpath?...params`)

## Initial investigation
I've found that [getPresignedObjectUrl](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioAsyncClient.java#L917) uses the method [buildUrl](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/S3Base.java#L290), which in turn uses the baseUrl property of the client to generate the presigned URL locally.

If I compare this to the implementation that minio/console uses to generate what is called a "Share link", I see it calls the Minio API [POST /api/v1/buckets/${bucketName}/objects/share](https://github.com/minio/console/blob/master/portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ShareFile.tsx#L180) to get the presigned URL from the Minio server itself.

**Comment by balamurugana** [comment]
If you want to get presign URL, you would need to use the hostname appropriately i.e. the hostname must be used as endpoint to create `MinioClient`. It is not possible to use different hostname.

MinIO Console uses MinIO server's internal API, but `minio-java` is S3 SDK.
