### ISSUE TITLE
How can i get the bucket info like objects number and space used?

### ISSUE THREAD

**Issue by coderfromhebei** [minio/minio-java#1452]
I try to use listObjects() with recursive(true) to get all objects then do respective computations, but i was so slow when the bucket has many files.

**Comment by lukasraska** [comment]
FWIW `MinioAdminClient` contains `getDataUsageInfo()` method (https://github.com/minio/minio-java/blob/master/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L593 ), which contains `bucketsUsageInfo`, which has `size` and `objectsCount`, so you can use those information to estimate number of objects and used space within one bucket. But that client is Minio-specific so will not work for other servers

**Comment by coderfromhebei** [comment]
@balamurugana @lukasraska Thanks for help
