### ISSUE TITLE
No access to HTTP status for `getObject`

### ISSUE THREAD

**Issue by sne11ius** [minio/minio-java#1455]
Getting an object gives a `GetObjectResponse`. This class does not contain the HTTP status.

I am interested in the status because I want to know whether my range request gets me all data (HTTP 200) or partial content (HTTP 206).

Are there arguments against including the status in the `GetObjectResponse`? If not, would you be open to a PR?

**Comment by balamurugana** [comment]
As you have requested `GetObject` with `offset` and/or `length`, the returned value contains range data. This itself suffices to conclude.

If you still wants to know HTTP status code, extend `MinioClient` and override respective methods. We have no plans to add HTTP status code in the response.
