### ISSUE TITLE
getPresignedObjectUrl() put url CORS

### ISSUE THREAD

**Issue by YiuWaKwan** [minio/minio-java#1457]
I successfully retrieved the url using the getPresignedObjectUrl() method , using curl can upload the file successfully
![image](https://github.com/minio/minio-java/assets/75985039/b3876585-93b0-428d-b8ef-1a0cc1f22de8)
   but my client sent a put request with an error
![image](https://github.com/minio/minio-java/assets/75985039/7aacefa8-bdb0-4108-8d34-ab28f49b5507)
![image](https://github.com/minio/minio-java/assets/75985039/fcd13f50-d19a-4741-818e-1591e52c2750)

Is this because of minio server configuration issues?

**Comment by balamurugana** [comment]
You need to check why your server is returning errors. Nothing can be done at client side.
