### ISSUE TITLE
Upgrade Android minVersion to 26 for using MethodHandle.invoke and MethodHandle.invokeExact in minio-java

### ISSUE THREAD

**Issue by Merpyzf** [minio/minio-java#1471]
To use the minio-java library in Android devices, it is required to adjust the minVersion of the application to 26 or higher. Otherwise, the build will fail due to the use of unsupported APIs. However, this may cause compatibility issues with devices running on Android versions earlier than 26.

`MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26): Lorg/xerial/snappy/pool/DirectByteBuffers$2;run()Ljava/lang/Void;`

It is currently common practice to set the Android minSdkVersion to 23, in order to ensure compatibility with earlier but still relevant versions of the operating system.

Therefore, I suggest upgrading the minVersion of the application to 26 or higher, in order to use the minio-java library in Android devices. This may require making necessary changes to the codebase to ensure compatibility across all Android versions.

Thank you for your attention to this issue.

**Comment by balamurugana** [comment]
We do not set any such requirement anywhere in the code for Android. I guess this should be done at minio-java user side. If not, feel free to send a PR.

**Comment by Merpyzf** [comment]
Yes, you are right. However, each Android system version has different support for Java. The snappy dependency used by minio-java relies on the MethodHandle.invoke or MethodHandle.invokeExact API, which is only supported on Android 10 and above. Therefore, in order to use minio-java in the project, I had to raise the minVersionCode of the project to 26 to compile it correctly. This means that I will lose users who use versions before 26. Can we consider releasing an Android-supported minio SDK?

**Comment by balamurugana** [comment]
Please send  PRs to support lower Android versions.

**Comment by antonymarion** [comment]
it seems related to https://github.com/minio/minio-java/issues/1280, I believe that this kind of a blocker for this lib regarding the following chart:

![image](https://github.com/minio/minio-java/assets/8767496/4a050de2-a816-433b-aaa7-dd3c0e03fce5)
