### ISSUE TITLE
module-info/JPMS?

### ISSUE THREAD

**Issue by Mechite** [minio/minio-java#1473]
```java
[WARN] **********************************************************************************************************************************************************************************
************************
[WARN] * Required filename-based automodules detected: [minio-8.5.2.jar]. Please don't publish this project to a public artifact repository! *
[WARN] **********************************************************************************************************************************************************************************
************************
```

As you can see, this Java client is not a JPMS compatible library.

**Comment by balamurugana** [comment]
Feel free to send a PR

**Comment by Mechite** [comment]
See #1474.

**Comment by Mechite** [comment]
An alternative approach I can propose is to use the `Automatic-Module-Name` header in the MANIFEST.MF in order to simply provide a stable name for the module. This is a way of achieving Java 1.8 compatibility without having to compile the module-info separately like a lot of projects have started doing. Downside? Much weaker encapsulation.

https://github.com/aws/aws-sdk-java-v2/ already uses this header to support JPMS.

**Comment by balamurugana** [comment]
Closing as stale issue
