### ISSUE TITLE
error on running minio on eclipse java windows

### ISSUE THREAD

**Issue by shernandezcorelate** [minio/minio-java#1475]
Help im encountering error when using spring boot/eclipse/ with new minio in windws.
it has also inserted other objects but getting this error

Caused by�[m: io.minio.errors.ErrorResponseException: You must specify at least one part
�[1mat�[m io.minio.MinioClient.execute (�[1mMinioClient.java:576�[m)
�[1mat�[m io.minio.MinioClient.executePost (�[1mMinioClient.java:673�[m)
�[1mat�[m io.minio.MinioClient.completeMultipart (�[1mMinioClient.java:1971�[m)
�[1mat�[m io.minio.MinioClient.putObject (�[1mMinioClient.java:1709�[m)
�[1mat�[m io.minio.MinioClient.putObject (�[1mMinioClient.java:1627�[m)
�[1mat�[m com.beacon.corelate.commons.file.repository.impl.MinioFileRepositoryImpl.putObject (�[1mMinioFileRepositoryImpl.java:59�[m)
�[1mat�[m com

**Comment by balamurugana** [comment]
If you are calling low level APIs yourself, you should follow the specification for multipart uploads.
