### ISSUE TITLE
no path allowed in endpoint http://my-ip-address:9000/xxx/

### ISSUE THREAD

**Issue by AnzhiZhang** [minio/minio-java#1476]
Hi,

I'm trying to connect to remote minio using java sdk and got `java.lang.IllegalArgumentException: no path allowed in endpoint http://my-ip-address:9000/xxx/`

The reason is that HttpUtils class:

```java
  public static void validateUrl(HttpUrl url) {
    if (!url.encodedPath().equals("/")) {
      throw new IllegalArgumentException("no path allowed in endpoint " + url);
    }
  }
```

I'm using nginx and have put minio under a /xxx/ path, is there a particular reason for this restriction, and if not is it possible to remove it?

**Comment by balamurugana** [comment]
As per S3 specification, path in the endpoint is not supported.
