### ISSUE TITLE
Intermittent error: NoSuchBucket

### ISSUE THREAD

**Issue by danilhisamov** [minio/minio-java#1479]
Hi! I am using Spring Webflux + Minio (async client) and facing intermittent error NoSuchBucket on the next scenario:
1. check if bucket exists
2. if not - create bucket
3. upload file(object) to bucket
4. clean up object and bucket

I have published a simple service with tests using testcontainers to demonstrate. There two tests with one pipeline written in different ways, but they do the same thing described above. But for some reason, second test fails sometime.

If I do the double check in the second pipeline it shows:
1. bucket exists: false
2. create bucket: response 200 OK
3. bucket exists: false

I received that bucket doesn't exist, even though directory was physically created in containers volume, and minio client received 200 OK response.

Could you help me to understand such kind of behavior?

[Demo repo](https://github.com/danilhisamov/minio_webflux)

**Comment by balamurugana** [comment]
You would need to check your S3 server/service why it returns non-2xx HTTP status code for `HeadBucket` request.

**Comment by balamurugana** [comment]
The error message states that the bucket doesn't exist for S3 API  `GetBucketLocation`. You should check your S3 server/service. Nothing can be done at client side.

**Comment by clayly** [comment]
> The error message states that the bucket doesn't exist for S3 API `GetBucketLocation`. You should check your S3 server/service. Nothing can be done at client side.

I am also facing this issue when using async client with Reactor. It was investigated here https://github.com/minio/minio/issues/17781 and looks like on server side it's all ok, but seems like some race condition with client, even if commands chained one after another (on Future completed).

**Comment by harshavardhana** [comment]
Okay thanks for confirming, so it must be something in the async model that waits for incorrectly.

@balamurugana do you know if we do anything specific with the ordering of calls here?

**Comment by balamurugana** [comment]
Please share your code. IMO you should wait bucket creation to be successful, then check for bucket existence.

**Comment by clayly** [comment]
> Please share your code. IMO you should wait bucket creation to be successful, then check for bucket existence.

There is example project with tests in issue. Code looks like you described, and I do the same. If you need more examples, please let me know.

**Comment by danilhisamov** [comment]
> I don't find any code other than wrapping `MinioAsyncClient` APIs with `Mono`

Have you seen test class in demo project?
https://github.com/danilhisamov/minio_webflux/blob/master/src/test/java/com/example/miniowebflux/service/MinioServiceTest.java
