### ISSUE TITLE
Get folder URL

### ISSUE THREAD

**Issue by mathieuleclaire** [minio/minio-java#1480]
Hi,
I would like to get a permanent folder (ie zip) URL. I do the following:

```scala
    minioClient.getPresignedObjectUrl(
      GetPresignedObjectUrlArgs.builder()
        .method(Method.GET)
        .bucket(myBucket)
        .`object`(fileName)
        .build
    )
```
where fileName is a folder path. It returns a marlformed URL: http://127.0.0.1:9000/mobiliquest/out-data/vtest/20230612/3563e426d2dec5c7e0d3f5813a697e2d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=mathieu%2F20230801%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230801T095702Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=dfece6c03e9b2cd558e218bb562c1983ed8d96bd041b86b3bfcf5d46ce7b60ab

It does work for a single file but apparently not for a folder. How could I achieve this ?
Thanks

**Comment by balamurugana** [comment]
You would need to use bucket policy to be set by `setBucketPolicy()`. To generate bucket policy refer https://awspolicygen.s3.amazonaws.com/policygen.html

**Comment by mathieuleclaire** [comment]
Uh, the policy generator is really cryptic, I don't understand most of the questions. If I understand well, a policy is a just a json file describing rights.
I guess my case is a very common one, do you know if it exists a list of common policy json files ?

**Comment by mathieuleclaire** [comment]
Actually, I am not sure to be clear. 
When I browse the folder in the web console, I can see the URL in my browser. When I jump from folder to folder until ```subfolder1/subfolder2/subfolder3```, the following URL appears in my browser: http://localhost:9001/browser/mobiliquest/b3V0LWRhdGEvdnRlc3QvMjAyMzA3MDYvMmJiODlkY2JjNmQyMDBhZGRmMDllNDc3ODU0OTI5YzQv. This is this URL, I would like to get programmatically, so that I can share it.

**Comment by mathieuleclaire** [comment]
Peharp's my problem comes from the way I run minio: it is a service launched behind a traefik reverse-proxy. I read that i should specify all this parameters to enable url to be reachable:
```sh
- MINIO_DOMAIN=minio.${MY_DOMAIN}
- MINIO_SERVER_URL=https://minio.${MY_DOMAIN}
- MINIO_BROWSER_REDIRECT_URL=https://minioadmin.${MY_DOMAIN}
- MINIO_SITE_REGION=eu-west-3

```
but my link is always lead to 404.

Any idea what could happened ? Is there someone a receipt to get presigned url from a minio behind a traefik ?
Thanks
