### ISSUE TITLE
OpenCensus tracing headers should not be signed

### ISSUE THREAD

**Issue by kfcss** [minio/minio-java#1494]
Hello Minio!

We are trying to add opencensus tracing when conducting calls through the Minio client SDK.

We added the [standard opencensus](https://github.com/census-instrumentation/opencensus-go/blob/01e6da5fc01c42aca1e0ce315f41744876e9fcbb/plugin/ochttp/propagation/b3/b3.go#L29-L33) tracing headers using the `extraHeaders` method. The headers are being correctly sent.

However, if the request is signed using S3 signature, then the requests fails. To understand why, we need a little deployment context. We have a setup where network is routed through Istio. Istio adds additional traces and modifies the standard opencensus headers through its proxies. When these headers are included in the signature, the minio server will reject the request since Istio modifies the values of the headers while being routed from the client to the server.

Is it possible to add the standard opencensus headers to [Signer.IGNORED_HEADERS](https://github.com/minio/minio-java/blob/16841e5632086a261ecefe357ce077860beae4ea/api/src/main/java/io/minio/Signer.java#L56C40-L56C40). The headers are `X-B3-TraceId`, `X-B3-SpanId` and `X-B3-Sampled`. They should be added in lowercase form.

Another option would be to allow customization of the Minio client to add additional headers to be ignored. This would be more future proof, as it could be used for other tracing systems.

What do you think?

**Comment by balamurugana** [comment]
According to S3 specification, signed headers should not be modified. As you are modifying headers mentioned in the description, it breaks the specification. As this is non-standard S3 operation, you could inherit `MinioAsyncClient` or `S3Base` class and have your custom implementation yourself.

**Comment by kfcss** [comment]
You are correct, signed headers should not be modified, or the signature breaks. That is why I ask you not to sign them in the first place.

The S3 specification clearly allows to not sign headers, and you communicate which headers that were part of the signature. See `SignedHeaders` on https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html. You are already not signing some headers, namely those in the `IGNORED_HEADERS` field.

Changing by inheritance is non-trivial and bound to break on upgrades:

- The call from [S3Base.executeAsync to Signer.signV4S3](https://github.com/minio/minio-java/blob/16841e5632086a261ecefe357ce077860beae4ea/api/src/main/java/io/minio/S3Base.java#L556C25-L556C25) would need to be changed. It has a lot of other logic that would be duplicated.
- Signing would need to be reimplemented as [Signer](https://github.com/minio/minio-java/blob/16841e5632086a261ecefe357ce077860beae4ea/api/src/main/java/io/minio/Signer.java#L40) does not have any way of specifying headers not to be signed from the outside.

I kindly ask you to reconsider the options below:

a) allowing to give a set of headers that should not be signed to the Minio client, which are forwarded to the Signer.
b) including the headers in the `IGNORED_HEADERS` field.

**Comment by kfcss** [comment]
@balamurugana bump
