### ISSUE TITLE
How to create a access key to an existing MinIO or AD/LDAP user in java.

### ISSUE THREAD

**Issue by Omico** [minio/minio-java#1498]
How to implement code equivalent to this in java?

```shell
mc admin user svcacct add
```

I am not familiar with GO. And I can not find the implementation of this API. Would you mind point out the specific line of this code in minio/minio, or providing REST docs for this API?

**Comment by balamurugana** [comment]
The specified API is not implemented yet. Feel free to send a PR

**Comment by Omico** [comment]
> The specified API is not implemented yet. Feel free to send a PR

Would you mind providing REST API docs?

**Comment by balamurugana** [comment]
> > The specified API is not implemented yet. Feel free to send a PR
> 
> Would you mind providing REST API docs?

No developer doc available, but you could see Go implementation at https://pkg.go.dev/github.com/minio/madmin-go#AdminClient.AddServiceAccount
