### ISSUE TITLE
Stream Object Upload

### ISSUE THREAD

**Issue by fengjicheng** [minio/minio-java#1501]
Dear Author：
                How to write object stream uploads in Minio. I've been searching for a long time.Can you give me some advice？
      
                 https://github.com/googleapis/java-storage/blob/main/samples/snippets/src/main/java/com/example/storage/object/StreamObjectUpload.java

**Comment by balamurugana** [comment]
What is streaming upload wrt S3 specifications?

**Comment by fengjicheng** [comment]
I don't know what wrt S3 specifications are. What I am doing now is downloading a large file through OKHTTP and uploading it to Minio. I want to start uploading while downloading.I don't want to download the file locally and then upload it.I see that minio client   can upload files through mini Client minio  . putObject (object). This doesn't seem to apply to me.

**Comment by balamurugana** [comment]
putObject API supports any stream compatible to InputStream. You would need to use this API.
