### ISSUE TITLE
Is there a method for Minio's Java client to reduce package size

### ISSUE THREAD

**Issue by Hans-Wu-cn** [minio/minio-java#1508]
Is there a method for Minio's Java client to reduce package size

**Comment by balamurugana** [comment]
What do you mean?

**Comment by Hans-Wu-cn** [comment]
> What do you mean?

I have developed a web server program with a packaging size of around 13MB. After introducing Minio, the jar file has expanded to 18MB. I am wondering if there is a way to reduce the size of Minio dependencies
