### ISSUE TITLE
file multipart upload

### ISSUE THREAD

**Issue by 888868** [minio/minio-java#1510]
Can the current version of Minio still achieve file sharding upload? What API should be used. I used createMultipartUpload to obtain the uploadId, and then used getPresignedObject Url to obtain the URL of each shard. I set different index identifiers for each URL, but after uploading the shard, I saw multiple versions of the file in Minio instead of the shard file. Then, I used listParts to query the shard length as 0

**Comment by balamurugana** [comment]
[putObject()](https://minio-java.min.io/io/minio/MinioAsyncClient.html#putObject-io.minio.PutObjectArgs-) automatically uploads with/without multipart based on [PutObjectArgs](https://minio-java.min.io/io/minio/PutObjectArgs.html)
