### ISSUE TITLE
Minio Client not working  FIPs mode

### ISSUE THREAD

**Issue by mmajor-devel** [minio/minio-java#1518]
I have developed a Java application that uses the Minio Client.

When FIPS mode is enable on a RHEL 8 operating system the application produces the following error:

java.security.InvalidKeyException
caused by sun.security.pkcs11.wrapper.PKCS11Exception: CKR_KEY_SIZE_RANGE.

**Comment by balamurugana** [comment]
Could you share full stacktrace? Please enable `MinioClient.traceOn()` and share the output.
