### ISSUE TITLE
How to set the Signature version to s3v2 in minio-java client

### ISSUE THREAD

**Issue by Taogang00** [minio/minio-java#1519]
I have to set the Signature version to s3v2, otherwise I will encounter some error problems. May I ask how I need to configure it? tks

Example :
```java
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>8.4.0</version>
        </dependency>
```
![image](https://github.com/minio/minio-java/assets/19925601/1aa61be7-3ecf-408d-8320-3f5a4c3aa999)

When I set the Signature Version of s3 browser to V2, everything works fine，If I choose the V4 version, an error will appear：
![image](https://github.com/minio/minio-java/assets/19925601/2a0a74c9-4ae0-43b8-a438-c32e8252ba22)

**Comment by balamurugana** [comment]
`minio-java` does not support Signature V2 and we don't have any plans to add it.
