### ISSUE TITLE
Add support for specifying port of custom endpoint in IamAwsProvider

### ISSUE THREAD

**Issue by jgolda** [minio/minio-java#1522]
Currently IamAwsProvider accepts providing a custom endpoint of IMDS service. It's great for testing, but in my opinion could be further improved by allowing the class'es client to provide a custom port as well. Currently in order to setup a local testing environment the user needs to set up a mock endpoint listening on port 80, which is sometimes not acceptable (eg. collides with other services).

Let me know if you're interested in such a feature. If so, i'll prepare a PR

**Comment by jgolda** [comment]
Not really, as the url provided via `customEndpoint` is later parsed and the url part is ignored, only scheme, hostname is used, eg in io.minio.credentials.IamAwsProvider#fetchImdsToken. 
If the user passes eg. http://localhost:8180 then minio client attempts to connect to http://localhost:80 (as 80 is default). There is no way around it

**Comment by balamurugana** [comment]
Feel free to send a fix WRT `customEndpoint` usage
