### ISSUE TITLE
Delete object from the bucket for which versioning is enabled

### ISSUE THREAD

**Issue by Hintic** [minio/minio-java#1525]
In the bucket with versioning enabled, I use `mc ilm --expire-delete-marker --noncurrent-expire-days 1 local/bucket` as the current lifecycle policy, which can realize that deleted objects are marked for deletion one day later. 
Now I want to implement that in this kind of bucket, as long as `delete` is called, the object will be marked immediately and cleaned up as soon as possible, can it be implemented?

**Comment by balamurugana** [comment]
You could write whatever you want on top of `minio-java`
