### ISSUE TITLE
Optimize performance for S3Escaper.encode

### ISSUE THREAD

**Issue by kzhsw** [minio/minio-java#1528]
I'm building some minio-based java app, and found out `S3Escaper.encode` and the `String.replaceAll` call inside it is one of the bottlenecks of the whole app after some profiling.
The optimized code is [here](https://github.com/kzhsw/minio-java-jmh/blob/4b2e33f4a7ac8995983191ff788ac66d0aa8034e/src/main/java/kzhsw/S3Escaper.java#L51).
The JMH benchmark result on github actions ci is [here](https://github.com/kzhsw/minio-java-jmh/actions/runs/7752407466/job/21141853765#step:5:98)

```
Benchmark                                    Mode  Cnt          Score          Error  Units
S3EscaperBenchmark.benchmarkEncode           avgt   10  106580200.431 ± 39231338.664  ns/op
S3EscaperBenchmark.benchmarkEncodeOptimized  avgt   10    6190071.878 ±    22742.019  ns/op
```

**Comment by balamurugana** [comment]
I wonder how this method affects overall performance including network/disk I/O. Please share your sample code here.

**Comment by kzhsw** [comment]
I'm using `MinioClient.getPresignedObjectUrl` for making presigned url for downloading some small images, so there would be many requests.

```java

final GetPresignedObjectUrlArgs.Builder builder =
        GetPresignedObjectUrlArgs.builder();

if (StringUtils.isNotEmpty(file.getRegionName())) {
    builder.region(file.getRegionName());
}
builder.bucket(file.getBucketName());
builder.object(file.getObjectPath());
if (StringUtils.isNotEmpty(file.getFileName())) {
    builder.extraQueryParams(Collections.singletonMap(
            "response-content-disposition",
            contentDisposition(file.getFileName(), attachment).toString()
    ));
}
final GetPresignedObjectUrlArgs args = builder
        .method(Method.GET)
        .expiry(Math.toIntExact(expireAfter.toMillis() / 1000))
        .build();

return client.getPresignedObjectUrl(args);
```

**Comment by balamurugana** [comment]
Make sense. Please send a PR.

**Comment by kzhsw** [comment]
> Make sense. Please send a PR.

It's here: https://github.com/minio/minio-java/pull/1529
