### ISSUE TITLE
Perfomace optimization using Java Zero Copy capability

### ISSUE THREAD

**Issue by konsultaner** [minio/minio-java#1530]
Hi I want to use this client in my java project to proxy a chunk upload of my netty based java server to a minio database and found several issues. 

The first issue might be related to #816 where someone found performance issues comparing to mc. Those performance issues may come from the fact the the `transferTo` method is not used. The underlying okhttp client uses it here:

https://github.com/square/okhttp/blob/02df2bbe05248028cf64ea87e312748f42570072/okhttp/src/main/kotlin/okhttp3/internal/cache2/FileOperator.kt#L72

Also a socket channel to socket channel transferTo would be awesome to be able to proxy downloads aswell.

The next problem is that there is no possibility to handle chunk uploads manually. I want to receive the uploadId myself and collect the ETAGs to be able to proxy my chunk uploads.

I would like to contribute to the client or maybe the repo owner wants to implement it? Any Idea where to start? I could also provide a netty based replacement for okhttp?

**Comment by balamurugana** [comment]
1. Please share your performance data along with your java code
2. You could use low level S3 APIs like https://minio-java.min.io/io/minio/S3Base.html#createMultipartUploadAsync-java.lang.String-java.lang.String-java.lang.String-com.google.common.collect.Multimap-com.google.common.collect.Multimap-, https://minio-java.min.io/io/minio/S3Base.html#uploadPartAsync-java.lang.String-java.lang.String-java.lang.String-java.lang.Object-long-java.lang.String-int-com.google.common.collect.Multimap-com.google.common.collect.Multimap- and  https://minio-java.min.io/io/minio/S3Base.html#completeMultipartUpload-java.lang.String-java.lang.String-java.lang.String-java.lang.String-io.minio.messages.Part:A-com.google.common.collect.Multimap-com.google.common.collect.Multimap-

**Comment by konsultaner** [comment]
>> The next problem is that there is no possibility to handle chunk uploads manually. I want to receive the uploadId myself and collect the ETAGs to be able to proxy my chunk uploads.
>
> You could use low level S3 APIs like [createMultipartUploadAsync()](https://minio-java.min.io/io/minio/S3Base.html#createMultipartUploadAsync-java.lang.String-java.lang.String-java.lang.String-com.google.common.collect.Multimap-com.google.common.collect.Multimap-), [uploadPartAsync()](https://minio-java.min.io/io/minio/S3Base.html#uploadPartAsync-java.lang.String-java.lang.String-java.lang.String-java.lang.Object-long-java.lang.String-int-com.google.common.collect.Multimap-com.google.common.collect.Multimap-) and [completeMultipartUploadAsync()](https://minio-java.min.io/io/minio/S3Base.html#completeMultipartUpload-java.lang.String-java.lang.String-java.lang.String-java.lang.String-io.minio.messages.Part:A-com.google.common.collect.Multimap-com.google.common.collect.Multimap-)

Thank you for your help with proxying the multipart upload using the low level API.

> Please share your performance data along with your java code

I haven't implemented any of your code. I generally use zero copy in my webserver implementation and would like to have it connecting to minio. Thats why I went through your code and saw how you manage file uploads. In my eyes this is not the way it should be done since this client loads all file data into the heap memory before passing it to the sockt. This is quite inefficient in my eyes. Using `transferTo` would reduce a lot of memory consumption and increase performance naturally.

This is a nice IBM article adressing this issue: https://developer.ibm.com/articles/j-zerocopy/

BUT! I might have missed out on something when going through your code in half an hour.

**Comment by balamurugana** [comment]
Yep. According to S3 specification, before sending the data to HTTP request body, we should write sha256sum or md5sum in the headers. This means the data for the body has to be kept in memory for checksum computation and writing to request body stream. This cannot be avoided.

**Comment by konsultaner** [comment]
@balamurugana I see the point, but one might already have the checksum and could provide them to the client.
