### ISSUE TITLE
Is it possible to add parameters such as `fake-endpoint` and `fake-port` for special network environments?

### ISSUE THREAD

**Issue by Semoz** [minio/minio-java#1531]
Private IP: 10.0.0.3
Public IP: 6.6.6.6
Service: Minio;Java Client
Port Mapping: 10.0.0.3:9000 -> 6.6.6.6:9000

For some security reasons, the firewall policy prohibits access when the exit IP and the server provide the same IP.
For example: server provides http://6.6.6.6:9000 service for the public network. Access through other public network addresses is normal, but access through the java client on 10.0.0.3 is prohibited.

When I use the `getPresignedObjectUrl` method, the Java client cannot access it.
I have tried to obtain the `getPresignedObjectUrl` address by using the intranet address http://10.0.0.3:9000, but the address is returned as an intranet address and cannot be used on the Internet.

I tried several methods:
1. Create a server with a new public IP for forwarding.
2. Invite the network administrator to go to Disney land, and ask him to change the firewall policy (failed).
3. Change the minio sdk, manually change 10.0.0.3 to 6.6.6.6 when signing (hard to upgrade).

Is there a better solution for me to choose from? Or add a parameter such as `fake-endpoint` and `fake-port` be added to modify the presignedUrl?

**Comment by balamurugana** [comment]
No.

You are generating pre-signed URL for one domain which cannot be changed. You should create the URL for your decided domain.
