### ISSUE TITLE
Add the userTags field to the Item.java

### ISSUE THREAD

**Issue by DonHoe** [minio/minio-java#1539]
[Item.java](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/messages/Item.java)
```java
  @Element(name = "UserTags", required = false)
  private String userTags;

  public String userTags() {
    return userTags;
  }
```
To receive the UserTags tag in the response.
![image](https://github.com/minio/minio-java/assets/7985073/cf90e61b-9e09-403f-ba2a-f4ba0c242269)

**Comment by balamurugana** [comment]
Feel free to send a PR
