### ISSUE TITLE
Need a Bundle SDK

### ISSUE THREAD

**Issue by DINGdeZHENZ** [minio/minio-java#1551]
would you mind package a Bundle of java SDK for avoiding  some annoying  dependency conflict
we can do this work by maven-shade-plugin,make a fat-jar,then we can say goodbye to error message,such as okio not found Exception etc
maybe...

**Comment by balamurugana** [comment]
We ship fat jar as well e.g. [minio-8.5.9-all.jar](https://repo1.maven.org/maven2/io/minio/minio/8.5.9/minio-8.5.9-all.jar) is available at https://repo1.maven.org/maven2/io/minio/minio/8.5.9/

If you are looking something else, feel free to send a PR
