### ISSUE TITLE
Java API - Client builder with session token

### ISSUE THREAD

**Issue by Dubkoslove** [minio/minio-java#1552]
Hello,

I would like to ask you, how to correctly create minIO client in Java using AssumeRoleWithWebIdentity service for generating temp credentials.  :

        OkHttpClient client = getOkHttpClientBuilder().build();
        RequestBody body = RequestBody.create("", null);

        Request request = new Request.Builder()
                .header("Content-Type", "application/x-www-form-urlencoded")
                .url(getMinIOHostApi() +
                        "?Action=AssumeRoleWithWebIdentity" +
                        "&Version=2011-06-15" +
                        "&DurationSeconds=86000" +
                        "&Role={admin:*}" +
                        "&WebIdentityToken=" + oauth_access_token
                )
                .post(body)
                .build();

        Response response = client.newCall(request).execute();

I managed to add the security/session token to the httpClient's header like:

    private MinioClient buildConnection(MinIOAuthSecrets secrets) {
        // Adds header with session token
        OkHttpClient okHttpClient = getOkHttpClientBuilder().addInterceptor(
                chain -> {
                    Request request = chain.request().newBuilder()
                            .addHeader("x-amz-security-token", secrets.sessionToken())
                            .build();
                    return chain.proceed(request);
                }
        ).build();
        return getMinIOBuilder()
                .endpoint(getMinIOHostApi())
                .credentials(secrets.accessKeyId(), secrets.secretAccessKey())
                .httpClient(okHttpClient)
                .build();
    }

However this was working well, until I had encountered with 403 Security token is invalid error, during generation of presigned URL. :

        String URL;
        MinioClient minioClient = minIOClientBuilder.build(token);
        try {
            URL = minioClient.getPresignedObjectUrl(
                    GetPresignedObjectUrlArgs.builder()
                            .method(Method.GET)
                            .bucket(bucketName)
                            .object(objectName)
                            .expiry(1, TimeUnit.DAYS)
                            .build()
            );
        } 

I could not find any documentation for Java API to include session token directly (Only for .Net, Python, JavaScript). Maybe I do something wrong. Could you please help me somehow ?

**Comment by balamurugana** [comment]
1. Refer [MinioClientWithWebIdentityProvider example](https://github.com/minio/minio-java/blob/master/examples/MinioClientWithWebIdentityProvider.java)
2. If you are managing you own way to fetch credentials, create custom provider and use it.
3. If you want to use access/secret keys with session token, use [StaticProvider](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/credentials/StaticProvider.java)
