### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by MaximKarabitsin** [minio/minio-java#1556]
When creating a service account, two encryption operations are performed (encrypt body and decrypt response). During these operations, an [object ](https://github.com/minio/minio-java/blob/8.5.10/adminapi/src/main/java/io/minio/admin/Crypto.java#L72) of 64 MB in size is allocated. [initMemory](https://github.com/bcgit/bc-java/blob/r1rv77/core/src/main/java/org/bouncycastle/crypto/generators/Argon2BytesGenerator.java#L147) produces an array of [objects](https://github.com/bcgit/bc-java/blob/r1rv77/core/src/main/java/org/bouncycastle/crypto/generators/Argon2BytesGenerator.java#L621) of size 65536. One object is an [array of longs](https://github.com/bcgit/bc-java/blob/r1rv77/core/src/main/java/org/bouncycastle/crypto/generators/Argon2BytesGenerator.java#L630) of size 128 (1 KiB)
It seems to me that this is redundant, since it requires the allocation of large resources for the application that uses this functionality quite often and in parallel. 
Judging by the [comment](https://github.com/minio/minio-java/blob/8.5.10/adminapi/src/main/java/io/minio/admin/Crypto.java#L68), the object should be allocated with 64 KiB, but in fact it is 64 MiB. 
My suggestion is to reduce the size or allow users to change this setting.

**Comment by balamurugana** [comment]
Feel free to send a PR. I am closing as of now.
