### ISSUE TITLE
Unable to download from Minio using java sdk if the object is written by Spark

### ISSUE THREAD

**Issue by ywzb** [minio/minio-java#1558]
What I'm doing

1. Use Spark (version 3.4.1) to write a CSV to Minio
2. Use Minio Java SDK (version 8.5.3) in my Java spring app to Read the CSV from Minio
Applications are deployed on K8s.

All credentials are set correctly and I can see the object in minio after the first step.
```
$ ls -l /data/minio/mybucket/somecsv/
total 20
drwxr-sr-x 2 minio root 4096 May 14 17:08 _SUCCESS
drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00000-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00001-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00002-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00003-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
```

However, when I tried to download this object, I got NoSuchKey error.
```
ErrorResponse(code = NoSuchKey, message = Object does not exist, bucketName = mybucket, objectName = somecsv, resource = /mybucket/somecsv, requestId = 17CF6A7029E8808C, hostId = ...)
request={method=HEAD, url=https://minio:9000/mybucket/somecsv, headers=Host: minio:9000
Accept-Encoding: identity
User-Agent: MinIO (Linux; amd64) minio-java/8.5.3
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20240514T171653Z
Authorization: ██
}
```
Initially I thought the Spark failed to save the file. So I tried reading the file from Spark after the write, and it succeeded.

With the SDK, if I use `listObjects` with `recursive=true`, I get
```
somecsv/_SUCCESS
somecsv/part-00000-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
somecsv/part-00001-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
somecsv/part-00002-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
somecsv/part-00003-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
```

It seems to me that Spark is saving the CSV as multiple objects in Minio, and it is able to somehow assemble them into one CSV. But Minio Java SDK is unable to recognize that. Is my understanding correct? What is the right way to download such an object?

**Comment by harshavardhana** [comment]
> $ ls -l /data/minio/mybucket/somecsv/
> total 20
> drwxr-sr-x 2 minio root 4096 May 14 17:08 _SUCCESS
> drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00000-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
> drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00001-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
> drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00002-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv
> drwxr-sr-x 3 minio root 4096 May 14 17:08 part-00003-91ea5d7c-d8e5-4328-8ffa-20e17de38f2b-c000.csv

Writing directly on the disk and letting MinIO read it back won't work. You need to ingest the data via MinIO.
