### ISSUE TITLE
io.minio.errors.InvalidResponseException: Non-XML response from server. Response code: 502, Content-Type: null, body: 

### ISSUE THREAD

**Issue by qiuhuanhen** [minio/minio-java#1563]
both  minioClient.bucketExists api and minioClient.putObject  report error msg : "io.minio.errors.InvalidResponseException: Non-XML response from server. Response code: 502, Content-Type: null, body: "  

![image](https://github.com/minio/minio-java/assets/55900765/a94ce7d3-e42d-4394-9b02-79e554459790)

it's my minioclient config:
minio:
  endpoint: http://192.168.207.130:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test

and it's normal when I open in browser  http://192.168.207.130:9000 , and login or create bucket / upload file can work normal.

**Comment by qiuhuanhen** [comment]
![image](https://github.com/minio/minio-java/assets/55900765/e7ee18c6-2841-4cd3-b04d-3980abedcce4)

**Comment by balamurugana** [comment]
Check your server setup WRT proxy/load balancer etc

**Comment by qiuhuanhen** [comment]
> Check your server setup WRT proxy/load balancer etc

thank you so much. It's cause by proxy. In my case, both run proxy app and System.setProperty("http.proxyHost", proxyHost) in springboot project  Application class , although I pause the proxy app,   forget to delete the code in application  class for testing
