### ISSUE TITLE
java: package io.minio.admin does not exist

### ISSUE THREAD

**Issue by amankumarchagti** [minio/minio-java#1567]
<img width="264" alt="image" src="https://github.com/minio/minio-java/assets/73024810/4e35ff4e-3a9e-4578-b8fa-567fc216a622">

although I have installed the minio java dependency already.
```
<dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>8.5.10</version>
</dependency>
```

**Comment by balamurugana** [comment]
You would need to use https://mvnrepository.com/artifact/io.minio/minio-admin.
