### ISSUE TITLE
Exception : unexpected end of stream when i used getObject() from minio 

### ISSUE THREAD

**Issue by nguyenhuudung111** [minio/minio-java#1575]
when i get object from minio server with file from 70mb -100mb this bug appear. I want to know how to fix this issue . I use java 8 and minIO 8.5.11 , okhttp 4.1.0

java.net.ProtocolException: unexpected end of stream
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:392)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:279)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:438)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)

**Comment by balamurugana** [comment]
If you are seeing intermittent failures, mostly you have network error due to proxy/load balancer/firewall etc. You would need to check and fix the setup accordingly.

**Comment by nguyenhuudung111** [comment]
> If you are seeing intermittent failures, mostly you have network error due to proxy/load balancer/firewall etc. You would need to check and fix the setup accordingly.

 it not intermittent failures . Sometime success , sometime failures

**Comment by Bouger-CN** [comment]
I have also encountered the same problem, which occurs when downloading multiple files simultaneously and there are large files inside. My application scenario is to read multiple files from Minio and generate compressed files.

java code:

```
 MinioClient client = getIntranetClient();
        for (int i = 0; i < objectKeyList.size(); i++) {
            GetObjectResponse subMinioResponse = client.getObject(GetObjectArgs.builder().bucket(minIoConfig.getBucket())
                    .object(objectKeyList.get(i)).build());
            if (Objects.isNull(subMinioResponse)) {
                continue;
            }
            srcFiles[i] = subMinioResponse;
            srcFileNames[i] = displayNameList.get(i);
        }
```
stream read 

```
for (int i = 0; i < srcFiles.length; i++) {
                out.putNextEntry(new ZipEntry(srcFileNames[i]));
                int len;
                BigDecimal downloadLength = BigDecimal.ZERO;
                GetObjectResponse srcFile = srcFiles[i];
                while ((len = srcFiles[i].read(buf)) != -1) {
                    downloadLength = downloadLength.add(new BigDecimal(len));
                    out.write(buf, 0, len);
                }
                out.closeEntry();
                srcFiles[i].close();
            }
```

Looking forward to receiving a solution
