### ISSUE TITLE
How to createMultipartUpload with minio 8.5.x？

### ISSUE THREAD

**Issue by kennard520** [minio/minio-java#1581]
In Minio 8.3,I can createMultipartUpload, But this api is not in 8.5.x, So after I migrate from 8.3.x to 8.5.x, How can I upload file in multipart file ?

**Comment by balamurugana** [comment]
@kennard520 You don't need to do anything special. [putobject() API](https://minio-java.min.io/io/minio/MinioAsyncClient.html#putObject-io.minio.PutObjectArgs-) uses regular/multipart upload automatically based on stream size. Refer https://minio-java.min.io/io/minio/PutObjectArgs.Builder.html#stream-java.io.InputStream-long-long-
