### ISSUE TITLE
Unable to download objects with double slashes

### ISSUE THREAD

**Issue by nicoloboschi** [minio/minio-java#1585]
I'm trying to download an object with double slash 
```
example//name.txt
```
but I always get `NoSuchKey`

It looks like double slash are trimmed here

https://github.com/minio/minio-java/blob/ef85db96a0ac02a201ccc3b5fdd7964f076e017a/api/src/main/java/io/minio/S3Escaper.java#L89-L108

If I use python botocore or the official AWS CLI, I'm able to download the file without issues.

I'm using minio 8.5.12

**Comment by balamurugana** [comment]
@nicoloboschi As `okhttp` doesn't support multiple slashes, it is not supported in `minio-java`.
