### ISSUE TITLE
Which version has abandoned the method of uploading and merging files in shards？

### ISSUE THREAD

**Issue by gongjlGit** [minio/minio-java#1591]
My version is 8.5.13，How do I merge files from each section when I implement breakpoint shard upload using the minioClient. putObject method? There is no explicit calling method, such as' perfectMultipartUpload '?

**Comment by balamurugana** [comment]
@gongjlGit `putObject` method automatically selects multipart-upload for given length. `putObjectArgs.Builder` comes with options to tweak the behavior. I am not able to understand. What is `perfectMultipartUpload`?

**Comment by gongjlGit** [comment]
Sorry, there was a paste error. Did the previous version have the 'createMultipartUpload' method that returns an ‘ObjectWriteResponse’?
It is used to merge shard files uploaded to the Minio server
