### ISSUE TITLE
minio multipart upload throws an exception, but sdk donot catch and throws it

### ISSUE THREAD

**Issue by goyjy** [minio/minio-java#1594]
【version】
minio version：RELEASE.2023-01-31T02-24-19Z
minio-java version：8.4.3

【description】
When I did a multipart upload, the multipart upload failed because the bucket's quota was exceeded, but the client did not catch the exception.

minio trace logs
![image](https://github.com/user-attachments/assets/4eed0f6d-c6b1-4043-bd1e-a4546a84fc67)

reason for error is "Bucket quota exceeded"

Looking at the source code, we found that when the multipart upload fails, the abortMultipartUploadAsync method needs to be executed, so the multipart upload error will not be thrown.
![image](https://github.com/user-attachments/assets/36659f61-13a9-4f08-b282-d6965e3ca4ca)

【expectation】
Error message for multipart upload failure can be thrown

**Comment by klauspost** [comment]
@balamurugana Server sent 400 on PutObjectPart. This was caught by the client, which then called AbortMultipartUpload.

It seems like successfully aborting swallows the original issue, right?

**Comment by goyjy** [comment]
> What error does the server throw to the client? If the server sends success, nothing can be done at client side.

The process is like this:
1、Java sdk upload object parts;
2、The minio server returned error code 400 because "Bucket quota exceeded";
3、Java sdk catch the server-side error and executes the abortMultipartUploadAsync method;
4、The abortMultipartUploadAsync method executes successfully and returns，But the "Bucket quota exceeded" error is not thrown upward.

When I call java sdk to do multipart upload, java sdk returns success. But in fact the object was not uploaded successfully
