### ISSUE TITLE
okhttp-3.14.9.jar

### ISSUE THREAD

**Issue by dragoncdj** [minio/minio-java#1596]
springboot 使用minio 8.5.13报okhttp3.14.9错误
![image](https://github.com/user-attachments/assets/df81825f-c34f-4767-a719-44150e6a6e8a)

**Comment by dragoncdj** [comment]
![image](https://github.com/user-attachments/assets/9de9fb08-26bd-4662-90cc-844dda347d67)

**Comment by balamurugana** [comment]
You have to use okhttp `4.12.0`  not ` 3.14.9`. If other libraries depends on okhttp `3.14.9`, you should fix the conflict.
