### ISSUE TITLE
Cannot convert to credential when adding service account 

### ISSUE THREAD

**Issue by lenzDocthread** [minio/minio-java#1600]
https://github.com/minio/minio-java/blame/8de1be7d0de3e3dd52da9f7f1564eff6bf85db64/adminapi/src/main/java/io/minio/admin/MinioAdminClient.java#L642

Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.minio.credentials.Credentials` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

 at [Source: (byte[])"{"credentials":{"accessKey":"ea318406ca924113bd81","secretKey":"cb37e90761844efda3cd58d70b4fbde3","expiration":"1970-01-01T00:00:00Z"}}"; line: 1, column: 17] (through reference chain: io.minio.admin.AddServiceAccountResp["credentials"])
 
 
 the method works and it adds the access token to it, however when it tries to respond with credential an error occurs which is shown at above.

**Comment by lenzDocthread** [comment]
> Please check your credential provider i.e. the service gives you temporary credentials. It seems it returns invalid credential JSON.

Hello where can I check my credential provider if that is the case?

**Comment by balamurugana** [comment]
Check how you created `MinioAdminClient` with credential provider.

**Comment by lenzDocthread** [comment]
@Configuration
public class MinioAdminConfig {

    @Value("${minio.access.key}")
    private String accessKey;

    @Value("${minio.access.secret}")
    private String secretKey;

    @Value("${minio.url}")
    private String minioUrl;

    @Bean
    @Primary
    public MinioAdminClient minioAdminClient() {
        return MinioAdminClient.builder()
                .credentials(accessKey, secretKey)
                .endpoint(minioUrl)
                .build();
    }


}



minio:
  access:
    key: LmNLz1RZwm0ubB0px693
    secret: 3TCGtsloPnzKMPPi184MOc9DCab8Vb4A9aXmBsXF
  url: http://localhost:9000
  
  
  it was created this way i used a different access key so i can create another access key seperately this access key currently has no policy on it 
  
  
![image](https://github.com/user-attachments/assets/9d27eddd-c31b-473d-a236-c3547b9e511e)
