### ISSUE TITLE
The listObjects method of io.minio.MinioClient is unable to retrieve data.

### ISSUE THREAD

**Issue by zhuhui6-lang** [minio/minio-java#1601]
Hello, my previous MinIO version was RELEASE.2021-06-17T00-10-46Z.hotfix.e6c50dc4c. After upgrading to RELEASE.2024-09-22T00-33-43Z, I found that the listObjects method returns no data. So, I upgraded the MinIO dependency version from 7.1.0 to 8.x, but I still can't retrieve the data.
![image](https://github.com/user-attachments/assets/2c256544-6a98-4f67-ad17-e1b38a4d59d0)
![image](https://github.com/user-attachments/assets/eec6ea8f-53ce-461b-9a10-d257349f27e4)
![image](https://github.com/user-attachments/assets/1b5ff5ef-7ca2-4812-bded-5829d2fe35b8)

**Comment by balamurugana** [comment]
@zhuhui6-lang enable `traceOn()` and share the output.

**Comment by zhuhui6-lang** [comment]
> @zhuhui6-lang enable `traceOn()` and share the output.

Sir, the output file from MinIO has been privately sent to you. Please check.

**Comment by zhuhui6-lang** [comment]
> The output is legit as you don't have any object in the prefix

Actually, there are objects. For the bucket poseidon-s3-prod, the prefix / (which is %2F) does contain objects.
![image](https://github.com/user-attachments/assets/743dee32-4d28-444f-a3ea-e19135c6676d)

**Comment by balamurugana** [comment]
There is nothing starts with `/`

**Comment by zhuhui6-lang** [comment]
> There is nothing starts with `/`

Yes, as you mentioned, I also think the issue lies here. I noticed that in the older versions of MinIO, there is this / character.
![image](https://github.com/user-attachments/assets/3bb39c91-4693-4f2e-8e26-6df9322203a4)

**Comment by balamurugana** [comment]
Open the issue with minio server

**Comment by zhuhui6-lang** [comment]
> Open the issue with minio server

Thanks.
