### ISSUE TITLE
ForbiddenException should be thrown instead of boolean as false for bucketExists() on unauthenticated private bucket

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#223]
~~~
scala> var client = Client.getClient("https://s3.amazonaws.com")
scala> client.bucketExists("ferenginar")
res2: Boolean = false

scala>
~~~

**Comment by fkautz** [comment]
This was brought up earlier in design and we had decided to take this approach instead. So, this is pretty consistent across all libraries. We could change it.

**Comment by harshavardhana** [comment]
> This was brought up earlier in design and we had decided to take this approach instead. So, this is pretty consistent across all libraries. We could change it.

The reason was that perhaps i was looking at minio-js wasn't replying in the same manner.  

It is okay for a successful request to go through and we receive a 404 to reply back as "false" but not 403 or any other errors. Since those are regarded as something we don't expect, that is why the would fall in Exception category.
