### ISSUE TITLE
Minior change - we have to expose getPartialObject() method like other libraries

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#226]

**Comment by fkautz** [comment]
Libraries that support overloading simply use getObject. Those that don't use getPartialObject as a workaround. .NET library also uses overloading.

**Comment by harshavardhana** [comment]
> Libraries that support overloading simply use getObject. Those that don't use getPartialObject as a workaround. .NET library also uses overloading.

It would make it simpler if all libraries do the same, overloading works for now. Closing this

**Comment by fkautz** [comment]
We could make this change, now is the time to do it :)
