### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by notnoopci** [minio/minio-java#346]
Looks like there has been significant and backward-compatibility breaking changes in the API since release 0.2.6, cut on Nov 25, 2015.  What's the timeline for the next release?

**Comment by harshavardhana** [comment]
> Looks like there has been significant and backward-compatibility breaking changes in the API since release 0.2.6, cut on Nov 25, 2015. What's the timeline for the next release?

We are currently concentrating our efforts towards 'minio' server, we will be making a release subsequently. Current master is stable with no more drastic API changes and is release candidate ready.

**Comment by notnoopci** [comment]
Thanks for the fast response!  I can deploy an RC build to an internal Maven repo in that case - wish there is a more recent version in Maven Central.

**Comment by harshavardhana** [comment]
> Thanks for the fast response! I can deploy an RC build to an internal Maven repo in that case - wish there is a more recent version in Maven Central.

I will see if we can steer this up as RC and upload to make.  I will keep you posted

**Comment by harshavardhana** [comment]
> Thanks for the fast response! I can deploy an RC build to an internal Maven repo in that case - wish there is a more recent version in Maven Central.

https://github.com/minio/minio-java/releases/tag/1.0.0 - We have made a 1.0.0 release. Should be available in maven shortly. 

Fixed by https://github.com/minio/minio-java/commit/9dfdf15a815043d0d02420d31204cd027b5bd832

**Comment by harshavardhana** [comment]
Closing.. minio-java released.
