### ISSUE TITLE
Java async client for minio

### ISSUE THREAD

**Issue by meggarr** [minio/minio-java#397]
Would you please add **async** support in Java API for all operations, including _buckets_, _objects_, and all other client operations?

Note: **Future** is the Java's way to do async, compared to NodeJS's callback handler. If it can get a **Future** in the implementations, the API will be compatible with the JDK9 flow in the future, and also compatible with existing Java async libraries, e.g. Vert.X, RxJava etc.

**Comment by balamurugana** [comment]
@meggarr is this https://github.com/balamurugana/minio-java/commit/bdf052316f4ffa5604fb9d46e24502aebfef26d2 patch good enough to solve this issue?

**Comment by meggarr** [comment]
@balamurugana I think this is only a simple wrapper around synchronous call with thread pool. It is good that we have API that returns `Future`, but on the other hand, can it do the **true async** in a lower level? E.g. without providing a thread pool, can it register a listener/handler that can be called when it has a result?

If it cannot provide a way in listener/handler, I think the user can simply create his/her utility to execute the code in thread pool and then notify a handler. For example, in Vert.X, it has its way to wrap this blocking/sync code, e.g. [HazelcastAsyncMap::put](https://github.com/vert-x3/vertx-hazelcast/blob/master/src/main/java/io/vertx/spi/cluster/hazelcast/impl/HazelcastAsyncMap.java#L53-56). In this case, we don't need a new API, the existing blocking/sync API is already there.

BTW, can I ask what is the implementation inside the MinioClient ? Is it HTTP with `minio` protocol implementation? Since I saw several HTTP words in the source code.

If `minio`'s driver is based on HTTP, how about we divide the `minio`'s driver into two parts? 1. The protocol parser; 2. The transport. The protocol parser is much more standalone, and the transport is more about using HTTP client to talk to server.. Because many framework has its own HTTP client framework, e.g. Netty has its HTTP client, Apache HTTP has its http client, Vert.X also has a HTTP client (based on Netty) which is **true async**. If you provide a `minio` protocol parser, I'd rather write my own version Minio client using any of these HTTP Client.

Just my two cents.

**Comment by GarimaKapoor** [comment]
@balamurugana is this issue resolved?

**Comment by balamurugana** [comment]
@GarimaKapoor No. We haven't made the conclusion to made all calls using async.  This requires major rewrite of minio-java.

**Comment by deekoder** [comment]
We have to discuss this and decide what we want to do about this. Assigning it to myself till then.

**Comment by TopSpoofer** [comment]
The asynchronous API is strongly recommended！

**Comment by balamurugana** [comment]
Archived.  Will reopen on more community attraction.

**Comment by abhishek-27** [comment]
Can someone confirm if minio support async s3 upload now ?

**Comment by balamurugana** [comment]
No. You would achieve by writing your own layer by inheriting `MinioClient`.

**Comment by pschichtel** [comment]
For those of you still looking for an async client:

Unless you need somthing minio specific, you can use the AWS SDK 2, like so:

```kotlin
@Bean
fun s3Client(
    @Value("\${minio.host}") host: String,
    @Value("\${minio.port}") port: Int,
    credentials: MinioCredentials,
): S3AsyncClient {
    val s3conf = S3Configuration.builder()
        .pathStyleAccessEnabled(true)
        .build()
    val s3Credentials = AwsBasicCredentials
        .create(credentials.accessKey, credentials.secretKey)

    return S3AsyncClient.builder()
        .credentialsProvider { s3Credentials }
        .serviceConfiguration(s3conf)
        .endpointOverride(URI.create("http://${host}:${port}/"))
        .region(Region.EU_CENTRAL_1) // should not really matter, but is required
        .build()
}
```

and then e.g. this in a kotlin coroutine:

```kotlin
val request = PutObjectRequest.builder()
    .bucket(bucketName)
    .contentType(contentType)
    .key("folder/$fileName")
    .build()
s3Client.putObject(request, filePath).await()
```

This is inspired by [minio's documentation about using the AWS SDK](https://docs.min.io/docs/java-client-quickstart-guide.html), but the documentation is for the old SDK.

**Comment by davinkevin** [comment]
I would like to use the minio driver in my reactor based application, but without async support, I have to fallback to aws sdk v2 sadly.

Nowadays, reactive is almost everywhere, even database provides reactive driver to avoid blocking thread, so I think this is a really interesting feature to consider in minio.

**Comment by mmadoo** [comment]
I have created an extension to minioClient to allow async upload.
For this, I use an executor and add the method
`public OutputStream newOutputStream(PutObjectArgs args, OnCloseCallback callback);`
where `OnCloseCallback `provide is created with `Runnable onClosed, Consumer<Exception> onCloseFailure`.

The principal is:
- main thread writes to the OutputStream, 
- the outputStream contains a  byte[] buf, this buffer can extends until PutObjectArgs.partSize()
- once this limit reached, 
- it creates a multipart upload (if not already created)
- buf is copied to a tmp buffer and passed to executor to be sent as part
- on OutputStream.close(), if it is full async, actual close is done in executor else it is done in same thread
- actual close is: if no part, file is sent with a single PUT
- else, remaining data is sent and thread is blocked until all response are received and S3Base.completeMultipartUpload() is called
- then OnCloseCallback is called

This code is currently integrated in our products but if such extension may be accepted by mainteners, I could do a Pull Request.

**Comment by harshavardhana** [comment]
> This code is currently integrated in our products but if such extension may be accepted by mainteners, I could do a Pull Request.

We can only make such judgements if we see a pull request @mmadoo - feel free to send it.
