### ISSUE TITLE
Does the java client support local caching? 

### ISSUE THREAD

**Issue by danyaljj** [minio/minio-java#406]
Suppose I download a file from remote server once. Does it cache it locally? 
In other words, the second time that I read it, does it read from the server again (slow), or it reads it from cache locally (fast)?

**Comment by balamurugana** [comment]
minio-java doesn't cache downloads.  However minio-java has one version of [getObject()](http://minio.github.io/minio-java/io/minio/MinioClient.html#getObject-java.lang.String-java.lang.String-java.lang.String-) which downloads to a given file.  Repeated `getObject()` to the file will not download again unless S3 server has a change.

This way we could achieve the caching.

**Comment by danyaljj** [comment]
This is cool!
