### ISSUE TITLE
Show progress when putObject?

### ISSUE THREAD

**Issue by danyaljj** [minio/minio-java#408]
Is there a way to print out the upload progress when using `putObject`? Like for big files I would very much prefer to see how fast it is being uploaded.

**Comment by balamurugana** [comment]
Currently there is no support in put/get Object progressing status.

**Comment by danyaljj** [comment]
Any simple way to do it? I can help too...

**Comment by harshavardhana** [comment]
> Any simple way to do it? I can help too...

We are going to add async support to Java API which would provide this feature.  Currently there is no simple way to do it.

**Comment by GarimaKapoor** [comment]
@balamurugana what is the current status of this issue?

**Comment by balamurugana** [comment]
@GarimaKapoor Currently none. We would need to discuss, evaluate and prioritize this issue

**Comment by deekoder** [comment]
This is an example : https://github.com/minio/minio-java/blob/master/examples/PutObjectProgressBar.java

**Comment by danyaljj** [comment]
@deekoder Sorry about the confusion. I'm talking about console progress bar. Something like this:
https://github.com/raszi/java-progressbar
Is there a way to know how much of the upload/download is done?

**Comment by harshavardhana** [comment]
> @deekoder Sorry about the confusion. I'm talking about console progress bar. Something like this:
> https://github.com/raszi/java-progressbar
> Is there a way to know how much of the upload/download is done?

@danyaljj console progress bar can be implemented in the same manner as the example shows. Do you want us to write that as well?

**Comment by danyaljj** [comment]
> @danyaljj console progress bar can be implemented in the same manner as the example shows. 

Not sure how its done the same way. Any sample codes for that? Thanks!

**Comment by harshavardhana** [comment]
> Not sure how its done the same way. Any sample codes for that? Thanks!

Will write an example in a bit @danyaljj .

**Comment by harshavardhana** [comment]
@danyaljj here is the example of console based progress bar - https://github.com/minio/minio-java/pull/550

**Comment by danyaljj** [comment]
Thanks @harshavardhana. Could you show usage for `getObject` too?

**Comment by danyaljj** [comment]
Or give me ideas on how to do this ...

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-java/pull/554 here we go @danyaljj
