### ISSUE TITLE
docs: README.md docs regarding building fileUploader.java is wrong

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#434]
#### Compile FileUploader

```sh

$ javac -cp "minio-2.0.1.jar"  FileUploader.java

```

#### Run FileUploader

```sh

$ java -cp "minio-2.0.1.jar" FileUploader.java
/tmp/asiaphotos.zip is successfully uploaded as asiaphotos.zip in asiatrip bucket.

$  mc ls play/asiatrip/
[2016-06-02 18:10:29 PDT]  82KiB asiaphotos.zip

```

`minio-2.0.1.jar` should `minio-2.0.1-all.jar` which carries all the dependencies as well.  Above example doesn't compile otherwise.

**Comment by harshavardhana** [comment]
Also `java -cp` doesn't work. should be 

```
$ java -cp "minio-2.0.1.jar:." FileUploader
```

NOTE: we shouldn't provide the `.java` again.

**Comment by koolhead17** [comment]
Can be fixed via https://github.com/minio/minio-java/pull/460

**Comment by harshavardhana** [comment]
This is fixed in master.
