### ISSUE TITLE
How to set custom metadata to Object as part of putObject call

### ISSUE THREAD

**Issue by sachinwalia2k8** [minio/minio-java#450]
AWS S3 provides an API to set custom ObjectMetadata using which you can set custom properties such as etag / cache control headers. Is it possible to have ability to set such metadata via MinioClient API?

**Comment by harshavardhana** [comment]
> AWS S3 provides an API to set custom ObjectMetadata using which you can set custom properties such as etag / cache control headers. Is it possible to have ability to set such metadata via MinioClient API?

Only minio-go currently supports it as part of 'responseHeaders' in PresignedGetObject() API.

**Comment by sachinwalia2k8** [comment]
@balamurugana any plan to support this. This would be a very helpful feature.

**Comment by balamurugana** [comment]
@sachinwalia2k8 No immediate plan.

**Comment by harshavardhana** [comment]
minio-go now supports PutObjectWithMetadata() - this can be now implemented with minio-java.

**Comment by cliffcotino** [comment]
This would be very useful feature for us as well. The ObjectStat object would probably also need a way to be able to read the metadata back when performing a statObject call.

**Comment by balamurugana** [comment]
@cliffcotino thanks for showing interest on this feature.  I will add it ASAP.

**Comment by cliffcotino** [comment]
Cool! Thanks for the quick response.

**Comment by sachinwalia2k8** [comment]
@balamurugana will this be added to go sdk as well?

**Comment by harshavardhana** [comment]
Go SDK already has this @sachinwalia2k8

**Comment by nitisht** [comment]
@sachinwalia2k8 will it be possible to get in touch with you regarding couple of questions on your tusd deployment

**Comment by marcadella** [comment]
Why did you guys add additional metadata param to upload object from InputStream ONLY???
