### ISSUE TITLE
MinioClient Threadsafety question

### ISSUE THREAD

**Issue by sachinwalia2k8** [minio/minio-java#451]
I am wondering if MinoClient is threadsafe and can be setup as Singleton object in Spring / Guice or any other DI container? Most of the time storage endpoints may not change so much so there isn't a lot of state information in the class.

**Comment by balamurugana** [comment]
Yes.There is a functional test which uses MinioClient object for multi-threaded put https://github.com/minio/minio-java/blob/master/test/FunctionalTest.java#L625

**Comment by sachinwalia2k8** [comment]
OK. thanks @balamurugana. I am marking it closed.
