### ISSUE TITLE
Missing setBucketPolicy/getBucketPolicy from latest jar 2.0.1

### ISSUE THREAD

**Issue by popopome** [minio/minio-java#455]
I tried to call setBucketPolicy() with jar 2.0.1 version 
but the funcs are not available somehow.

The last build was done at Jul 15, but when I looked up MinioClient.java file
the set/getBucketPolicy were added on Jul. 22.

Can somebody update maven repository with latest jar build?

Thanks.

**Comment by harshavardhana** [comment]
> I tried to call setBucketPolicy() with jar 2.0.1 version 
> but the funcs are not available somehow.
> 
> The last build was done at Jul 15, but when I looked up MinioClient.java file
> the set/getBucketPolicy were added on Jul. 22.
> 
> Can somebody update maven repository with latest jar build?
> 
> Thanks.

We haven't made a release yet @popopome

**Comment by harshavardhana** [comment]
Release 2.0.2 should be available in maven shortly. Closing this bug.
