### ISSUE TITLE
2.0.2 presignedGetObject broken, invalid signature

### ISSUE THREAD

**Issue by IsNull** [minio/minio-java#456]
The 2.0.2 version now properly lists the objects without any issue. However, when I generate a pre-signed URL I always receive a 404 from minio server, saying `SignatureDoesNotMatch`.

If I switch back to 2.0.1 the presigned url works so it appears to be a regression of `2.0.2`.

Edit:

* It is reproducible with the empty txts from last test.
* It is reproducible with a single empty object `obj.txt` in the bucket

**Comment by harshavardhana** [comment]
@balamurugana ping

**Comment by balamurugana** [comment]
Checking this issue now.

**Comment by balamurugana** [comment]
@IsNull My bad! I missed adding query parameter encoding for presigning.  I fixed it in https://github.com/minio/minio-java/issues/458

**Comment by IsNull** [comment]
@harshavardhana Any chance for a hot-fix release? For now I have to use `2.0.1` to at least get a bit of a working system.

Btw: You currently advertise version `2.0.2` as the current one. With this version the `presigned-` methods are completely broken. New users or unsuspecting users upgrading to 2.0.2 will have a bad experience - I would actually advertise `2.0.1` until you have this bug fixed in a upcoming release.

That all aside, I am very impressed how fast you all react and fix bugs - thank you for this and keep up the good work 👍

**Comment by balamurugana** [comment]
@IsNull Thanks for your appreciation. We are going to make 2.0.3 release ASAP.

**Comment by harshavardhana** [comment]
> @harshavardhana Any chance for a hot-fix release? For now I have to use 2.0.1 to at least get a bit of a working system.

Hot-fix has been uploaded, 2.0.3 artifacts will be available shortly. Thanks for your patience @IsNull
