### ISSUE TITLE
How to get region/public URL of uploaded objects to Amazon S3

### ISSUE THREAD

**Issue by sachinwalia2k8** [minio/minio-java#462]
For publicly accessible buckets on S3 is there any way we can retrieve the URL. I believe if ObjectStat returns regionName then public URL can be derived as: 

`https://s3-<RegionName>.amazonaws.com/<BucketName>/<ObjectKey>
`

**Comment by balamurugana** [comment]
For any anonymous request region `"us-east-1"` should be used.  This is automatically taken care inside minio-java. You could use the library normally without given access/secret keys.

**Comment by balamurugana** [comment]
@sachinwalia2k8 please close the issue if you are good with the answer

**Comment by sachinwalia2k8** [comment]
Thanks this is helpful.
