### ISSUE TITLE
Implement CopyObject API

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#463]
For reference visit https://docs.minio.io/docs/golang-client-api-reference#CopyObject

**Comment by NitishT** [comment]
Hey @harshavardhana mind if I give this a shot?

**Comment by harshavardhana** [comment]
> Hey @harshavardhana mind if I give this a shot?

Feel free to @NitishT - Thanks

**Comment by NitishT** [comment]
> Feel free to @NitishT - Thanks

Cool. Thanks!

**Comment by balamurugana** [comment]
@NitishT :+1:   If you have any trouble in current code base, feel free to ask me.

**Comment by NitishT** [comment]
Sure! Will do that @balamurugana

**Comment by NitishT** [comment]
Hi @balamurugana I have code & JUnit tests done, but I wanted to add a Functional test as well. 

I see the file FunctionalTest.java but not sure how to run those tests. Can you please tell me how to run those in eclipse?

**Comment by balamurugana** [comment]
@NitishT Currently functional tests are run by hand using `javac` and `java` commands.  I am trying to add a new task for functional test which can be run on requirement like `./gradlew functionaltest`

**Comment by balamurugana** [comment]
@NitishT FYI https://github.com/minio/minio-java/pull/473

**Comment by GarimaKapoor** [comment]
@NitishT what is the status of the issue?

**Comment by NitishT** [comment]
There were a few enhancements/review comments to be addressed. I will take it up this week @GarimaKapoor
