### ISSUE TITLE
Content Type not updating on S3 - Java Client Lib

### ISSUE THREAD

**Issue by janiparthiv** [minio/minio-java#464]
Hi,

I am using java client library of minio. I am trying to upload files using putObject method but i noticed that when i pass all the details along with content type. It is not changing content type of file on s3. It is always remain as binary/octet-steam. Because of this when i try to access any file in browser it directly go to download instead of displaying it on html page or display as image. 

Can you please fix this asap. 

Thank you,

Regard,
Jani Parthiv

**Comment by harshavardhana** [comment]
Thanks for opening the bug @janiparthiv - we have a fix. Should be merged shortly.
