### ISSUE TITLE
Implement ListenBucketNotification .

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#468]
Refer minio-go for current API.

**Comment by deekoder** [comment]
Please catch up the java sdk with this. All other sdks have this implemented already.

**Comment by NitishT** [comment]
ETA 20 April

**Comment by kannappanr** [comment]
Will reopen this issue and implement if there is interest in the community.

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio-java/pull/727

**Comment by vadmeste** [comment]
Can we close this ?

**Comment by kannappanr** [comment]
Closing this issue as this has been fixed by #727
