### ISSUE TITLE
Implement ListBucketPolicies

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#469]
Refer minio-go for API level documentation.

**Comment by christopher-fredregill** [comment]
I took a stab at this one; please see https://github.com/minio/minio-java/pull/627

As a side note - the functional tests are breathtakingly slow, running against https://play.minio.io:9000. Running against a local Docker container endpoint, the entire suite was able to finish in under a minute. I'd be happy to add/implement a feature to optionally run the tests against a container, if desired.

**Comment by harshavardhana** [comment]
Merged and fixed in #627
