### ISSUE TITLE
Error in methods "SetBucketPolicy" and "GetBucketPolicy" of Java client api

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-java#470]
Hi, I meet some problems, my test codes are below:
```
minioClient.makeBucket("test");
BucketPolicy policy1 = minioClient.getBucketPolicy("test", "");
System.out.println(policy1);  // It's "none".
minioClient.setBucketPolicy("test", "", BucketPolicy.ReadOnly);
BucketPolicy policy2 = minioClient.getBucketPolicy("test", ""); // Where error happens.
System.out.println(policy2);
minioClient.removeBucket("test");
```

When I set a policy to a bucket, error happened if i call the method "getBucketPolicy" to the bucket.
The phenomenon is same if i call the method "setBucketPolicy" to the bucket again.

The exception messages is below: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: **Expected a string but was BEGIN_ARRAY at line 1 column 242 path $.Statement[1].Condition..**
```
HttpResponse response = executeGet(bucketName, null, null, queryParamMap);
BucketAccessPolicy policy = gson.fromJson(response.body().charStream(), BucketAccessPolicy.class);
response.body().close();
```

**Comment by harshavardhana** [comment]
Cloned from https://github.com/minio/minio/issues/2886 reported by @zhanjiejun

**Comment by balamurugana** [comment]
Closed by https://github.com/minio/minio-java/pull/475

**Comment by zhanjiejun** [comment]
Is the bug fixed in the next release version?

**Comment by balamurugana** [comment]
@zhanjiejun Its fixed in the upstream master. You can directly compile and use the source. Since enums are breaking backward compatibility, we would be making new release with major number increased.

**Comment by yuanfeiz** [comment]
Is there any update on releasing it to Maven?

**Comment by balamurugana** [comment]
@yuanfeiz We are working on it

**Comment by harshavardhana** [comment]
> Is there any update on releasing it to Maven?

Yep just pushed 2.0.5 should be available shortly.

**Comment by balamurugana** [comment]
@harshavardhana As some of the calls are breaking backward compatibility. the release version needs to be 3.0.  `build.gradle` has already set accordingly unless manual override.

**Comment by harshavardhana** [comment]
> @harshavardhana As some of the calls are breaking backward compatibility. the release version needs to be 3.0. build.gradle has already set accordingly unless manual override.

which calls are breaking @balamurugana ?

**Comment by yuanfeiz** [comment]
> Yep just pushed 2.0.5 should be available shortly.

Cool, is this fix included?

**Comment by harshavardhana** [comment]
> Cool, is this fix included?

Yes this is included.. it should be 3.0.0 not 2.0.5
