### ISSUE TITLE
Does minio support signature v2 for Swift3?

### ISSUE THREAD

**Issue by porunov** [minio/minio-java#471]
I am using OpenStack Swift with Swift3 middleware which is designed for S3 API. The problem is that it only supports v2 signature. Can we configure minio-java to use signature v2 of S3? I tried to use it but it shows me a 403 error.

**Comment by harshavardhana** [comment]
> I am using OpenStack Swift with Swift3 middleware which is designed for S3 API. The problem is that it only supports v2 signature. Can we configure minio-java to use signature v2 of S3? I tried to use it but it shows me a 403 error.

minio-java doesn't support Signature V2.  Only [minio-go](https://github.com/minio/minio-go) implements signature v2 for applications like [mc](https://github.com/minio/mc)

**Comment by porunov** [comment]
I see. Thank you for your response
