### ISSUE TITLE
presigned urls start time issue (url not yet valid)

### ISSUE THREAD

**Issue by IsNull** [minio/minio-java#487]
If minio is not running on the same server as the minio-java client, even minimal clock drifts / time differences between the servers can cause the presigned urls to be invalid.

Event though both server are NTP synchronised, they have some minimal differences. I think this is something which is quite common.

I do understand that the basic design of this is Amazons fault (they use a start-date and a duration instead of an expiry date), but we need some kind of workaround.

* The simplest solution would be to just provide an additional start-date param in the API so this can be set manually by code.
* Or probably just set the start date = now() - 1 day, and the duration += 1 day by default. (It should be no harm if a link is valid in the past)

**Comment by harshavardhana** [comment]
> If minio is not running on the same server as the minio-java client, even minimal clock drifts / time differences between the servers can cause the presigned urls to be invalid.
> 
> Event though both server are NTP synchronised, they have some minimal differences. I think this is something which is quite common.
> 
> I do understand that the basic design of this is Amazons fault (they use a start-date and a duration instead of an expiry date), but we need some kind of workaround.
> 
> The simplest solution would be to just provide an additional start-date param in the API so this can be set manually by code.
> Or probably just set the start date = now() - 1 day, and the duration += 1 day by default. (It should be no harm if a link is valid in the past)

Even if the skewed time happens 15 minutes is allowed by the API with proper date headers. With NTP synchronized there is no reason that they can drift away. 

Can you provide a sample code which reproduces this?  can you reproduce this against play.minio.io:9000 ?

**Comment by IsNull** [comment]
>Even if the skewed time happens 15 minutes is allowed by the API with proper date headers. With NTP synchronized there is no reason that they can drift away in such drastic ways.

Ok that is great to hear, 15 minutes should be more than enough.

I have to investigate further and will report back.

**Comment by harshavardhana** [comment]
> Ok that is great to hear, 15 minutes should be more than enough.
> 
> I have to investigate further and will report back.

Closing this for now @IsNull - please re-open if this issue is seen again.
