### ISSUE TITLE
A method to check if object exists?

### ISSUE THREAD

**Issue by zhanjiejun** [minio/minio-java#493]
Hi ^^
i found there is no method in Java minioclient provided to check if object exists or not

**Comment by harshavardhana** [comment]
https://docs.minio.io/docs/java-client-api-reference#statObject @zhanjiejun ?

**Comment by balamurugana** [comment]
@zhanjiejun  Amazon S3 does not have a direct call to check object existent like bucket.  However we could use [head object call](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html) to check object existent.

In minio-java You could use [statObject](https://docs.minio.io/docs/java-client-api-reference#statObject) call as @harshavardhana mentioned above.

**Comment by zhanjiejun** [comment]
i saw it before, but i didn't see descriptions in javadoc to show what will return if object is not exist , will it return null or throw a exception?

**Comment by balamurugana** [comment]
> i saw it before, but i didn't see descriptions in javadoc to show what will return if object is not exist , will it return null or throw a exception?

You could use something like below
```java
boolean objectFound = false;
try {
    // Check whether "myobject" exists
    minioClient.statObject("mybucket", "myobject");
    objectFound = true
} catch(ErrorResponseException e) {
    if (e.errorResponse().errorCode() != ErrorCode.NO_SUCH_KEY) {
        throw e
    }
}

if objectFound {
    // object is found
} else {
   // object is not found
}
```

> 
> maybe i should try it at first
> 
> anyway , thank you very much for replying so timely

Let me know do we need to have handy method like `MinioClient.objectExists()`
