### ISSUE TITLE
Add MinioClient.getUrl

### ISSUE THREAD

**Issue by PSanetra** [minio/minio-java#502]
The MinioClient class only provides the method presignedGetObject which returns a signed url for an object.

It would be useful to have a getUrl method to get a simple url for public files.

The AWS SDK has such a method: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#getUrl-java.lang.String-java.lang.String-

**Comment by balamurugana** [comment]
@PSanetra [AmazonS3Client.getUrl()](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#getUrl-java.lang.String-java.lang.String-) identifies bucket/key has public read permissions using Canned ACL and returns [URL object](http://docs.oracle.com/javase/6/docs/api/java/net/URL.html?is-external=true).

Currently minio-java supports bucket policy not canned ACL.  We could add a new  `MinioClient.getUrl()` method to return `URL` object with bucket policy.

Is this solution good for you?

**Comment by PSanetra** [comment]
@balamurugana I think it does not matter if the public read permissions are granted by canned ACL or bucket policies or if the object isn't accessible at all. MinioClient.getUrl() should return a url in any case.

The aws sdk documentation states 

> If the object identified by the given bucket and key has public read permissions (ex: CannedAccessControlList.PublicRead), then this URL can be directly accessed to retrieve the object's data.

The method returns a url for the object even if the object is not accessible by this url, because of missing permissions. But if the object is public readable you may retrieve it by this url.

**Comment by balamurugana** [comment]
@PSanetra The feature under review at https://github.com/minio/minio-java/pull/507
