### ISSUE TITLE
create folder does not work

### ISSUE THREAD

**Issue by thomas-logisch** [minio/minio-java#514]
I have used the example PutObject.java to create a folder inside a bucket in the test account as well as on an AWS account like

`minioClient.putObject("my-bucketname", "myfolder/my-objectname", bais, bais.available(), "application/octet-stream");`

but I get in both cases the error:

`The request signature we calculated does not match the signature you provided. Check your key and signing method.,`

just using "my-objectname" without the folder name works fine and using the AWS CLI it works,too...

hope you can help!
thanks a lot!

**Comment by balamurugana** [comment]
@thomas-logisch It works with current master and should work in v3.0.2
Could you share what version of minio-java you used?

**Comment by thomas-logisch** [comment]
Oh sorry! Yes, you are right! 
I was using the latest minio-java (3.0-DEV) from maven repository because I thought I have to use minio-java instead of just minio 3.0.2.
Thanks for clearing!

**Comment by balamurugana** [comment]
@thomas-logisch  If things are working as expected in the latest release, please close this issue.

**Comment by harshavardhana** [comment]
Closing as solved by release.
