### ISSUE TITLE
`getObject` seems not to observe key case sensitivity

### ISSUE THREAD

**Issue by marcinwyszynski** [minio/minio-java#520]
I just had a case where using the Minio Java library I requested key `Mattermost/Extensions/Array+RemoveObject.swift@9dc2b931f92aa08ecd0bb95432b0af6f`, but received the content of `Mattermost/extensions/Array+RemoveObject.swift@9dc2b931f92aa08ecd0bb95432b0af6f`

Both paths are valid, but case sensitivity matters.

I took a look through the code but haven't spotted any obvious reasons for such behaviour. I tried to reproduce that using `mc` CLI but this one works just fine.

**Comment by balamurugana** [comment]
@marcinwyszynski what is the version of minio-java you used?

**Comment by marcinwyszynski** [comment]
3.0.2

**Comment by balamurugana** [comment]
Below code works fine in latest master and minio server
```
import io.minio.MinioClient;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public class Check {
  public static void main(String[] args) throws Exception {
    MinioClient minioClient = new MinioClient("http://127.0.0.1:9000", "minio", "minio123");

    minioClient.putObject("mybucket",
                          "Mattermost/Extensions/Array+RemoveObject.swift@9dc2b931f92aa08ecd0bb95432b0af6f",
                          "/tmp/hello");
    minioClient.putObject("mybucket",
                          "Mattermost/extensions/Array+RemoveObject.swift@9dc2b931f92aa08ecd0bb95432b0af6f",
                          "/tmp/world");

    InputStream stream = null;
    byte[] buf = new byte[16384];
    int bytesRead;

    stream = minioClient.getObject("mybucket",
                                   "Mattermost/Extensions/Array+RemoveObject.swift@9dc2b931f92aa08ecd0bb95432b0af6f");
    while ((bytesRead = stream.read(buf, 0, buf.length)) >= 0) {
      System.out.println(new String(buf, 0, bytesRead, StandardCharsets.UTF_8));
    }
    stream.close();

    stream = minioClient.getObject("mybucket",
                                   "Mattermost/extensions/Array+RemoveObject.swift@9dc2b931f92aa08ecd0bb95432b0af6f");
    while ((bytesRead = stream.read(buf, 0, buf.length)) >= 0) {
      System.out.println(new String(buf, 0, bytesRead, StandardCharsets.UTF_8));
    }
    stream.close();
  }
}
```

Checking with Amazon S3 now.

**Comment by marcinwyszynski** [comment]
I actually used Minio server. I'll update the library version to 3.0.3 and see what gives.

**Comment by balamurugana** [comment]
@marcinwyszynski the above example works fine with minio-java v3.0.2.  Can you check at your end?

If you use minio server, please provide minio version and setup info.  There could be minio server issue.

**Comment by marcinwyszynski** [comment]
![minio_browser](https://cloud.githubusercontent.com/assets/571786/22376136/19913492-e4ad-11e6-9817-e58c8640a195.png)

**Comment by marcinwyszynski** [comment]
@balamurugana I just want to make sure the upgrade does not affect data integrity?

**Comment by harshavardhana** [comment]
It doesn't @marcinwyszynski

**Comment by harshavardhana** [comment]
@marcinwyszynski were you able to validate with latest minio-java and server releases?

**Comment by marcinwyszynski** [comment]
@harshavardhana I haven't seen the issue since I upgraded minio server.

**Comment by harshavardhana** [comment]
Thanks for letting us know @marcinwyszynski . Closing

**Comment by bmizerany** [comment]
I'm seeing this in latest:

```
minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: devel go1.23-4605dfaf76 Fri Mar 15 18:30:58 2024 +0000 X:rangefunc darwin/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
```

I am unable to get a test failure getting an object using the Minio client against Minio (version above) running locally to 404 if I request the object with different casing that the actual key.

**Comment by bmizerany** [comment]
To reproduce:

```
; minio --version
minio version DEVELOPMENT.GOGET (commit-id=DEVELOPMENT.GOGET)
Runtime: devel go1.23-4605dfaf76 Fri Mar 15 18:30:58 2024 +0000 X:rangefunc darwin/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
; cat x.go 
package main

import (
	"context"
	"strings"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	mc, err := minio.New("localhost:9000", &minio.Options{
		Secure: false,
		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
	})
	if err != nil {
		panic(err)
	}

	ctx := context.Background()
	mc.MakeBucket(ctx, "testbucket", minio.MakeBucketOptions{})
	mc.PutObject(
		ctx,
		"testbucket",
		"testobject",
		strings.NewReader("x"),
		1,
		minio.PutObjectOptions{},
	)

	_, err = mc.GetObject(ctx, "testbucket", "testObject", minio.GetObjectOptions{})
	if err == nil {
		panic("expected not found!!!!")
	}

	println("all is right")
}
; 
```

**Comment by harshavardhana** [comment]
> func main() {
> 	mc, err := minio.New("localhost:9000", &minio.Options{
> 		Secure: false,
> 		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	ctx := context.Background()
> 	mc.MakeBucket(ctx, "testbucket", minio.MakeBucketOptions{})
> 	mc.PutObject(
> 		ctx,
> 		"testbucket",
> 		"testobject",
> 		strings.NewReader("x"),
> 		1,
> 		minio.PutObjectOptions{},
> 	)
> 
> 	_, err = mc.GetObject(ctx, "testbucket", "testObject", minio.GetObjectOptions{})
> 	if err == nil {
> 		panic("expected not found!!!!")
> 	}

object names are case sensitive.
