### ISSUE TITLE
Connection leak when using splitIterator()?

### ISSUE THREAD

**Issue by Erwyn** [minio/minio-java#529]
Hello,

I'm encountering an issue with the minio java library.

Here is the code I'm running:

```
StreamSupport.stream(client.listObjects("someBucket").spliterator(), false)
                .filter()....
                .collect()...
```

And I get this error message: `[warn] c.s.o.OkHttpClient - A connection to http://minio.service.dev:9000/ was leaked. Did you forget to close a response body?`

**Comment by balamurugana** [comment]
@Erwyn Please add minio-java version you used.

**Comment by Erwyn** [comment]
sure:   "io.minio" % "minio" % "3.0.3",

**Comment by harshavardhana** [comment]
Can you paste your entire code @Erwyn ?

**Comment by Erwyn** [comment]
```
        MinioClient client = clientFactory.getClient();

        Optional<Result<Item>> lastFileKey = StreamSupport.stream(client.listObjects(configurationHelper.getMinioPimImportBucket()).spliterator(), false)
                .filter(entry -> {
                    try {
                        return !entry.get().isDir();
                    } catch (Exception exception) {
                        throw new RuntimeException(exception);
                    }
                })
                .filter(entry -> {
                    try {
                        return StringUtils.containsIgnoreCase(entry.get().objectName(), channel);
                    } catch (Exception exception) {
                        throw new RuntimeException(exception);
                    }
                })
                .max((entry1, entry2) -> {
                    try {
                        return entry1.get().lastModified().compareTo(entry2.get().lastModified());
                    } catch (Exception exception) {
                        throw new RuntimeException(exception);
                    }
                });

        if (! lastFileKey.isPresent()) {
            throw new Exception("Unable to find the last inserted file");
        }

        return lastFileKey.get().get().objectName();

```

**Comment by Erwyn** [comment]
Sorry guys when pasting It I discovered the source of the problem. Just before the end of the gist I was doing a : `        client.getObject(configurationHelper.getMinioPimImportBucket(), lastFileKey.get().get().objectName());
`
Now that I removed it there is no leak anymore. Now, could you explain me, it's because the InputStream coming out of this method is never closed?

Moreover, regarding something I have later in my code, that means that closing the InputStreamReader will close the contained StreamReader as well?

Regards,
Martin

**Comment by balamurugana** [comment]
> Sorry guys when pasting It I discovered the source of the problem. Just before the end of the gist I was doing a : client.getObject(configurationHelper.getMinioPimImportBucket(), lastFileKey.get().get().objectName());
> Now that I removed it there is no leak anymore. Now, could you explain me, it's because the InputStream coming out of this method is never closed?
> 

Returned `InputStream` of `getObject()` needs to be closed by the consumer.


> Moreover, regarding something I have later in my code, that means that closing the InputStreamReader will close the contained StreamReader as well?

Top level `close()` should call `close()` of underneath contained/child object.  But you could check respective docs whether this applicable.

@Erwyn If this issue is not correct, you could close it.

**Comment by Erwyn** [comment]
@balamurugana Thank you very much! I'm closing the issue. Sorry for the trouble, this was completely my fault.

**Comment by balamurugana** [comment]
@Erwyn No problem
