### ISSUE TITLE
Add the ability to add additional upload parameters to a putObject and fPutObject

### ISSUE THREAD

**Issue by PsyTae** [minio/minio-java#530]
Our company uses extra parameters when uploading files to the s3 such as the `Metadata: { someKey : 'STRING_VALUE' }` object.  It would be nice to be able to add additional parameters as AWS-SDK does.  as referenced [Here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).

**Comment by PsyTae** [comment]
wrong repository.

**Comment by harshavardhana** [comment]
Closing as duplicate of #450
