### ISSUE TITLE
Support encryption for GetObject() and PutObject()

### ISSUE THREAD

**Issue by NitishT** [minio/minio-java#536]
Minio server supports the header required. The SDK needs to support client side encryption and decryption.

**Comment by deekoder** [comment]
Is there a bug on the server that this one depends on.

**Comment by harshavardhana** [comment]
> Is there a bug on the server that this one depends on.

There is no server side changed needed for this. Its purely a client enhancement issue.

**Comment by NitishT** [comment]
ETA 15 April
