### ISSUE TITLE
client: [feature] Support proxy configuration.

### ISSUE THREAD

**Issue by mescalitox** [minio/minio-java#540]
add a proxy configuration to the minio client

**Comment by harshavardhana** [comment]
https://github.com/MarkusBernhardt/proxy-vole/ - This can be achieved by simply doing 

```java
import com.github.markusbernhardt.proxy.ProxySearch;
import java.net.ProxySelector;

public class XDF {
  public static void main(String[] args) {
    ProxySearch x = ProxySearch.getDefaultProxySearch();
    ProxySelector.setDefault(x.getProxySelector());
  }
}
```

OkHTTP honors this - nothing needs to be done by minio-java end here.

**Comment by nitisht** [comment]
@mescalitox closing this as working as intended. Feel free to re-open if there are any issues
