### ISSUE TITLE
listObjectsV2 causes endless loop > 1000 items

### ISSUE THREAD

**Issue by IsNull** [minio/minio-java#578]
Using the new (default) listObjectsV2 to list objects causes an endless loop when there are more than 1000 items returned by the server and _recursive_ is set to `true`. The iterator will list the first 1000 items over and over again.

I guess there is some error in the continuation token logic in the java client.

To reproduce, create 1001 items in a bucket and use the simplistic code below to list them:
```java
    private static void testEndlessLoop(){

        MinioClient minioClient = null;
        try {
            minioClient = new MinioClient(
                    "http://myminio.lan:9000",
                    accessKey,
                    accessSecret);


            Iterable<Result<Item>> iterable = minioClient.listObjects(
                    "mybucket",
                    "some/prefix/",
                    true,
                    false);  // if set to true it works, using V1
            

            iterable.forEach(o -> {
                try {
                    System.out.println(o.get().objectName());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

If you have trouble reproducing it on your end let me know.

**Versions**
`minio-java 3.0.4`
`minio  RELEASE.2017-05-05T01-14-51Z `

**Comment by harshavardhana** [comment]
Have you tried with mc does that work ?

**Comment by vadmeste** [comment]
I was able to reproduce this. I can take it.

**Comment by IsNull** [comment]
@harshavardhana any chance of a new release which contains this fix? While the problem is not really an issue for me (as I switched back to the v1 api), all new users have a non working default configuration as V2 has been made the default.

**Comment by harshavardhana** [comment]
> @harshavardhana any chance of a new release which contains this fix? While the problem is not really an issue for me (as I switched back to the v1 api), all new users have a non working default configuration as V2 has been made the default.

Sure we will make a new release soon @IsNull - thanks for getting back to us.

**Comment by klingtnet** [comment]
This is also an issue for the latest `minio-go`.
