### ISSUE TITLE
Make MinioClient.httpClient extensible

### ISSUE THREAD

**Issue by balamurugana** [minio/minio-java#589]
Refer the actual issue filed at https://github.com/minio/minio/issues/4707

Currently `MinioClient.httpClient` field is `private` which limits of customization with interceptor.  To enable this feature, either one of following can be done
1. make `httpClient` field `protected`
2. have a method to accept interceptor
3. have a method to accept `OkHttpClient` which replaces existing `httpClient`

**Comment by balamurugana** [comment]
@malejpavouk My choice is option 3.  Let me know if it works for you.

**Comment by malejpavouk** [comment]
Ok, thanks. Works perfectly for me

**Comment by balamurugana** [comment]
@malejpavouk there is a change. A new constructor is introduced to accept custom http client than a method.

**Comment by malejpavouk** [comment]
Thanks!
