### ISSUE TITLE
Allow presigned DELETE url's

### ISSUE THREAD

**Issue by ganzah** [minio/minio-java#605]
Currently, the Java client does not support the generation of presigned URL's for deleting a file, only for PUT, POST and GET operations. 

In a scenario with a javascript frontend app and a java backend service, the service may choose to let frontend handle file operations directly with the minio server by issuing presigned URLs for upload and download. However, there is currently no way to let the frontend handle file deletions. 

It would be nice to have a presignedDeleteObject or a generic presignedRequest method to help support this scenario.

**Comment by harshavardhana** [comment]
This request is similar to the request PR https://github.com/minio/minio-go/pull/770
