### ISSUE TITLE
Suppressed: java.lang.ClassNotFoundException: java.nio.file.Paths (Paths and Files)

### ISSUE THREAD

**Issue by WaseemSafarifone** [minio/minio-java#608]
I am trying to upload the Image, but I am stuck with this headache issue. The **Path** and the **File** class is not found in the library, it crashes always in the section of _**MinioClient.java 
Path filePath = Paths.get(fileName);**_
    if (!Files.isRegularFile(filePath)) 

The server and the Bucket name is already established and working fine. 

FATAL EXCEPTION: Smack-Cached Executor 1 (0)
                  Process: com.safarifone.waafi, PID: 6725
                  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                      at io.minio.MinioClient.putObject(MinioClient.java:2983)
                      at io.minio.MinioClient.putObject(MinioClient.java:3038)
                    ..........
                   ## **Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList**
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at io.minio.MinioClient.putObject(MinioClient.java:2983) 
                      at io.minio.MinioClient.putObject(MinioClient.java:3038) 
                      ..............
                      at java.lang.Thread.run(Thread.java:818) 
                  	**### Suppressed: java.lang.ClassNotFoundException: java.nio.file.Paths**
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 11 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by balamurugana** [comment]
Could you share your java version? You would need to have java 1.8

**Comment by harshavardhana** [comment]
Are you trying minio-java library on Mobile platforms? @WaseemSafarifone can you provide more details with examples and operating system details?

**Comment by WaseemSafarifone** [comment]
@balamurugana I am using Java 8 with version jdk1.8.0_121. @harshavardhana Yes trying mino-java library on Mobile platforms for Android.

**Comment by WaseemSafarifone** [comment]
I am implementing the same example as shown in the main. With bucket existence it works pretty good, but when I try to do 
            **// Upload the image file to the bucket with putObject
            minioClient.putObject(bucketName, fileName, filePath);**
The exception raises as I have question out. @harshavardhana

**Comment by balamurugana** [comment]
It seems you have a setup problem.  Please refer https://github.com/deeplearning4j/deeplearning4j/issues/3261 and https://github.com/dizitart/nitrite-database/issues/4

**Comment by WaseemSafarifone** [comment]
@balamurugana I didn't get the deeplearning4j you have prefered for this type of error. Deeplearning4j is for CPUs and GPUs I think so. For the 2nd option I am already using the same he describe but didn't solve that problem. 
Can you please tell me that, is this Java library working perfectly on Mobile devices?

**Comment by agibsonccc** [comment]
Hey folks: it generally should work on android fine. http://deeplearning4j.org/android
I only found this because of google alerts..but it wouldn't hurt to try to ask help from us rather than guessing on your own. You're welcome to join our live chat if you have questions: https://gitter.im/deeplearning4j/deeplearning4j

**Comment by balamurugana** [comment]
@WaseemSafarifone the reference issues are how similar things happened and what could be a possible solution.

From my understanding Android blacklists some classes like `nio`.  I guess you would need to enable in your setup.

As I don't have experience in Android, I couldn't able to give exact steps.

**Comment by WaseemSafarifone** [comment]
@balamurugana I just change my mind and I use Volley library to upload the picture on the requested slot of Minio Server. Before this I was trying Minio Java sdk but didn't succeed because of the problem I have mentioned. Thanks for your rapid response.
