### ISSUE TITLE
mint fails for copyobject with metadata against gateways

### ISSUE THREAD

**Issue by poornas** [minio/minio-java#614]
The copyobject test fails on azure and gcs - expected for Azure but not so for GCS. Needs to be investigated.

Output log is also not showing up in json format - need the release version of minio-java to be updated.

Test: copyObject(String bucketName, String objectName, String destBucketName,CopyConditions copyConditions, Map<String, String> metadata) replace object metadata

GCS and Azure error log identical as below:
java.lang.Exception: [FAILED] Test: copyObject(String bucketName, String objectName, String destBucketName, CopyConditions copyConditions, Map<String, String> metadata)
	at FunctionalTest.copyObject_test8(FunctionalTest.java:1427)
	at FunctionalTest.runTests(FunctionalTest.java:1652)
	at FunctionalTest.main(FunctionalTest.java:1717)

Mint image built from  commit 158108152fc86c52d5543995e0e7634bf1b6da74
Minio version:
Version: 2017-09-25T21:57:17Z
Release-Tag: RELEASE.2017-09-25T21-57-17Z
Commit-ID: d3eb5815d9951fdb82d0134b7651368bab71d72e

**Comment by kannappanr** [comment]
This also failed with gateway connected to aws. Here is the failure log

{"name":"minio-java","function":"copyObject(String bucketName, String objectName, String destBucketName, CopyConditions copyConditions, Map<String, String> metadata)","duration":3375,"status":"FAIL","error":"java.lang.Exception: content type differs. expected: application/javascript, got: application/octet-stream >>> [FunctionalTest.copyObject_test8(FunctionalTest.java:1964), FunctionalTest.runTests(FunctionalTest.java:2396), FunctionalTest.main(FunctionalTest.java:2476)]"}

**Comment by deekoder** [comment]
It also happens on S3 gateway

**Comment by poornas** [comment]
This is a problem with the copyobject_test8 itself. customcontenttype is being set as application/javascript and it is asserting a check for application/octetstream. Nothing to do with the gateway

**Comment by harshavardhana** [comment]
> This is a problem with the copyobject_test8 itself. customcontenttype is being set as application/javascript and it is asserting a check for application/octetstream. Nothing to do with the gateway

Quite surprising that this doesn't fail with FS and Erasure Code :-)

**Comment by poornas** [comment]
ok, :(  missed that the assertion is against object in destination bucket.

**Comment by harshavardhana** [comment]
> ok, :( missed that the assertion is against object in destination bucket.

:gun:

**Comment by balamurugana** [comment]
Not minio-java issue.
