### ISSUE TITLE
How to get custom meta data that save using putObject method ?

### ISSUE THREAD

**Issue by Prasanthmv** [minio/minio-java#624]
Hi,
   i have checked the put object method for saving the custom meta data along with file upload . Is there any other way to save custom meta data . Also how can i retrieve this . not found one with getObject and statObject method . please suggest a solution for this .

My example is given below
            
           ` Map<String, String> headerMap = new HashMap();
            headerMap.put("x-amz-meta-name", "pmv3");
            headerMap.put("x-amz-meta-size", "1025");
            
            minioClient.putObject("test1", "pmv3",
            stream,stream.available(),headerMap);           
            ObjectStat objectStat = minioClient.statObject("test1", "pmv3");      
            
            System.out.println("objectStat "+objectStat);`

 Output doesnt contain the headerMap values . Please suggest the way to find this .

**Comment by balamurugana** [comment]
@Prasanthmv it seems a bug in minio-java doesn't return headers.  Checking that.

**Comment by balamurugana** [comment]
@Prasanthmv I have submitted a PR https://github.com/minio/minio-java/pull/625 which fixes the issue.  Could you confirm whether it works for you?
