### ISSUE TITLE
Contributors Guide needs more detailed instructions

### ISSUE THREAD

**Issue by christopher-fredregill** [minio/minio-java#630]
It appears that there are some undocumented requirements for outside contributions which really should be captured in the Contributors Guide. A couple quick examples of things that would be nice to list out concretely in the guide:

* commit messages - there appear to be some standard commit message templates for various sorts of changes (`api: <blah>`, `test: <blah>`, ... ), but these aren't concretely listed anywhere in the guide. To facilitate contributions, any expectations along these lines really ought to be documented.

* test coverage - there are both unit and e2e tests in the project; as a would-be contributor, it should be clear to me which level of coverage is necessary for a given feature/bug fix/etc. Some quick statement to clarify expectations on this would be helpful.

It might be nice to reference a Java style guide for the project, as well; every org seems to have a different idea of what quality code looks like, so some sort of reference for the standard in use here would also be helpful, as I've seen in other projects.

**Comment by balamurugana** [comment]
>     commit messages - there appear to be some standard commit message templates for various sorts of changes (api: <blah>, test: <blah>, ... ), but these aren't concretely listed anywhere in the guide. To facilitate contributions, any expectations along these lines really ought to be documented.
> 

As you identified the style from existing commit logs, its most commonly used style.  Sometimes (rarely) we deviate from this.  There is no hard rule.


>     test coverage - there are both unit and e2e tests in the project; as a would-be contributor, it should be clear to me which level of coverage is necessary for a given feature/bug fix/etc. Some quick statement to clarify expectations on this would be helpful.
> 

Functional tests are primary for testing .  The tests are API point of view and each parameter has to be tested separately in its own test method.  Existing unit tests are not very useful.  A cleanup is required on this.

Again there is no hard rule.  Most of the cases adding functional/unit tests are not required unless new API is added.

> It might be nice to reference a Java style guide for the project, as well; every org seems to have a different idea of what quality code looks like, so some sort of reference for the standard in use here would also be helpful, as I've seen in other projects.

We follow Google coding style.  I believe developer understands the existing style and does changes.  `./gradlew build` takes care of the check automatically.  Similarly travis/appveyor CI do the check also.

**Comment by balamurugana** [comment]
Reopen if its not answered
