### ISSUE TITLE
Functional tests run slowly against https://play.minio.io:9000 endpoint

### ISSUE THREAD

**Issue by christopher-fredregill** [minio/minio-java#631]
Unless there's something specific we need to prove by running the tests against the https://play.minio.io:9000 endpoint, it might be nice to just run up a local Docker container to use as the endpoint for the functional tests. There are Gradle plugins that could be used to help facilitate this. This could even be rigged up in Travis CI, such that when builds run, the functional tests run against a Docker container local to the Travis VM's environment, which is totally under the CI system's control, rather than having to contend with external influences or actions of other users on https://play.minio.io:9000, which might lead to fragile/less idempotent tests.

Of course, there could always be a default/fallback option to run against https://play.minio.io:9000, if a user doesn't want to _have_ to run Docker to run the functional tests locally, but it seems like there's some room to improve on the testing strategy here.

**Comment by harshavardhana** [comment]
For the most part play.minio.io is used by default for our CI tests since the server is is located closer to us we do not have this problem. 

If you wish to run it locally it is also possible that is why it is possible to override this as well, so i don't see a problem with current approach.

**Comment by balamurugana** [comment]
You can run functional test like `./gradlew -PendPoint=<http://HOST:PORT> -PaccessKey=<MYUSER> -PsecretKey=<MYPASSWORD> runFunctionalTest`.  Its not necessary to run against [play](https://play.minio.io:9000).

For developer easiness, [play](https://play.minio.io:9000) is used as default.  Note that this SDK works with any S3 server supporting signature v4.  Its up to the developer how to run functional test.

However travis/appveyor CI run functional test with `play` for every PR change.

If you feel this information is missing, feel free to add this into `CONTRIBUTING.md`

**Comment by ebozduman** [comment]
@christopher-fredregill 
Please let us know if the above information/response is satisfactory for you.

**Comment by christopher-fredregill** [comment]
Closing. Thanks @ebozduman
