### ISSUE TITLE
 Problem occur while i am trying to get input stream some time its working fine but some time it give me the error and Some time it give me the minio connection time.

### ISSUE THREAD

**Issue by arunpal-kiwi** [minio/minio-java#635]
Hi i am using minio 3.0.8 . its working fine for upload file in java .But it give me a error while i am trying to download a file

error occured
ErrorResponse(code=NoSuchKey, message=The specified key does not exist., bucketName=null, objectName=null, resource=/resourse-server/284/health/1509086845373.doc, requestId=3L137, hostId=3L137)
request={method=GET, url=http://host:port/bucketName/284/health/1509086845373.doc, headers=Range: bytes=0-
Host: hostname:portnumber
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20171028T063134Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20171028/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=REDACTED
}
response={code=404, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-07-24T18-27-35Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14F1A834C5D82B02
Date: Sat, 28 Oct 2017 06:31:34 GMT
Transfer-Encoding: chunked
}

java code : 
MinioClient minioClient = new MinioClient("minio.server.url","minio.access.key, "minio.secret.key");
minioClient.setTimeout(30000, 30000, 30000);
response.setContentType("application/octet-stream");
String disHeader = "Attachment";
response.setHeader("Content-Disposition", disHeader);
String headerKey = "Content-Disposition";
String headerValue = String.format("attachment; filename=\"%s\"", "fileName()");
response.setHeader(headerKey, headerValue);
OutputStream outStream  = response.getOutputStream();

InputStream inputStream = minioClient.getObject("minio.bucket.name","Objectname");

byte[] in = new byte[64];
/*int count =0;*/
int read;
while ((read = inputStream.read(in)) != -1) {
byte[] output = cipher.update(in, 0, read);
if (output != null)
outStream.write(output);
}
byte[] output = cipher.doFinal();
					if (output != null)
						outStream.write(output);
					inputStream.close();
					outStream.flush();
					outStream.close();
1. Problem occur while i am trying to get input stream some time its working fine but some time it give me the error
2 Some time it give me the minio connection time

**Comment by balamurugana** [comment]
I see you have a problem in putting an object where it returns success wrongly.  Could you share more information about how put object is done?
* exact error message at client and server for put object
* what SDK you use to upload and its version?
* what is minio server version? (run `minio version` to paste the information here)
* I see you use client side encryption. Add more information about that.

**Comment by arunpal-kiwi** [comment]
For putting an Object i have used following code 
MinioClient minioClient = new MinioClient("serverUrl", "accesskey, secretkey");
boolean isExist = minioClient.bucketExists("bucket");
if (!isExist) {
 minioClient.makeBucket("bucketName");
}
minioClient.putObject("bucketName", "objectName", "fileName");
String fileUrl = minioClient.presignedGetObject("bucketName", objectName);

i am getting Minio connection time out exception very frequently 

Please do needfull

**Comment by balamurugana** [comment]
@arunpal-kiwi Please share the detail I asked in above comment.

**Comment by balamurugana** [comment]
Reopen if necessary information is available.
