### ISSUE TITLE
Any way to confirm object exist or not?

### ISSUE THREAD

**Issue by laudukang** [minio/minio-java#639]
I have a use case to comfirm a object exist in bucket whether or not, and I can finish the case through the following ways:

1. MinioClient#statObject, method will throw exception if object not exist, so I can know the object is not exist in minio server

2. MinioClient#getObject, method will throw exception if object not exist

Is there a better way that I can ensure a object exist in minio server whether or not?

**Comment by harshavardhana** [comment]
What you explained is the most idiomatic way.  What exactly are you looking for ?

**Comment by laudukang** [comment]
@harshavardhana Sorry, I have updated the issue.

**Comment by balamurugana** [comment]
@laudukang You would need to do like below
```java
boolean found = false;
try {
  minioClient.statObject("my-bucketname", "my-objectname");
  found = true;
} catch (ErrorResponseException e) {
  if (e.errorResponse().errorCode() != ErrorCode.NO_SUCH_OBJECT)) {
    throw e;
  }

if (found) {
  // Do things when object is found
} else {
  // Do things when object is not found
}

**Comment by kannappanr** [comment]
@laudukang Please close the issue, if the above reply is what you are looking for.

**Comment by vmyrsky** [comment]
This works a bit better.

    catch (ErrorResponseException e) {
      ErrorCode code = e.errorResponse().errorCode();
      if (code == ErrorCode.NO_SUCH_KEY || code == ErrorCode.NO_SUCH_OBJECT) {
        // Not found
      } else {
        throw e;
      }
    }

**Comment by negarnegma** [comment]
what about a folder? it throws a NO SUCH KEY exception too!

**Comment by vishrantgupta** [comment]
@balamurugana I guess there is a delete marker, and instead of just returning true, we should check for a delete marker.

```
objectStats.IsDeleteMarker == false
```

**Comment by tabiStein** [comment]
Hello MinIO devs! After searching for the correct way to check if a MinIO object exists, I stumbled across this thread. @balamurugana suggested the following:
```
try {
  minioClient.statObject("my-bucketname", "my-objectname");
  found = true;
} catch (ErrorResponseException e) {
  if (e.errorResponse().errorCode() != ErrorCode.NO_SUCH_OBJECT)) {
    throw e;
  }
}
```
However, in the latest version of MinIO (or more specifically, since release 8.0.0) the ErrorCode enum has been deleted. (See PR https://github.com/minio/minio-java/pull/1028 ). 
Is there a convenient and clean way to check the error codes without hardcoding them in my application?

Thanks!! - Tabi

**Comment by balamurugana** [comment]
It is same logic like below
```java
try {
  StatObjectResponse stat = minioClient.statObject(StatObjectArgs.builder().bucket("my-bucketname").object("my-objectname").build());
  found = true;
} catch (ErrorResponseException e) {
  if (e.response().code() != "NoSuchKey")) {
    throw e;
  }
}
```

Refer https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html for error codes. If you want enum style error codes, define your own enums and use it here.

**Comment by tabiStein** [comment]
Thanks for the quick reply and the link to the error codes @balamurugana !

**Comment by youngledo** [comment]
> It is same logic like below
> 
> ```java
> try {
>   StatObjectResponse stat = minioClient.statObject(StatObjectArgs.builder().bucket("my-bucketname").object("my-objectname").build());
>   found = true;
> } catch (ErrorResponseException e) {
>   if (e.response().code() != "NoSuchKey")) {
>     throw e;
>   }
> }
> ```
> 
> Refer https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html for error codes. If you want enum style error codes, define your own enums and use it here.


Should be:
```java
if ("NoSuchKey".equals(e.errorResponse().code())) {
                //
}
```

😄
