### ISSUE TITLE
Provide Maven support to fetch minio jar along with all dependent jar's 

### ISSUE THREAD

**Issue by vrock28** [minio/minio-java#641]
Currently, the maven entry provided here will result in just downloading the minio-3.0.9.jar and not minio-3.0.9-all.jar. I faced quite a bit of problem trying to unit test where the call to instantiate minio object was expecting the xmlPullParser class to be present but was not there in my local repo as its not part of minio-3.0.9.jar

It would be helpful if the -all.jar file is fetched as part of maven artifact entry in pom.xml rather than the trimmed one.

**Comment by balamurugana** [comment]
@vrock28 I am not sure how maven fetches *-all.jar` with specified dependency entries.  I see most of java projects provide something like below, where minio-java does the same.
```xml
<dependency>
  <groupId>com.squareup.okhttp3</groupId>
  <artifactId>okhttp</artifactId>
  <version>3.9.0</version>
</dependency>
```

You would need check maven how you can fetch `-all.jar`

**Comment by vrock28** [comment]
@balamurugana : I quite dont get it. Can you post the pom.xml file entry here which would help me fetch -all.jar ?

**Comment by balamurugana** [comment]
@vrock28 I said there is no option for fetch `-all.jar`

**Comment by balamurugana** [comment]
Reopen if necessary information is available.

**Comment by vrock28** [comment]
@balamurugana : We are hitting the "Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found" exception with the minio jar and when i manually include -all.jar, this gets resolved because the XmlPullParser is bundled as part of -all.jar

**Comment by balamurugana** [comment]
@vrock28 You would need to include the dependencies (all minio-java dependencies) into your maven configuration

**Comment by vrock28** [comment]
@balamurugana: where can I find all the minio java dependencies list?

**Comment by balamurugana** [comment]
@vrock28 https://github.com/minio/minio-java/blob/master/build.gradle#L54

**Comment by vrock28** [comment]
@balamurugana : Thanks for the pointer. Shouldn't these be bundled along with the minio jar itself rather than expecting these to be there before using the minio java client ? Or is it expected for folks to refer to the above file before starting ? At the very least, this should be called out somewhere in the documentation right ?

**Comment by balamurugana** [comment]
@vrock28 
1. I believe it is java development style (As I am not a java developer but seen many java projects).  Its required to have proper dependency map in your project.
2. Have you seen any project doing that? I aware none.
3. I don't see any project is doing that.  Project https://github.com/square/okhttp depends on okio which is not mentioned in the README doc.

The dependency issue is build system problem. I know `gradle` pulls all dependencies automatically.  If you use something else, your build system must be solution to solve dependency problems.

**Comment by vrock28** [comment]
@balamurugana :   
Based on my earlier experience, either we bundle all dependencies into one (like minio.3.0.9-all.jar) or we provide a Maven pom.xml  file that explicitly calls out these dependencies. Not sure if this way is commonly followed.

**Comment by balamurugana** [comment]
@vrock28  Hope https://stackoverflow.com/questions/17281927/how-to-make-gradle-generate-a-valid-pom-xml-file-at-the-root-of-a-project-for-ma helps
