### ISSUE TITLE
Support append some bytes to an existed object

### ISSUE THREAD

**Issue by cwjcsu** [minio/minio-java#654]
append or update:
`long appendObject(bucketName,objectName,byte[]data,int objOffset,int dataOffset,int length)`
or just append to the tail of file:
`long appendObject(bucketName,objectName,byte[]data,int dataOffset,int length)`
meight return the current length of the object.

**Comment by harshavardhana** [comment]
There is no S3 API which allows appending on an existing object. what is the purpose behind this API ?

**Comment by balamurugana** [comment]
@cwjcsu As @harshavardhana mentioned, there is no S3 API to do so.  This kind of application logic should be handled in your application layer, not in minio-java like SDKs.

Close this issue if answered.

**Comment by cwjcsu** [comment]
@harshavardhana ,aliyun oss api has this capability，I'm not familiar with S3. Thanks, I should close it.
