### ISSUE TITLE
Object etag contains '/' cause getObject fail in windows

### ISSUE THREAD

**Issue by cwjcsu** [minio/minio-java#658]
In MinioClient's `getObject(bucketName,objectName,fileName)` ，there is a line 
`String tempFileName = fileName + "." + etag + ".part.minio"`
when the etag contains character '/', the tempFileName will become a directory in windows,in my case ,the etag is 'W/32cd942789df57d72f5a216988e9e938'
the later line 
`os = Files.newOutputStream(tempFilePath, StandardOpenOption.CREATE, StandardOpenOption.APPEND);` 
will encounter a non-exists directory,and throw 
```
java.nio.file.NoSuchFileException: D:\git\cloudGuanjia\gateway\cloudGateway\src\main\assets\downloads\distribute\AgentDistributeFile-9\item-1.W\32cd942789df57d72f5a216988e9e938.part.minio
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:430)
	at java.nio.file.Files.newOutputStream(Files.java:172)
	at io.minio.MinioClient.getObject(MinioClient.java:1684)
```

**Comment by cwjcsu** [comment]
@harshavardhana ,the ETag is returned by `statObject(bucketName,  objectName)`

**Comment by balamurugana** [comment]
@cwjcsu Could you share `minio version` and how you run `minio` server?

**Comment by cwjcsu** [comment]
@balamurugana ,minio server version is '2017-11-22T19:55:46Z'

**Comment by harshavardhana** [comment]
> @harshavardhana ,the ETag is returned by statObject(bucketName, objectName) .The server is minio server

AWS S3 or Minio never sends an ETag with weak element https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation, so i suspect you are using a proxy in between manipulating what was sent by the server.

**Comment by cwjcsu** [comment]
@harshavardhana the server is using nginx,does thes matter?

**Comment by cwjcsu** [comment]
It's confirmed that it's the nginx cause the problem,changed the etag from '32cd942789df57d72f5a216988e9e938' to `W/"32cd942789df57d72f5a216988e9e938"` .
When i access the file from http://{ip}:9199 directly,not from nginx which is http://{ip}:80 ,the etag is correct
