### ISSUE TITLE
Set metadata for encrypted object (putObject())

### ISSUE THREAD

**Issue by helderribeirosousa** [minio/minio-java#660]
Hello,

I'm running a local instance of minio server and i wrote some basic java code leveraging "minio-java 3.0.11" to store an encrypted object on it.

```
//Recreates secret key from environment variable
SecretKeySpec secretKey = new SecretKeySpec(Hex.decodeHex("MY_AES_KEY_IN_HEX".toCharArray()),"AES");

//Encrypts file and uploads it
FileInputStream uploadStream = new FileInputStream(/path/to/my/file);

client.putObject("test","object",uploadStream,uploadStream.available(), "application/octet-stream", secretKey);
```

This is working just fine.
The problem is that i now want to associate some metadata to this blob. Something like:

```
HashMap<String,String> map = new HashMap<String,String>();
map.put("MY_KEY","MY_VALUE");

```
As far as i can tell there's no call to perform this. Or is there?

**Comment by balamurugana** [comment]
@helderribeirosousa I don't see version of `putObject()` accepts encryption key and header map.  This issue is taken as feature request.

**Comment by helderribeirosousa** [comment]
Just as i suspected @balamurugana.
Please make it a feature then. AFAIK Azure Blob Storage APIs (at least NodeJS) already support custom metadata for blob objects.

Thank you for help 👍

**Comment by deekoder** [comment]
Can someone from the community help us on this?

**Comment by deekoder** [comment]
This will soon be not an issue. We are changing the API style. PR #663. Closing this as invalid.

**Comment by deekoder** [comment]
Incorrectly close this issue for another.

**Comment by balamurugana** [comment]
@helderribeirosousa It is planed to remove client side encryption and support only SSE-C.  When SSE-C support is added, it will come up with `headerMap`.

Hope this helps.

**Comment by helderribeirosousa** [comment]
@balamurugana ok... Not the greatest outcome since i will need to handle the encryption and decryption myself.
But if i'm able to set the metadata so i can store the IV i guess i can live with it...

Thank you for the effort guys :)

**Comment by helderribeirosousa** [comment]
Is there an ETA for that release?

**Comment by ivoribeiro** [comment]
I would also like to know when this MR will be released.
Thanks.

**Comment by deekoder** [comment]
@aead  can we close this? Since the WIP pr is also closed. We can reopen it again and do this when we have more bandwidth.

**Comment by kannappanr** [comment]
Closing this PR as Server Side encryption side support is now available in `minio-java` SDK
