### ISSUE TITLE
Support composing objects from multiple existing ones. 

### ISSUE THREAD

**Issue by dkushner** [minio/minio-java#661]
In the same way that the Go SDK supports [composing](https://github.com/minio/minio-go/blob/706c81d3ee2a18cdd8239faf544de8a066e7e261/api-compose-object.go) new objects from existing object parts, the Java SDK should support this behaviour.

**Comment by deekoder** [comment]
@dkushner We will close this as a won'tfix for now and address this later after we finish up our current backlog of items.
