### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by joseivanpo** [minio/minio-java#665]
Hi Minio team!

I'm getting a error when trying to compile my apk after integrate Minio on my project, I also tried creating a new project and adding only Minio dependency without any other import and still get the error.

This is the Log:
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

My gradle:
>defaultConfig {
        applicationId "com.rocketjourney.rocketjourney"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

>dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:design:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    //ORM ActiveAndroid, URL = https://github.com/pardom/ActiveAndroid/wiki/Getting-started
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    compile 'com.estimote:sdk:1.4.0'
    compile 'com.cocosw:bottomsheet:1.3.0@aar'
    compile 'io.minio:minio:3.0.12'
}

**Comment by mehmetcanker** [comment]
+1

**Comment by nitisht** [comment]
@joseivanpo have you tried setting `multiDexEnabled` to true

```
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```

**Comment by mehmetcanker** [comment]
@nitisht not working with this config

**Comment by joseivanpo** [comment]
@nitisht Still not working

**Comment by nitisht** [comment]
@joseivanpo @mehmetcanker what is the android studio and gradle version you're using? 

I found a similar issue here https://github.com/paypal/PayPal-Android-SDK/issues/448

**Comment by joseivanpo** [comment]
I'm using gradle 3.0.1 and Android Studio 3.0.1, should I change the gradle version? @nitisht

**Comment by deekoder** [comment]
We are not sure why this is happening.  Need to ask community for help with this issue. Marking help wanted.

**Comment by deekoder** [comment]
@joseivanpo  i wonder if you can try and see if you get this idea in another IDE outside of Android studio/gradle systems.

**Comment by nitisht** [comment]
@joseivanpo we need help to repro and troubleshoot. Closing it for now, please reopen when you are able to help us in the repro/troubleshoot
