### ISSUE TITLE
Return stats when getting object

### ISSUE THREAD

**Issue by s-spindler** [minio/minio-java#673]
At the moment the various `getObject` methods return an `InputStream`, i.e. only the response body.
Additional information from the HTTP headers of the response (like content type, length etc.) is left out.

Amazon's Java SDK has similar methods but returns an object of type `S3Object` (see `com.amazonaws.services.s3.AmazonS3` which allows access to that information.
Maybe a similar approach is possible here.

**Comment by deekoder** [comment]
We will discuss it here and let you know. Parking it in future for now.

**Comment by deekoder** [comment]
We will consider this work when we are done with the current set of priorities on our plate. Until then I will close it. We reactivate closed issues when we are done with current issues.

**Comment by s-spindler** [comment]
May I suggest keeping it open for now so that it is visible for anybody who would want to tackle and contribute it?
