### ISSUE TITLE
Program type already present: javax.annotation.CheckReturnValue

### ISSUE THREAD

**Issue by Dwebtron** [minio/minio-java#683]
Hey all - I just started trying to use this library today, but I'm having some trouble trying to just run a simple compile / gradle sync. When I put the following in my app.gradle:

>    implementation 'io.minio:minio:4.0.1'

I get this:

> Program type already present: javax.annotation.CheckReturnValue
Message{kind=ERROR, text=Program type already present: javax.annotation.CheckReturnValue, sources=[Unknown source file], tool name=Optional.of(D8)}

I'm not sure what to do. I've tried invalidating caches and restarting, cleaning the project, make/building the project.... The only thing that seems to work is just removing the line. But, of course then I can't use the library. Thoughts? Need more info from me? It's a brand new project I just created from scratch compiling on SDK 27 (I've also tried 28) with minSDK at 16.

**Comment by balamurugana** [comment]
May be you would need to remove minio.jar as per https://stackoverflow.com/a/50086364

**Comment by nitisht** [comment]
@Dwebtron is it possible to share the `app.gradle` file, I can try to reproduce it locally

**Comment by nitisht** [comment]
Thanks, we'll take a look!

**Comment by nitisht** [comment]
@Dwebtron looks like downgrading `com.android.support:appcompat` fixed the issue for few people, can you try steps mentioned here https://stackoverflow.com/questions/49112190/error-program-type-already-present-android-support-design-widget-coordinatorl

**Comment by nitisht** [comment]
@Dwebtron any progress here

**Comment by nitisht** [comment]
closing this due to no response, feel free to reopen if it is still not fixed.
