### ISSUE TITLE
A connection to xxx was leaked. 

### ISSUE THREAD

**Issue by meatfly** [minio/minio-java#696]
i am getting message "A connection to http://minio-service.minio:9000/ was leaked. Did you forget to close a response body?" while InputStream i =calling client.getObject(bucket, path) more than 50/sec.

it looks after inpustream close must be called response.body().close()

**Comment by kannappanr** [comment]
@meatfly Thanks for filing this issue. Do you see the issue all the time? Or is it happening in only certain cases. Can you please elaborate on that? Do you also have a sample program that we can use to reproduce the issue?

**Comment by meatfly** [comment]
@kannappanr i found bug in my code, i call 2x InputStream i =calling client.getObject(bucket, path) but only once i.close(). Now it seems it is ok. I apologize for the issue.
