### ISSUE TITLE
Is it possible to update the version of Jackson ref'd in build.gradle?

### ISSUE THREAD

**Issue by sjrd218** [minio/minio-java#699]
It appears the version of Jackson referenced in the build.gradle file is old and vulnerable to data deserialization attacks. Is it possible to update to the latest version of Jackson in the 2.9 series?

**Comment by nitisht** [comment]
fixed by #700

**Comment by sjrd218** [comment]
Can we get a build that incorporates this fix? We are currently unable to use this library in our product because of the vulnerability in the current release, and we'd really like to use your excellent library. Thanks!

**Comment by nitisht** [comment]
Sure, we'll make a release soon @sjrd218 cc @deekoder
