### ISSUE TITLE
More than one file was found with OS independent path 'org/joda/time/format/messages_en.properties'

### ISSUE THREAD

**Issue by MeLean** [minio/minio-java#703]
When I have in my project dependencies:
```
    implementation 'io.minio:minio:5.0.1'
    implementation 'net.danlew:android.joda:2.9.9'
    implementation "com.android.support:appcompat-v7:28.0.0-rc02"
    implementation "com.android.support:support-v4:28.0.0-rc02"
    implementation "com.android.support:design:28.0.0-rc02"
    implementation "com.android.support:recyclerview-v7:28.0.0-rc02"
```
I got that kind of exception. I google it and I found this solutions  [here](https://stackoverflow.com/questions/29568964/gradle-duplicate-files-during-packing-messages-properties-of-jodatime
)
But none of them helped.
When I tried to exclude joda-time as fowls:
```
    implementation('io.minio:minio:5.0.1'){
        exclude module: 'joda-time'
    } 
```
I got exception:

> Program type already present: javax.annotation.Detainted
> Message{kind=ERROR, text=Program type already present: javax.annotation.Detainted, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by kannappanr** [comment]
@MeLean Thanks for reaching out to us. We will take a look at this and get back to you.

**Comment by MeLean** [comment]
javax library is used by "org.greenrobot:eventbus" wich is included in my project too.

**Comment by aead** [comment]
@MeLean Can you check that their is no {minio / minio-dependency}.jar in your lib folder? AFAICS this must be a compatibility issue - your relying on two incompatible dependencies...

**Comment by kannappanr** [comment]
Closing this issue as stale. Please feel free to reach out to us if you still need help.
