### ISSUE TITLE
Support for metadata in putObject

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-java#705]
One of the requests that we got at the conference here was to support metadata for putObject (just like how we support it in minio-go)

**Comment by nitisht** [comment]
@krishnasrinivas would this work http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.io.InputStream-long-java.util.Map-

There is already option to add metadata in `headerMap` and use this API

**Comment by cwurbs** [comment]
@nitisht ,that's great to hear. But the Java SDK documentation that people stumble upon (https://docs.minio.io/docs/java-client-api-reference.html) is missing that part. Although it is present for the others language SDKs.

**Comment by Praveenrajmani** [comment]
Yes we already have meta data support for PUT [https://github.com/minio/minio-java/blob/master/examples/PutObjectWithMetadata.java](url) . Need to update the docs though..

**Comment by kannappanr** [comment]
@Praveenrajmani, Just to clarify, looking at http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.io.InputStream-long-java.lang.String-javax.crypto.SecretKey- we do not seem to have metadata support in the case of encrypted `putObject` calls. Maybe that is also something that we need to add.

**Comment by Praveenrajmani** [comment]
Yes @kannappanr, looks like we already have provision for encrypted putObject with metadata [https://github.com/minio/minio-java/blob/8ad645bd3829f20251756a535773cffc87c79bac/api/src/main/java/io/minio/MinioClient.java#L3414](url) which is a private class. We need to expose it by making it public. Will send a PR for this

**Comment by kannappanr** [comment]
@Praveenrajmani I will open a new issue to track the documentation update. But in the meantime, while you add new API in Java, please make sure that corresponding API's documentation is updated as part of that PR.
