### ISSUE TITLE
Unable to get first X bytes of object

### ISSUE THREAD

**Issue by panteparak** [minio/minio-java#706]
I am unable to get the first X bytes of object via getObject(String bucketName, String objectName, long offset, Long length). Specifying a 0 offset and X length would return an entire file rather than bytes from 0 - X-1

Directly Quoting RFC 2616 Page 138, Regarding Byte range.

> The first 500 bytes (byte offsets 0-499, inclusive):  bytes=0-499

Further inspection of the source code, I found that if offset is less than or equal to 0, range header would get ignored.
Screenshot of source code from `MinioClient.java` Version 5.0.1
<img width="1267" alt="screen shot 2018-10-01 at 02 17 46" src="https://user-images.githubusercontent.com/16161996/46261613-6b9ee180-c520-11e8-8f3c-b04bce2db2ab.png">

**Comment by harshavardhana** [comment]
can you paste your example code? @panteparak

**Comment by harshavardhana** [comment]
also what is the server in question here?

**Comment by panteparak** [comment]
I am using Minio server 
this is sample code 
`minioClient.getObject("ABC", "somefile", 0, 10)`

Expected content: get input stream with 10 bytes. But I got an entire file content.

**Comment by sinhaashish** [comment]
PR #707 resolves it.
