### ISSUE TITLE
java client support 'Bucket Notification' api ?

### ISSUE THREAD

**Issue by gbKidCoding** [minio/minio-java#711]
can't find it in java client api

**Comment by kannappanr** [comment]
@gbKidCoding Yes it does, please look at https://github.com/minio/minio-java/blob/master/examples/GetBucketNotification.java , https://github.com/minio/minio-java/blob/master/examples/RemoveAllBucketNotification.java and https://github.com/minio/minio-java/blob/master/examples/SetBucketNotification.java Will update the docs to reflect these APIs

**Comment by deekoder** [comment]
@gbKidCoding  closing this. If you feel something is really missing that you need, please feel free to reactivate this issue.

**Comment by deekoder** [comment]
we do need to link these and add them to our API doc.

**Comment by gbKidCoding** [comment]
@kannappanr  Thanks!

**Comment by songzijiang** [comment]
it helps me a lot
