### ISSUE TITLE
How to support Topic or Cloud Function based notifications.

### ISSUE THREAD

**Issue by songzijiang** [minio/minio-java#712]
i'm trying to set the notifications but it gievs me `io.minio.errors.ErrorResponseException: Minio server does not support Topic or Cloud Function based notifications.`what should i do to deal with the problems

**Comment by kannappanr** [comment]
This looks like a duplicate of #710

**Comment by songzijiang** [comment]
yep,it happend when i new the object.and if i get object from the minioclinet,it throws the exception like #710

**Comment by kannappanr** [comment]
closing this issue as duplicate of #710

**Comment by kannappanr** [comment]
@songzijiang Minio does not support Topic notifications. We will update the example such that you can use it in Minio.
