### ISSUE TITLE
Is it possible to show a picture with custom resolution

### ISSUE THREAD

**Issue by songzijiang** [minio/minio-java#713]
i want to resize an image when it is shared.can u add the feature in future,thx.

**Comment by kannappanr** [comment]
@songzijiang Can you check out if this will work out for you? https://stackoverflow.com/questions/41281024/resize-existing-images-in-s3-bucket-folder

**Comment by songzijiang** [comment]
> @songzijiang Can you check out if this will work out for you? https://stackoverflow.com/questions/41281024/resize-existing-images-in-s3-bucket-folder

it looks like will slove my issue,thx
