### ISSUE TITLE
Implement bulk delete

### ISSUE THREAD

**Issue by mindscratch** [minio/minio-java#715]
The other minio SDK's ([minio-go](https://docs.minio.io/docs/golang-client-api-reference.html#RemoveObjects) for example) provide the ability to delete objects in bulk, which is faster than deleting objects one at a time. It would be nice if the java SDK provided similar functionality.

**Comment by nitisht** [comment]
Thanks @mindscratch we'll take a look soon

**Comment by mindscratch** [comment]
For those interested, the [AWS SDK for Java](https://aws.amazon.com/sdk-for-java/) implements bulk deletes. You can include just the S3 portion of the sdk by using [aws-java-sdk-s3](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3).

**Comment by sinhaashish** [comment]
@mindscratch  Please[ refer](https://github.com/minio/minio-java/blob/master/examples/RemoveObjects.java) . This is already an existing functionality .[PTAL](https://github.com/minio/minio-java/issues/467)

**Comment by mindscratch** [comment]
@sinhaashish The example that you referenced does delete multiple objects, but it does so by making multiple requests. The AWS S3 API supports deleting multiple objects with one HTTP request.

Looking at the [MinioClient.java](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java) there is not function for deleting multiple objects with one HTTP request.

**Comment by mindscratch** [comment]
Oh, I see now, thanks for the reference.

**Comment by sinhaashish** [comment]
> Oh, I see now, thanks for the reference. Perhaps the [API docs](https://docs.minio.io/docs/java-client-api-reference) can be updated.

The documentation is already present under `removeObjec`t tag . Refer . The second part under `removeObject` has all the details .
```    
removeObject(String bucketName, Iterable objectNames)
public Iterable<Result<DeleteError>> removeObject(String bucketName, Iterable<String> objectNames)

Removes multiple objects. ```
