### ISSUE TITLE
The method putObject doesn't save custom metadata

### ISSUE THREAD

**Issue by sberequek** [minio/minio-java#720]
Hi, 
when I try to save a custom Map to metadata with put_object, it saves only keys which starts with 'X-Amz-Meta', all other key are ignored.

**Comment by kannappanr** [comment]
@sberequek If you take a look at https://github.com/minio/minio-java/blob/master/examples/PutObjectWithMetadata.java#L72

`X-Amz-Meta-...` is the custom metadata. If you want to add custom metadata, you will have to prefix it with `X-Amz-Meta`

**Comment by kannappanr** [comment]
@sberequek Closing this issue as answered. Please feel free to open other issues if you have further questions.
