### ISSUE TITLE
Fix API documentation

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-java#723]
The API documentation is a little outdated. This needs to be up to date.

**Comment by sinhaashish** [comment]
@kannappanr  The documentation is present under `removeObject` tag . [Refer](https://docs.minio.io/docs/java-client-api-reference#removeObject) .  The second part under `removeObject` has all the details .
```    
removeObject(String bucketName, Iterable objectNames)
public Iterable<Result<DeleteError>> removeObject(String bucketName, Iterable<String> objectNames)

Removes multiple objects. ```

**Comment by kannappanr** [comment]
I think this issue is closed via https://github.com/minio/minio-java/pull/730

@sinhaashish Please re-open the issue if that is not the case.
