### ISSUE TITLE
cluster endpoints in client

### ISSUE THREAD

**Issue by z0mb1ek** [minio/minio-java#724]
Hi. I see in constructor only one endpoint, but if I have a cluster, what should I do?

**Comment by harshavardhana** [comment]
Use a load balancer or round robin DNS for all IPs - it is by design to take single endpoint.

**Comment by z0mb1ek** [comment]
thx

**Comment by johnnymillergh** [comment]
> Use a load balancer or round robin DNS for all IPs - it is by design to take single endpoint.

Thank you so much. I was looking for the answer for sooo long

**Comment by devMls** [comment]
this feature can be interesting. In MariaDB JConnector (JDBC Driver) exists and it is usefull, maybe is possible replicate the feature

https://mariadb.com/kb/en/about-mariadb-connector-j/#failover-and-load-balancing-modes
