### ISSUE TITLE
Error: Program type already present: javax.annotation.Nonnull$Checker

### ISSUE THREAD

**Issue by Dwebtron** [minio/minio-java#726]
I let this project sit for a while, and just came back to it. Unfortunately I'm still having an issue similar to this one : https://github.com/minio/minio-java/issues/683

The full error is : 

> Program type already present: javax.annotation.Nonnull$Checker
> 	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
> 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
> 	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
> 	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
> 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
> 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
> 	... 33 more

I created a brand-new app to test this on, with the only change being to add : 

>     implementation 'io.minio:minio:5.0.2'

Since this is happening for me on multiple versions of minio, is this my fault somehow? This is my full gradle: 

> apply plugin: 'com.android.application'
> 
> android {
>     compileSdkVersion 28
>     defaultConfig {
>         applicationId "com.example.tester"
>         minSdkVersion 26
>         targetSdkVersion 28
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation 'com.android.support:appcompat-v7:28.0.0'
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     implementation 'com.android.support:design:28.0.0'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'com.android.support.test:runner:1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
>     implementation 'io.minio:minio:5.0.2'
> 
> }
> 

I've tried messing with the minSdkVersion too, from 16 to where it is now at 26. Lower versions show a different error. Is it maybe because I'm using this with Android instead of a regular java project?

**Comment by kannappanr** [comment]
@Dwebtron Did you get a chance to try out what was suggested in https://github.com/minio/minio-java/issues/683#issuecomment-405180172

Please let us know if that workaround fixes the issue for you.

**Comment by Dwebtron** [comment]
The workaround in that link was to change the downgrading 

> com.android.support:appcompat

 version to another version, right?. Yes, I tried + and - versions with no luck.

**Comment by muzammilhussnain14** [comment]
@nitisht, @Dwebtron  I just solved this issue and here is the link of stack-overflow answer for this issue. [Stackoverflow Answer](https://stackoverflow.com/questions/53374677/minio-gradle-dependency-android-javax-annotation-checkreturnvalue/53387292#53387292)

**Comment by nitisht** [comment]
Thanks @muzammilhussnain14 this is very helpful!

**Comment by nitisht** [comment]
closing this due to no response, feel free to reopen @Dwebtron if above fix doesn't work for you
