### ISSUE TITLE
Should non-AWS-compatible buckets names be allowed?

### ISSUE THREAD

**Issue by manics** [minio/minio-java#728]
Currently bucket names must be compatible with AWS. This is enforced by `checkBucketName` in `createRequest`: https://github.com/minio/minio-java/blob/5.0.2/api/src/main/java/io/minio/MinioClient.java#L829

It's possible for bucket names on other S3 servers to not follow the same rules, e.g. they can contain uppercase, for example, minio server in nas gateway mode, and I've come across at least one other server that had bucket names with capitals. Should mino-java allow this, or do you consider it a breakage of the S3 API that shouldn't be supported?

**Comment by harshavardhana** [comment]
We do not want to diverge away on this from AWS, we support federation based on bucket names as DNS it will become incompatible and complex.

**Comment by manics** [comment]
Thanks for answering.
