### ISSUE TITLE
I call putObject() API, when there are incomplete parts, it still putObject() and gets the same etag again. I found my md5Hash and  the part.etag() look very different. Is there anything wrong?

### ISSUE THREAD

**Issue by shpwang** [minio/minio-java#738]
I just use JAVA main function for testing(JAVA sdk).

Minio version: 5.0.4
![image](https://user-images.githubusercontent.com/10089768/49841913-73b6af80-fdf4-11e8-8110-0dca8571f497.png)

The steps are:
1. I called "putObject()" to upload a 1G size file.
![image](https://user-images.githubusercontent.com/10089768/49841807-fa1ec180-fdf3-11e8-83ae-938e817571b2.png)
2. Interrupt the process after few seconds
3. Check my minio docker volume, I found the **/data/.minio.sys/multipart/** folder appear some files and the size about 500MB.
4.  Repeat the step1, I called "putObject()" to upload the same 1G size file again.
5.  Debug and trace the code, it gets `existingParts` successfully(https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L3693). But when the process goes to `if (md5Hash.equals(part.etag()))`(https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L3736), it always gets the negative result, so it uploads all of the parts again.

     I printed my **md5Hash** and the **part.etag()**, these two formats look very different(refer to the screenshot below). 
![image](https://user-images.githubusercontent.com/10089768/49842135-59310600-fdf5-11e8-8ce1-e13f0b47dd38.png)

Please help, which step did I do wrong?

**Comment by nitisht** [comment]
we'll take a look @shpwang

**Comment by shpwang** [comment]
@nitisht Thank you so much

**Comment by kannappanr** [comment]
@shpwang We have already merged a PR https://github.com/minio/minio-java/pull/741 As described in the PR, we will not try to resume multipart uploads when a `putObject` call that does a `multi-part upload` internally fails. We will be starting all over again. So, closing this issue as this issue is not valid anymore.
