### ISSUE TITLE
Cannot add custom meta data with putObject in general

### ISSUE THREAD

**Issue by marcadella** [minio/minio-java#745]
You implemented custom metadata with putObject(InputStream, Size). It would take about 10 minutes to implement it for all the putObject methods. Why not doing it??
Best regards.

(Generalization of https://github.com/minio/minio-java/issues/662)

**Comment by kannappanr** [comment]
@marcadella We will take a look at it and implement it. On a quick look, we might have to add one for the variation of 

`putObject(String bucketName, String objectName, ServerSideEncryption sse, String fileName)`
 and may be

`putObject(String bucketName, String objectName, String fileName)`

Will implement it soon.
