### ISSUE TITLE
Misleading implementation of minio-java:putObject

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-java#746]
Copying the contents of the issue https://github.com/minio/minio/issues/7053 as this issue belongs to this repo.

putObject should take an OutputStream and not an InputStream. It works ok with IS, but it is not very professional (and misleading). In addition the SDK doc does not mention that one should close the IS (as it is done for getObject).

**Comment by marcadella** [comment]
Ok I saw AWS is using InputStream as well, my bad. Thanks for the quick answer and sorry if I was a bit rude.

**Comment by kannappanr** [comment]
@marcadella No problem. Closing the issue based on the comments above.
