### ISSUE TITLE
Does the Java client support AWS instance profiles for S3 authentication?

### ISSUE THREAD

**Issue by tommy979** [minio/minio-java#756]
I can't find anything in the documentation that mentions setting up the Minio Java Client to authenticating with IAM/instance profiles. I see that there is something over on the Go client (https://github.com/minio/minio-go/commit/5d7ee332f62e83d36beba669be671801180abb89)

There are APIs that allow you to specify a region but in this case, I don't want to specify an access or secret.

**Comment by kannappanr** [comment]
We have this support only in `minio-go` as of now. If you can, we would love to have a PR.

**Comment by kannappanr** [comment]
Closing this issue now. Marking this request for future. Will re-open this issue when we find time to work on this.
