### ISSUE TITLE
Question on java minio client with distributed minio server

### ISSUE THREAD

**Issue by thomaslange24** [minio/minio-java#759]
When i create a minio client i have to pass the url to one of the nodes of distributed minio (not a list of them). Are there any differences in which of the urls to take? I tried some scenarios in which i shut down the minio server of the according node before creating the minio client with the url of the same node or shutting down while uploading/downloading a bunch of random files. And it kept working. Which is what it is supposed to do, but i would like to know what exactly happens when this is the case? Which server processes the requests?

**Comment by harshavardhana** [comment]
We will be adding support to take list of endpoints, for now you can either 

- have a common load balancer (provided by most k8s, docker) like environments
- have a round robin DNS setup in your /etc/hosts on the client

**Comment by thomaslange24** [comment]
And what does minio client actually do, when the endpoint to a node is passed that is currently not available? Or the given endpoint suddenly is not available any more during the up or download? 
When i tested those cases they did not seem to affect the up or download.

**Comment by harshavardhana** [comment]
If the endpoint is not available it will fail. All operations will fail.

**Comment by thomaslange24** [comment]
Sure, but if that endpoint is part of a distributed minio setupw with 4 nodes it keeps uploading files.

**Comment by harshavardhana** [comment]
> Sure, but if that endpoint is part of a distributed minio setupw with 4 nodes it keeps uploading files.

do you have a load balancer between all servers? - it won't happen if you are not using kubernetes or docker swarm like environments.

**Comment by thomaslange24** [comment]
I am not using a load balancer. I observerd, that it is no problem if I shut down only one of the nodes. There seemed to be no visible issues on the client side. The Problems only arise when i shut down more than one. I just wanted to to know how it could be, that one missing node does not lead to problems

**Comment by harshavardhana** [comment]
> I am not using a load balancer. I observerd, that it is no problem if I shut down only one of the nodes. There seemed to be no visible issues on the client side. The Problems only arise when i shut down more than one. I just wanted to to know how it could be, that one missing node does not lead to problems

You are not taking down the endpoint minio client is referencing @thomaslange24 - of course what you are saying is the server behavior.

**Comment by thomaslange24** [comment]
But isn't minio client referencing the enpoint i passed as url? Then how can I know which of the endpoints minio client uses to upload the files?

**Comment by harshavardhana** [comment]
You may want to re-read this again https://github.com/minio/minio-java/issues/759#issuecomment-470609404 @thomaslange24

**Comment by kannappanr** [comment]
@thomaslange24 Closing this issue as answered. Please feel free to reach out to us if you have furhter questions.
