### ISSUE TITLE
Cannot set custom headers

### ISSUE THREAD

**Issue by marcadella** [minio/minio-java#774]
There is no way to add a custom header to requests which makes it difficult to use CORS for example. Cf. https://github.com/minio/minio/issues/3985

**Comment by kannappanr** [comment]
Did you get a chance to look at http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.lang.String-java.lang.Long-java.util.Map-io.minio.ServerSideEncryption-java.lang.String-

**Comment by kannappanr** [comment]
@marcadella Please take a look at the example here https://github.com/minio/minio-java/blob/master/examples/PutObjectWithMetadata.java

**Comment by marcadella** [comment]
Yes that is true it is possible to set it for the putObject method but it the parameter is mission for all the other methods.

**Comment by harshavardhana** [comment]
> Yes it's true it's possible to set it for the putObject method but it the parameter is missing for all the other methods.

It has no meaning in S3 API for all other methods user-metadata is only supported for PutObject @marcadella

**Comment by marcadella** [comment]
Thanks for your answer but I am not talking about user-metadata, but HTTP headers. As you can see [here](https://github.com/minio/minio/issues/3985) we do need to be able to set the ORIGIN header for all the methods in order to get CORS to work properly.

**Comment by marcadella** [comment]
Up?

**Comment by marcadella** [comment]
@harshavardhana I agree that this is not a bug, but could you replace "working as intended" with feature request or some kind of other flag?

**Comment by harshavardhana** [comment]
We cannot do that @marcadella why do you need to set origin headers for Java methods?

**Comment by marcadella** [comment]
@harshavardhana you wrote yourself [here](https://github.com/minio/minio/issues/3985):
 > On the browser or your client you need to set the valid `Origin:` HTTP header[1] [...] for any PUT or GET request.

My client is written in Java therefore do you agree that I need this Origin header for both PUT and GET requests in the Java driver? putObject let me do that nicely, but I currently cannot add the Origin header to getObject for example.
I'm far from being a web expert, so let me know if I'm wrong.

**Comment by harshavardhana** [comment]
@marcadella how are you running minio-java in the web browser?

**Comment by marcadella** [comment]
@harshavardhana Ok I think I get it now. It's unlikely minio-java is used in java-script...
Sorry for the silly questions!
