### ISSUE TITLE
using presignedPutObject upload file

### ISSUE THREAD

**Issue by chenqiguang** [minio/minio-java#781]
using presignedPutObject get a url ,then  using httpClient upload file 
![image](https://user-images.githubusercontent.com/24667581/62032706-ed34ce00-b21c-11e9-905f-1c22d5c1e4b5.png)

when using addBinaryBody , can not upload file 
![image](https://user-images.githubusercontent.com/24667581/62032948-777d3200-b21d-11e9-943c-855903df2f76.png)

when using addPart, can upload file,but some http headers fill to the origin file
![image](https://user-images.githubusercontent.com/24667581/62033074-bdd29100-b21d-11e9-859a-fec3ad9a3acf.png)

so I want to know how to remove the http headers or when using addBinaryBody , what is the parameter “name” ？

**Comment by balamurugana** [comment]
Refer [here](https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L1861) how to use presigned PUT.

Refer [here](https://github.com/minio/minio-java/blob/master/functional/FunctionalTest.java#L1908) how to use presigned POST which supports multipart.

**Comment by chenqiguang** [comment]
thanks very much，I am already resovle my problem @balamurugana

**Comment by balamurugana** [comment]
@chenqiguang If things are working for you, you could close this issue.

**Comment by chenqiguang** [comment]
ok，I am sorry，I will close this comment right now.

**Comment by ChyHuang3033** [comment]
> thanks very much，I am already resovle my problem @balamurugana

请问你是怎么解决上传的文件前面添加有请求头信息的？
