### ISSUE TITLE
PostPolicy not implements  SetSuccessStatusAction?

### ISSUE THREAD

**Issue by wittech** [minio/minio-java#782]
PostPolicy not implements  SetSuccessStatusAction?

**Comment by kannappanr** [comment]
@wittech Can you please give more details?

**Comment by kannappanr** [comment]
Closing the issue. Please feel free to re-open the issue and provide us with more information.

**Comment by harshavardhana** [comment]
Re-opening this issue for now what @wittech is asking is to support https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

> success_action_status

> If you don't specify success_action_redirect, the status code is returned to the client when the upload succeeds.
> 
> Accepts the values 200, 201, or 204 (the default).
> 
> If the value is set to 200 or 204, Amazon S3 returns an empty document with a 200 or 204 status code.
> 
> If the value is set to 201, Amazon S3 returns an XML document with a 201 status code.
> 
> If the value is not set or if it is set to an invalid value, Amazon S3 returns an empty document with a 204 status code.
> 
> Type: String
> 
> Default: None
> 
> Note
> 
> Some versions of the Adobe Flash player do not properly handle HTTP responses with an empty body. To support uploads through Adobe Flash, we recommend setting success_action_status to 201.
