### ISSUE TITLE
MAX_OBJECT_SIZE MAX_MULTIPART_COUNT is configurable

### ISSUE THREAD

**Issue by woxinqidai** [minio/minio-java#791]
If null is passed, the default MAX_OBJECT_SIZE MAX_MULTIPART_COUNT will be used to calculate the size of a single part, which is more than 500 megabytes. Can you customize MAX_OBJECT_SIZE MAX_MULTIPART_COUNT to control the size of a single part in the case of a stream

**Comment by kannappanr** [comment]
@woxinqidai I believe you are asking for a way to specify multipart size. we have this implemented in few other SDKs like `js` and `python`, Please feel free to send a PR

**Comment by woxinqidai** [comment]
ok, thank you !

**Comment by kannappanr** [comment]
@woxinqidai Closing this issue as stale. Please feel free to send a PR when you are ready.
