### ISSUE TITLE
unhandled HTTP code 301

### ISSUE THREAD

**Issue by Danbuth** [minio/minio-java#792]
I use minio sdk for java to connect aws s3.
when The region is cn-northwest-1, I cann't connect to aws s3 (NingXia region).
when the region is  cn-north-1, I can connect to aws s3 (Beijing region).
But I use `mc` can connect two regions and operate.

**Comment by harshavardhana** [comment]
301 is not handled on purpose, this looks like you are using buckets with wrong region setting.

**Comment by kannappanr** [comment]
@Danbuth Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for firhter such questions.

**Comment by Danbuth** [comment]
the config is right, but i cann't connect cn-northwest-1 and  i can connect to cn-north-1 region.

**Comment by harshavardhana** [comment]
> the config is right, but i cann't connect cn-northwest-1 and i can connect to cn-north-1 region.

Most probably because we don't have cn-northwest-1 endpoint not updated.

**Comment by Danbuth** [comment]
yeah，now i use aws-s3-sdk to connect s3 and minio.
now i have a new question, when i use s3-sdk to connect, the us-east-1  region which I have selected,Is there a difference in choosing a different region?Which region should i choose？
