### ISSUE TITLE
Support STS Client Grants authentication flow

### ISSUE THREAD

**Issue by haneefkassam** [minio/minio-java#793]
Minio Go client sdk supports sts authentication flow and using jwt/session tokens for authentication.  This feature is missing from the minio Java sdk, and would bring the Java SDK into closer parity with the Minio Go SDK and the AWS Java SDK.

**Comment by harshavardhana** [comment]
@haneefkassam definitely this is on our roadmap.

**Comment by haneefkassam** [comment]
@harshavardhana Thanks for your quick reply!  Do you know the relative milestone/release it's targeted for (if it is already targeted for a milestone/release)? (or a reference to it on the roadmap so I can follow it)

**Comment by harshavardhana** [comment]
There is no set roadmap yet, but we will get to it soon.

**Comment by haneefkassam** [comment]
Awesome!  I'm excited!  I LOVE minio!

**Comment by davemsolomon** [comment]
I think I can make this code change to allow the passing of a session token. A decision needs to be made about the signature of the minioclient constructor that will allow for the passing of the session token.

**Comment by harshavardhana** [comment]
We shouldn't do that @davemsolomon we should do what minio-go does come up with an interface to implement various STS implementations

**Comment by mperia** [comment]
Do you know when this will become available for java client? using 6.0.13 version of the client.  Are there alternatives to send the security token?

**Comment by senthillogs** [comment]
> Do you know when this will become available for java client? using 6.0.13 version of the client. Are there alternatives to send the security token?

Could you please let us know when this feature would be available?

**Comment by harshavardhana** [comment]
> > Do you know when this will become available for java client? using 6.0.13 version of the client. Are there alternatives to send the security token?
> 
> Could you please let us know when this feature would be available?

We are working through other priorities right now, we will get to this issue in future. We don't have a set date yet.

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/1026

**Comment by rsivakanth** [comment]
Hi,
I the SessionToken feature available yet for Java client?
Could you please comment when would this feature be available?
Thanks,
Sivakanth.
