### ISSUE TITLE
Is there an API to determine if a file exists in a bucket

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio-java#799]
I want to determine whether there is a file in a bucket, but now I can only use the method `listObjects()`. When there are many files, the response time of calling this method is relatively long, so I want to ask if there are any other methods in Java that can determine whether there is a file in a bucket

**Comment by kannappanr** [comment]
@shouldnotappearcalm please look at https://docs.min.io/docs/java-client-api-reference.html#statObject . You can reach out to us at https://slakc.min.io for sucj questions.

**Comment by shouldnotappearcalm** [comment]
Hopefully the SDK will add methods to determine if the bucket is empty

**Comment by harshavardhana** [comment]
> Hopefully the SDK will add methods to determine if the bucket is empty

@shouldnotappearcalm you shouldn't implement such applications, there is some fundamental requirement going wrong here - what are you trying to implement?
