### ISSUE TITLE
Client Side encryption removed, why?

### ISSUE THREAD

**Issue by willie68** [minio/minio-java#804]
Hi,

is there a good reason, why you removed the client side encryption part from the java client.
Ok, i know that minio server now supports server side encryption, but not every S3 compatible server can do this.
Because of it's clean interface i liked to use the minio java client for all my  storage parts regarding S3. My provider uses a netapp S3 storage, which dosn't support sse. And i have to switch from verion 3.0.6 to a newer one, because the chunked upload (in special the recovery of already uploaded chunks) uses unsupported features, too. So i switch to the actual version, 6.0.11, and now i can upload more than 5Mb. But now it breaks my encryption. Surely i can reimplement client side encryption by myself, but i would like to know, why you remove this support. Are there any other reasons, why you break the interface?

BTW.: And why are you marking things deprecated in version 7, when the actual version is 6? 
(* @deprecated As of release 7.0) Or will you remove this marked methods in version 7, so the comment should be "to be removed in release 7.0"

**Comment by harshavardhana** [comment]
Because it's not useful @willie68 server does and support better encryption mechanisms so SSE is a better alternative and our SDKs only do one thing. Not multiple ways to do the same thing.

**Comment by kannappanr** [comment]
@willie68 Thanks for the suggestion on the deprecation part. Will fix it properly. Closing this issue as we will not be supporting client side encryption inside the SDK

**Comment by willie68** [comment]
> Because it's not useful @willie68 server does and support better encryption mechanisms so SSE is a better alternative and our SDKs only do one thing. Not multiple ways to do the same thing.

It's very useful. I don't use MinIO Server, because i use the S3 implementation of my provider. I like the simpler interface of the MinIO client. Call my conservative, but i didn't trust an anonymous server implementation, so won't use server side encryption. I can't check, if the server is not saving my encryption key. It's like putting money into a safe and than put the key on the notice board in the town hall. So for me this part of double implementation makes sense.
