### ISSUE TITLE
Update doc and readme example to use new not-Deprecated methods

### ISSUE THREAD

**Issue by DeepSnowNeeL** [minio/minio-java#805]
I saw that you prefer us to use the methods specifying ServerSideEncryption but can't find any updated doc neither on the readme nor the doc at https://docs.min.io/docs/java-client-quickstart-guide.html

Could it be updated ? Thanks

**Comment by kannappanr** [comment]
@DeepSnowNeeL We have documented all the methods in the same doc. For e.g, you can search for `getObject(String bucketName, String objectName, ServerSideEncryption sse)` and see what I mean. You can also look at http://minio.github.io/minio-java/io/minio/MinioClient.html. Closing this as answered, please feel free to reach out to us at https://slack.min.io for such questions

**Comment by DeepSnowNeeL** [comment]
Well, you could update the readme & other docs too, it feels strange to get taught to use deprecated methods

**Comment by cbou** [comment]
It would be nice to update the README :)
