### ISSUE TITLE
remove a directory (prefix) recursively

### ISSUE THREAD

**Issue by KevinSmile** [minio/minio-java#806]
**Problem:** 
How to remove a directory (prefix) recursively?

**Environment:** 
server: minio/minio:RELEASE.2019-10-12T01-39-57Z
java-client: 6.0.11

**My tests:**
You cannot remove a directory (prefix) directly.
You must list all objects in a directory (prefix), then delete them one by one.

**Discussion:**
`MinioClient.listObjects `supports a "prefix" option, which could be used as "directory" option.
So it would reasonable  that `MinioClient.removeObject(s) `supports something like recursively delete ?

The MinIO Browser does support recursively delete:
![image](https://user-images.githubusercontent.com/17903517/67845229-175a9c80-fb3a-11e9-8047-8fe1d6b15806.png)

Does MinIo-java-client support this?

**Comment by kannappanr** [comment]
```
You cannot remove a directory (prefix) directly.
You must list all objects in a directory (prefix), then delete them one by one.

```
Yes, S3 API does not take in a prefix and delete all the objects under that prefix. You are supposed to provide the actual object names. Even if `minio-java` has to do that, we will do exactly what you already do.

Browser is an exception and that is not an S3 API. minio-java and other client SDKs cannot implement that.

**Comment by kannappanr** [comment]
@KevinSmile Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further such questions.
