### ISSUE TITLE
initMultipartUpload、putObject、completeMultipart interface type is private？

### ISSUE THREAD

**Issue by ericzju** [minio/minio-java#808]
I am using minio for Object storage. Minio is a java project. I want to use multipartUpload, but I find  these function types are private , when to become public ?

1. private String initMultipartUpload(String bucketName, String objectName, Map<String, String> headerMap)
2. private String putObject(String bucketName, String objectName, Object data, int length,
                           Map<String, String> headerMap, String uploadId, int partNumber)
3. private void completeMultipart(String bucketName, String objectName, String uploadId, Part[] parts)

**Comment by vadmeste** [comment]
@ericzju MinIO SDKs are intended to plus simple to use. minio-java will use transparently the multipart upload without you knowing it.

Kindly join here https://slack.min.io/ if you have more questions.

**Comment by kannappanr** [comment]
@ericzju Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for more questions
