### ISSUE TITLE
Minio AssumeRole using SDK

### ISSUE THREAD

**Issue by emarcy** [minio/minio-java#817]
Is there support for the AssumeRole funtion from either the Minio Java SDK or the AWS Java SDK?

I found no documentation for this in the Minio SDK

I have attempted to use the AWS Java SDK to make an assumeRole call to a Minio sever.
It consistently fails with:
com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Generating temporary credentials not allowed for this request. (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: ########

I am hoping that there SDK support and perhaps an example is available. Thanks.

## Context
We are attempting to get credentials in a java app that a python client can subsequently use to put and get large files.

**Comment by emarcy** [comment]
Thanks for the reply. 
In lieu of SDK support, can someone supply a detailed example of using the http request for AssumeRole? 
In particular, the details of the AUTHPARAMS signature V4 authorization construction would be very helpful. The Minio documentation points to the AWS docs on this. 

Several things are unclear in the context of Minio. 

- Is this a GET request? or POST or ?
- Is there any restriction or recommendation as to the hashing algorithm? 
- Service is needed for the credential scope of the signing. What service is AssumeRole part of in Minio? Is it STS, IAM, S3, or ?
- Region is also needed for the credential scope of the signing, but Minio doesn't have a region. What value should be used? Or does it matter?

Thanks again for any assistance.

**Comment by tatiana-chukina** [comment]
Hi, you should use credentials of newly created user https://docs.min.io/docs/minio-multi-user-quickstart-guide.html 
Java code is this:

` 
AWSCredentials credentials = new BasicAWSCredentials("newuser", "newuser123");
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");
        
        AWSSecurityTokenService stsClient =
                AWSSecurityTokenServiceClientBuilder.standard()
                        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9000", Regions.US_EAST_1.name()))
                        .withClientConfiguration(clientConfiguration)
                        .withCredentials(new AWSStaticCredentialsProvider(credentials))
                        .build();

        AssumeRoleRequest assumeRequest = new AssumeRoleRequest()
                .withRoleArn("role")
                .withDurationSeconds(3600)
                .withRoleSessionName("sessionName");
        AssumeRoleResult assumeResult =
                stsClient.assumeRole(assumeRequest);`

**Comment by codeGeek16** [comment]
Hi tatiana-chukina ,

I tried using the above code but seem to have issue with importing AWSSecurityTokenServiceClientBuilder,AwsClientBuilder & AWSStaticCredentialsProvider.
I'm using minio version 7.0.2 and aws-java-sdk-sts version 1.9.6.

While creating a minio client with admin credentials works file for both file upload and download from java application .

**Comment by shougao** [comment]
could you please share the java SDK usage? thank you very much.
and if I want to using your commit, could you please share a feature branch release.thank you.

**Comment by balamurugana** [comment]
@shougao Please refer PR https://github.com/minio/minio-java/pull/1036 particularly [examples/MinioClientWithAssumeRoleProvider.java]( https://github.com/minio/minio-java/pull/1036/files#diff-cfd5b7d09f15b6d84883dfdc922bded2)

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/1036
