### ISSUE TITLE
statObject does not contain custom provided metadata

### ISSUE THREAD

**Issue by maxbroens** [minio/minio-java#823]
The metadata used in
putObject(String bucketName, String objectName, String fileName, Long size, **Map<String,String> headerMap**, ServerSideEncryption sse, String contentType)

is not returned when calling statObject() for the given object. My custom headers are also not in the httpHeaders.

documentation of putObject:
_**headerMap - Custom/additional meta data of the object.**_

documentation of statObject:
_**Returns: Populated object metadata.**_

**Comment by BigUstad** [comment]
Can you please tell us what custom headers are missing in httpHeaders? I was unable replicate this issue. Is it possible for you to attach just the relevant code extract?

**Comment by kannappanr** [comment]
@maxbroens We were unable to reproduce the issue locally. The custom metadata are returned in `httpHeaders`. Closing this issue as working as intended. Please feel free to add more information for us to reproduce this issue. We can open it then.
