### ISSUE TITLE
Replace joda-time by java.time utilities.

### ISSUE THREAD

**Issue by ypji** [minio/minio-java#827]
The SDK now requires JDK8 or above.
Joda-time itself encourges users to use JSR-310.
> Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.

**Comment by kannappanr** [comment]
@ypji Please feel free to send a PR

**Comment by ypji** [comment]
I checked the code, replaced all `org.joda.time.DateTime` and `java.util.Date`(it still resides on some codes) by `java.time.ZonedDateTime`.

But I guess, change it on next major release (7.0.0?) could be a better choice, API backward compatibility could be ignored.

**Comment by harshavardhana** [comment]
There is no reason to change major version if there are no breaking changes @ypji

**Comment by harshavardhana** [comment]
Fixed by #855
