### ISSUE TITLE
When deploy on Weblogic, it throws exception

### ISSUE THREAD

**Issue by 283665377** [minio/minio-java#830]
`Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.minio.DateFormat `
It conflicts with jars of weblogic ?

**Comment by sinhaashish** [comment]
@283665377   Can you give the steps to reproduce the issue.

**Comment by 283665377** [comment]
We solved this problem by adding the following code in the **weblogic.xml** file. Thank you!
```
        <prefer-application-packages>
            <package-name>org.joda.time.*</package-name>
        </prefer-application-packages>
```
