### ISSUE TITLE
Can't specify actions GetLifecycleConfiguration and PutLifecycleConfiguration in method setBucketPolicy.

### ISSUE THREAD

**Issue by MikhailCrimea** [minio/minio-java#831]
Hello everybody.
I'm looking at policy permissions page here https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html.
I'm already successfully pass some of permissions (PutObject, GetObject, GetBucketPolicy, PutBucketPolicy) from that page to method setBucketPolicy, but still can't pass GetLifecycleConfiguration and PutLifecycleConfiguration.
I see that object and bucket permissions needs to be declared in separate sections.
I'm getting exception "ErrorResponse(code=MalformedPolicy, message=Policy has invalid resource."
Are they implemented for java?
If they are not, where can I get supported "enumerations" and how can I manage permissions for bucket lifecycle operations?

Here is my json I try to apply: [json.zip](https://github.com/minio/minio-java/files/3998757/json.zip)

Thanks in advance.

**Comment by kannappanr** [comment]
@MikhailCrimea What is the object store that you are testing this against?

**Comment by kannappanr** [comment]
```
{
  "Version": "2012-10-17",
  "Statement": [
       {
          "Action": [
              "s3:PutObject",
              "s3:DeleteObject",
              "s3:GetObject"
          ],
          "Effect": "Allow",
          "Principal": {
              "AWS": [
                  "*"
              ]
          },
          "Resource": [
              "arn:aws:s3:::bucket/*"
          ]
      },
      {
          "Action": [
              "s3:DeleteBucket",
              "s3:ListBucket",
              "s3:GetBucketPolicy",
              "s3:PutBucketPolicy",
              "s3:GetLifecycleConfiguration",
              "s3:PutLifecycleConfiguration"
          ],
          "Effect": "Allow",
          "Principal": {
              "AWS": [
                  "*"
              ]
          },
          "Resource": [
              "arn:aws:s3:::bucket"
          ]
      }
  ]
}
```
The above policy works on AWS S3

**Comment by MikhailCrimea** [comment]
> @MikhailCrimea What is the object store that you are testing this against?

I'm using minio docker image minio/minio:RELEASE.2019-10-12T01-39-57Z.

**Comment by kannappanr** [comment]
@MikhailCrimea Closing this issue as https://github.com/minio/minio/pull/8698 has been merged. Please let us know if you still see this issue against `minio/minio:edge`
