### ISSUE TITLE
springmvc整合minio

### ISSUE THREAD

**Issue by moayi** [minio/minio-java#835]
<dependency>
          <groupId>io.minio</groupId>
          <artifactId>minio</artifactId>
          <version>6.0.11</version>
      </dependency>
      
      <dependency>
          <groupId>com.squareup.okhttp3</groupId>
          <artifactId>okhttp</artifactId>
          <version>3.9.1</version>
      </dependency>

[WARNING] The requested profile "dev" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project ffmpeg: Compilation failure
[ERROR] /D:/IdeaWorkspace/ffmpeg/src/main/java/com/sx/controller/MpegController.java:[53,38] 无法访问org.xmlpull.v1.XmlPullParserException
[ERROR]   找不到org.xmlpull.v1.XmlPullParserException的类文件

**Comment by vadmeste** [comment]
@moayi this doesn't seem related to minio-java, it looks like you are having issue compiling ffmpeg.

**Comment by moayi** [comment]
yes,my minio  version is 6.0.11 
When I execute this code, he will report an error
minioClient.putObject(BUCKET_NAME, file.getName(), file.getInputStream(), file.getContentType());

**Comment by kannappanr** [comment]
Not sure of the issue, but can you please take a look at https://github.com/minio/minio-java/issues/833 Maybe this is similar to that and you could use an approach similar to the one described there

**Comment by harshavardhana** [comment]
Closing this issue as 7.0.0 is released, PTAL at the latest release.
