### ISSUE TITLE
while call minioClient.putObject with size null client load about 500M into memory

### ISSUE THREAD

**Issue by kathzhan** [minio/minio-java#840]
Cause we do not know the stream size and while call the putObject the parameter goes to null.
minioClient.putObject("mybu", "my-objectname", fis, null, null, null,
                        "application/octet-stream");
calculateMultipartSize do the caculate
5L * 1024 * 1024 * 1024 * 1024 / 10000 about 500M goes to memory which may cause OoM, could the MAX_MULTIPART_COUNT be configured?
double partSize = Math.ceil((double) size / MAX_MULTIPART_COUNT);

**Comment by harshavardhana** [comment]
This is expected @kathzhan it won't OOM it reuses the same memory for all other parts. To reduce the memory usage set the appropriate size during upload.

**Comment by kathzhan** [comment]
the requirement is we do not really know the accurate size, but we want it sent to Minio piece by piece till nothing to. That's why we need piece size to be configured.

**Comment by kathzhan** [comment]
Plus if you use multi-thread the memory will be increased anyway based on ThreadPool size

**Comment by harshavardhana** [comment]
There is no option in S3 API where you don't know the size. Because maximum size of any object is 5TiB so you can never forever keep uploading data.

It is possible for us to take an override for part size. But it is not possible to support your use cases in S3 API.

So change your application, provide the right file size.

**Comment by kannappanr** [comment]
@kathzhan Closing this issue as answered. please feel free to reach out to us at https://slack.min.io for further such questions.

**Comment by zablvit** [comment]
@harshavardhana @kannappanr 
> There is no option in S3 API where you don't know the size.

S3 supports multipart Upload with streams as an input:
https://docs.aws.amazon.com/AmazonS3/latest/dev/usingHLmpuJava.html

> You can upload data from a file or a stream

Streams do not have a predefined size, so your answer is not strictly correct.

Question is then, does Minio support S3 Multipart upload or not?

**Comment by balamurugana** [comment]
The recent release has better API [putObject()](http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.io.InputStream-io.minio.PutObjectOptions-). Below is an example
```java
PutObjectOptions options = new PutObjectOptions(-1, 5242880); // assumed max size is 10,000 * 5MiB
minioClient.putObject("my-bucketname", "my-objectname", inputStream, options);
```
