### ISSUE TITLE
I can not upload file with putObject

### ISSUE THREAD

**Issue by leonardwu** [minio/minio-java#847]
```
private void init() {
    try {
      minioClient = new MinioClient(configuration.getUrl(), configuration.getAccessKey(), configuration.getSecretKey());
    } catch (InvalidEndpointException | InvalidPortException e) {
      log.error("Minio init failed.", e);
      Assert.notNull(null, "Minio init failed.");
    }
  }

  private String bucket = configuration.getBucket();

  public boolean saveFile(InputStream is, String name, String type) {
    Assert.notNull(is, "Inputstream MUST BE NOT null.");
    try {
      if(minioClient.bucketExists(bucket)) {
        log.info("Bucket is ready");
      } else {
        minioClient.makeBucket(bucket);
      }
      log.info(minioClient.getBucketPolicy(bucket));
      minioClient.putObject(bucket, name, is, Long.valueOf(is.available()), null, null, type);
      is.close();
    } catch (NoSuchAlgorithmException | IOException | InvalidKeyException | XmlPullParserException | MinioException e) {
      log.error("File upload failed.", e);
      return false;
    }
    return true;
  }
```

file always 0 bytes, no some error log.

**Comment by harshavardhana** [comment]
>       minioClient.putObject(bucket, name, is, Long.valueOf(is.available()), null, null, type);

can you print `log.info(Long.valueOf(is.available()))`

**Comment by leonardwu** [comment]
This is about the size of this stream. For example, the image file size I used for testing is 4191.

**Comment by harshavardhana** [comment]
What I am saying is please log and then re-run the code and paste the output log here.

**Comment by leonardwu** [comment]
16:20:28.051 [main] INFO  MinioTest - size: 4961
16:20:28.674 [main] INFO  org.paboo.uranus.blobstorage.utils.MinioUtil - Bucket is ready
16:20:28.683 [main] INFO  org.paboo.uranus.blobstorage.utils.MinioUtil - {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:ListBucket","s3:ListBucketMultipartUploads","s3:GetBucketLocation"],"Resource":["arn:aws:s3:::uranus"]},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:AbortMultipartUpload","s3:DeleteObject","s3:GetObject","s3:ListMultipartUploadParts","s3:PutObject"],"Resource":["arn:aws:s3:::uranus/*"]}]}

because I have not some log,sorry.

this is my code: https://gitlab.com/Paboo/blobstorage

**Comment by balamurugana** [comment]
@leonardwu This is quite strange. We have many functional tests in minio-java and they work fine. The failure is most likely `Long.valueOf(is.available())` returning `0`.

The right way to do what's going on in `minio-java` to use `MinioClient.traceOn()` and `MinioClient.traceOff()` methods. Please enable `traceOn()` and share the log here.

**Comment by leonardwu** [comment]
17:12:29.020 [main] INFO  MinioTest - size: 4961

---------START-HTTP---------
GET /uranus?location= HTTP/1.1
Accept-Encoding: identity
Host: 10.100.1.2:7000
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200216T091229Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200216/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 128
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-02-07T23-28-16Z
Vary: Origin
X-Amz-Request-Id: 15F3D70E50592240
X-Xss-Protection: 1; mode=block
Date: Sun, 16 Feb 2020 09:12:30 GMT

----------END-HTTP----------
---------START-HTTP---------
HEAD /uranus HTTP/1.1
Accept-Encoding: identity
Host: 10.100.1.2:7000
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200216T091229Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200216/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO/RELEASE.2020-02-07T23-28-16Z
Vary: Origin
X-Amz-Request-Id: 15F3D70E52316258
X-Xss-Protection: 1; mode=block
Date: Sun, 16 Feb 2020 09:12:30 GMT

----------END-HTTP----------
17:12:29.522 [main] INFO  org.paboo.uranus.blobstorage.utils.MinioUtil - Bucket is ready
---------START-HTTP---------
GET /uranus?policy= HTTP/1.1
Accept-Encoding: identity
Host: 10.100.1.2:7000
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200216T091229Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200216/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Content-Security-Policy: block-all-mixed-content
Vary: Origin
X-Amz-Request-Id: 15F3D70E52710174
X-Xss-Protection: 1; mode=block
Date: Sun, 16 Feb 2020 09:12:30 GMT
Content-Length: 397
Content-Type: text/plain; charset=utf-8

----------END-HTTP----------
17:12:29.529 [main] INFO  org.paboo.uranus.blobstorage.utils.MinioUtil - {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:ListBucket","s3:ListBucketMultipartUploads","s3:GetBucketLocation"],"Resource":["arn:aws:s3:::uranus"]},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:AbortMultipartUpload","s3:DeleteObject","s3:GetObject","s3:ListMultipartUploadParts","s3:PutObject"],"Resource":["arn:aws:s3:::uranus/*"]}]}
---------START-HTTP---------
PUT /uranus/zjKFMVxf3sODJ7Oz8dBy6vba56R5cpWHPP0q5TYe7EE%3D HTTP/1.1
Content-Type: image/png
Accept-Encoding: identity
Host: 10.100.1.2:7000
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200216T091229Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200216/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
ETag: "d65feb6e704f11cb749719dd3cdd1609-1"
Server: MinIO/RELEASE.2020-02-07T23-28-16Z
Vary: Origin
X-Amz-Request-Id: 15F3D70E530DA894
X-Xss-Protection: 1; mode=block
Date: Sun, 16 Feb 2020 09:12:30 GMT

----------END-HTTP----------


I  think the right way is SDK got inputstram size

**Comment by balamurugana** [comment]
@leonardwu 
```
---------START-HTTP---------
PUT /uranus/zjKFMVxf3sODJ7Oz8dBy6vba56R5cpWHPP0q5TYe7EE%3D HTTP/1.1
Content-Type: image/png
Accept-Encoding: identity
Host: 10.100.1.2:7000
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200216T091229Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20200216/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=REDACTED
```
By looking above trace, `putObject()` got zero sized input stream by, when size > 0, `STREAMING-AWS4-HMAC-SHA256-PAYLOAD` is used instead of sha256 hash `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`.

```bash
$ echo -n | sha256sum
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
```
You would need to fix your code why you are getting zero sized input stream.

**Comment by leonardwu** [comment]
no no no inputstream is not zero,I check before calling that method.

**Comment by balamurugana** [comment]
@leonardwu The trace is very clear in `minio-java` that it got zero sized input stream. You would need to investigate further why the stream got truncated before getting control into `minio-java`.

**Comment by leonardwu** [comment]
I'm pretty sure the input stream is not 0 sized, and I think truncation is a bug in your SDK. Because your code is so bad I don't know how to better locate the problem.

**Comment by harshavardhana** [comment]
> I'm pretty sure the input stream is not 0 sized, and I think truncation is a bug in your SDK. Because your code is so bad I don't know how to better locate the problem.

Let us be civilized @leonardwu - just looked at your code clearly you have a bug https://gitlab.com/Paboo/blobstorage/-/blob/master/src/main/java/org/paboo/uranus/blobstorage/controller/FileController.java#L51 

You reading the inputStream entirely before sending to `putObject()` - I also added log which I clearly asked you to do 

```diff
--- a/src/main/java/org/paboo/uranus/blobstorage/utils/MinioUtil.java
+++ b/src/main/java/org/paboo/uranus/blobstorage/utils/MinioUtil.java
@@ -71,7 +71,7 @@ public class MinioUtil {
       } else {
         minioClient.makeBucket(bucket);

       }
-      log.info(minioClient.getBucketPolicy(bucket));
+      log.info(Long.valueOf(is.available()).toString());
       minioClient.putObject(bucket, name, is, Long.valueOf(is.available()), null, null, type);
       is.close();
     } catch (NoSuchAlgorithmException | IOException | InvalidKeyException | XmlPullParserException | MinioException e) {
```

And here is the log
```
14:46:28.637 [qtp1407083101-22] INFO  org.paboo.uranus.blobstorage.utils.MinioUtil - 0
```

**So please fix your code** - closing this issue.

**Comment by leonardwu** [comment]
Oh no,I'm not use this method for test.And no matter how I get the length, your putObject is invalid.

**Comment by harshavardhana** [comment]
Then please update the real code / updated code @leonardwu in your project for us to help you. 

So please share the project repo once more with updated code.

**Comment by dingjs** [comment]
InputStream.available may not be the accurate size. Here is the docs of InputStream.available

> Returns an **estimate** of the number of bytes that can be read (orskipped over) from this input stream without blocking by the nextinvocation of a method for this input stream. The next invocationmight be the same thread or another thread. A single read or skip of thismany bytes will not block, but may read or skip fewer bytes.
