### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by dev-convo** [minio/minio-java#849]
Getting this error while trying to upload a file with server side encryption with customer key. 

> java.net.ProtocolException: unexpected end of stream
okhttp3.internal.http1.Http1Codec$FixedLengthSink.close(Http1Codec.java:318)
okio.ForwardingSink.close(ForwardingSink.java:47)
okio.RealBufferedSink.close(RealBufferedSink.java:248)
okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
okhttp3.RealCall.execute(RealCall.java:93)

**Comment by kannappanr** [comment]
@dev-convo Can you please provide a sample code for us to reproduce the issue? Also, are you connecting to S3 with TLS enabled?

**Comment by goeh** [comment]
I get the same exception on the same row. I'm not using TLS or encryption. I can reproduce with Minio server running in testcontainers on my Mac. Unfortunately I cannot share the application code. I will try to create a simpler test-case but it will take a few weeks before I find time.

**Comment by goeh** [comment]
I'm not 100% sure yet, but I suspect my problem occurs when I try to overwrite an existing object with putObject(). Creating the object works. But the second putObject() with the same bucket+filename fails.

**Comment by goeh** [comment]
Something was wrong on my side. When i sent null instead of content length to putObject, then updates (overwrites) started to work again. That lead me to track down a bug in my reactive java code that somehow mixed up content length for create and update. After fixing that bug I re-added length parameter to putObject() and everything still works. So it was my fault (as usual).

**Comment by balamurugana** [comment]
As per previous comment, closing this issue.
