### ISSUE TITLE
GCS Minio Client InvalidResponseException

### ISSUE THREAD

**Issue by rajivml** [minio/minio-java#851]
HI,

I am exploring querying GCS through Minio java client, but the response headers content type which GCS is returning and what Minio client is expecting are different.

GCS is returning: application/xml;utf-8 
Minio is Expecting: application/xml

As a result, Minio client is throwing InvalidResponseException and not processing the XML returned

```
   // Error in case of Non-XML response from server
        if (!("application/xml".equals(response.headers().get("content-type")))) {
          throw new InvalidResponseException();
        }
```

Please let me know how can i fix this. 

Thanks & Regards,
Rajiv

**Comment by kannappanr** [comment]
@rajivml instead of `equals` can you please send a PR that checks for `contains` or `starts-with` ?

**Comment by balamurugana** [comment]
Current release handles this case of content-type header.
