### ISSUE TITLE
MinIO Notification URL encoding

### ISSUE THREAD

**Issue by J11522** [minio/minio-java#856]
When running the example ListenBucketNotification we can observe the following issue:

1.  Create a sub-directory, e.g. test
1.  Upload a file to this directory, e.g. foo

- The Java Client reports `buckettest/test%2Ffoo has been created`
- The command line client reports `ObjectCreated https://play.min.io/buckettest/test/foo`

Now, if I want to download the file straight from the event I cannot use the object key, as this yields the following error:
`code=NoSuchKey, message=The specified key does not exist., bucketName=buckettest, objectName=test%2Ffoo, resource=/buckettest/test%2Ffoo`

In the mc we use QueryUnescape to unescape the response:
https://github.com/minio/mc/blob/master/cmd/client-s3.go#L598

The Java client should do similar

**Comment by harshavardhana** [comment]
It is your responsibility to Unescape @J11522 - as per AWS S3 specification event notification object name should be URL escaped. `mc` unescapes this automatically like an application should.
