### ISSUE TITLE
Sporadic failure of multipart putObject call

### ISSUE THREAD

**Issue by bambulin** [minio/minio-java#869]
Hi there, I'm using minio java client to upload larger files (hundreds of MB each) to S3 server (Exoscale). I experience a sporadic issue when uploading these files when server returns 408 Request Timeout for some of the multipart PUT calls. According to Exoscale suport this happens when there are a lot of multipart connections open in parallel and that some of them do not exchange data for a long time (30s actually). 
My question is if there is a mechanism how to prevent such a state. Is there any configuration how to limit the number of paralel connections of multipart upload, or make them sequential? Or any way how to prevent this?

I use the client as follows:
```
MinioClient minioClient = new MinioClient(config.getS3Endpoint(), config.getS3AccessKey(), config.getS3SecretKey());
client.putObject(resource.getBucket(), resource.getObjectName(), resource.getLocalDataFile().toString(), null, null, null, MediaType.APPLICATION_OCTET_STREAM);
```

I don't use any parallelism, all the files are uploaded sequentially - no concurrent calls of `client.putObject()`. 

here's the error log:

```
ErrorResponse(code=RequestTimeout, message=No data received during the last 30 secs, bucketName=wb-serve-file-v3, objectName=null, resource=null, requestId=90c10ecf-c763-4cd8-b9eb-4b986dc4d241, hostId=90c10ecf-c763-4cd8-b9eb-4b986dc4d241)
request={method=PUT, url=https://sos-ch-dk-2.exo.io/wb-serve-file-v3/resolver-1193.zip?uploadId=a4b99db9-a9b1-4073-92d5-5d7ccb0d56f4&partNumber=8, headers=Content-MD5: *****
Host: sos-ch-dk-2.exo.io
User-Agent: MinIO (amd64; amd64) minio-java/dev
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20200316T162229Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200316/ch-dk-2/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=server: nginx
date: Mon, 16 Mar 2020 16:22:59 GMT
content-type: application/xml
content-length: 292
x-amz-bucket-region: ch-dk-2
x-amz-request-id: 90c10ecf-c763-4cd8-b9eb-4b986dc4d241
x-amzn-requestid: 90c10ecf-c763-4cd8-b9eb-4b986dc4d241
x-amz-id-2: 90c10ecf-c763-4cd8-b9eb-4b986dc4d241
}

	at io.minio.MinioClient.executeReq(MinioClient.java:1204)
	at io.minio.MinioClient.execute(MinioClient.java:1066)
	at io.minio.MinioClient.executePut(MinioClient.java:1430)
	at io.minio.MinioClient.executePut(MinioClient.java:1452)
	at io.minio.MinioClient.putObject(MinioClient.java:4511)
	at io.minio.MinioClient.putObject(MinioClient.java:4608)
	at io.minio.MinioClient.putObject(MinioClient.java:3879)
	...
```

**Comment by kannappanr** [comment]
You should be able to specify part size and if you use a large enough part size, you might avoid or reduce the number of concurrent calls

**Comment by bambulin** [comment]
That would be nice - but how? Can't find any configuration that allows it, documentation says nothing about such a possibility.

**Comment by kannappanr** [comment]
Please look at http://minio.github.io/minio-java/io/minio/PutObjectOptions.html , http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.lang.String-io.minio.PutObjectOptions- and http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.io.InputStream-io.minio.PutObjectOptions- Please feel free to reach out to us at https://slack.min.io for further questions
