### ISSUE TITLE
Remove objects which are older than specific date

### ISSUE THREAD

**Issue by vinqin** [minio/minio-java#875]
**Problem:**
How to remove objects which are older than specific date?

**Environment:**
server: 2020-03-19T21:49:00Z
java-client: 6.0.13

**Expectation:**
The same function of such:
```bash
$ mc rm --recursive --force --older-than 90d s3/jazz-songs
```

**Comment by harshavardhana** [comment]
minio-java SDK implements APIs, not higher-level functionality like what you want in a tool, it is up to you to write such tools using this SDK @vinqin
