### ISSUE TITLE
The difference between the request time and the server's time is too large

### ISSUE THREAD

**Issue by knursultan** [minio/minio-java#877]
Hi!

I wrote nodejs app.
The task is to compress all files in minio.
I get listObjects by this method listObjectsV2. Then compress and put it. The size of the whole objects is over 60Gb. 
I got this error if I don't write get object by prefix
`mc.listObjectsV2('bucket', '', true, '')`

If I wrote by prefix, it works
`mc.listObjectsV2('bucket', 'prefix', true, '')`

The server and local machine Time is same

**Comment by kannappanr** [comment]
@knursultan looks like you are using `minio-js`. I cannot determine what is wrong with the information provided. If you can provide the error return by the server, we can take a look at it. Also, you can paste the trace log from client side and server side. Closing this issue right now. Please provide all the information and open the issue at https://github.com/minio/minio-js/issues/new
