### ISSUE TITLE
Unable to create bucket when updating java client from 6.x.x to 7.0.0

### ISSUE THREAD

**Issue by vasilievip** [minio/minio-java#881]
Error:
`
error occurred
ErrorResponse(code = MalformedXML, message = The XML you provided was not well-formed or did not validate against our published schema.
, bucketName = my-test-bucket, objectName = null, resource = /my-test-bucket, requestId = 15FFDB8A67106604, hostId = 96fa3866-7ee6-4546-87d9-4283e3def6c3)
request={method=PUT, url=https://play.min.io/my-test-bucket, headers=Host: play.min.io
`

Code:

https://github.com/testcontainers/testcontainers-spring-boot/blob/develop/embedded-minio/src/test/java/com/playtika/test/minio/EmbeddedMinioBootstrapConfigurationTest.java#L43

Change:
https://github.com/testcontainers/testcontainers-spring-boot/pull/228

Build results:
https://circleci.com/gh/testcontainers/testcontainers-spring-boot/1020?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kannappanr** [comment]
@vasilievip I tried the example https://raw.githubusercontent.com/minio/minio-java/master/examples/MakeBucket.java against both AWS S3 and Play and both of them work with version 7.0.0

**Comment by vasilievip** [comment]
Ok, by removing "region" parameter from client constructor I've got test passed as well.

https://github.com/testcontainers/testcontainers-spring-boot/pull/228/files#diff-b6877828dafe1a78cb3763f47f811d33R104

What is correct setup for region then?
It passed to container via MINIO_REGION and then if I set non any value for client - client can't connect.

**Comment by balamurugana** [comment]
> What is correct setup for region then?
> It passed to container via MINIO_REGION and then if I set any value for client - client can't connect.

Can you enable `MinioClient.traceOn()` and share the output?

**Comment by vasilievip** [comment]
`
---------START-HTTP---------
PUT /my-test-bucket HTTP/1.1
Host: localhost:32855
Accept-Encoding: identity
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
Content-MD5: DA38F+K3csWr9tiTmrJC2g==
x-amz-content-sha256: 0676e06a51e2a0d8eb1482f44c2a4876ed706cf39abb817dcfd953efb5aef09a
x-amz-date: 20200327T082226Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200327//s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*


io.minio.messages.CreateBucketConfiguration@5db6b845
HTTP/1.1 400
Accept-Ranges: bytes
Content-Length: 355
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-03-25T07-03-04Z
Vary: Origin
X-Amz-Request-Id: 16001B8996AEA5D2
X-Xss-Protection: 1; mode=block
Date: Fri, 27 Mar 2020 08:22:26 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema.</Message><BucketName>my-test-bucket</BucketName><Resource>/my-test-bucket</Resource><RequestId>16001B8996AEA5D2</RequestId><HostId>116582d0-7f46-432c-8616-bf574f2c6b4e</HostId></Error>
----------END-HTTP----------

error occurred
ErrorResponse(code = MalformedXML, message = The XML you provided was not well-formed or did not validate against our published schema.
, bucketName = my-test-bucket, objectName = null, resource = /my-test-bucket, requestId = 16001B8996AEA5D2, hostId = 116582d0-7f46-432c-8616-bf574f2c6b4e)
request={method=PUT, url=http://localhost:32855/my-test-bucket, headers=Host: localhost:32855
Accept-Encoding: identity
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
Content-MD5: DA38F+K3csWr9tiTmrJC2g==
x-amz-content-sha256: 0676e06a51e2a0d8eb1482f44c2a4876ed706cf39abb817dcfd953efb5aef09a
x-amz-date: 20200327T082226Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200327//s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=Accept-Ranges: bytes
Content-Length: 355
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-03-25T07-03-04Z
Vary: Origin
X-Amz-Request-Id: 16001B8996AEA5D2
X-Xss-Protection: 1; mode=block
Date: Fri, 27 Mar 2020 08:22:26 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:1182)
`
