### ISSUE TITLE
Usage of Simple Framework for XML Parsing -- Library is old an unmaintained.  Minio ALready Uses JAckson

### ISSUE THREAD

**Issue by thecatwhisperer** [minio/minio-java#886]
### Summary 
Recent contribution (https://github.com/minio/minio-java/commit/d97252674ecce371e7939eab850157ecf602a1f7#diff-c197962302397baf3a4cc36463dce5ea) added the Simple Framework library.  This library is used to marshall and unmarshall XML, but is very old (last updated Jul 08, 2013) and is not currently maintained.  

Minio's build already includes the highly used and maintained Jackson library for this purpose.  I would _strongly_ recommend that simple framework be removed and its needed functionality be replaced with the existing Jackson library's capabilities.  

re: https://github.com/minio/minio-java/blob/master/build.gradle#L51
and: https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/Xml.java

**Comment by kannappanr** [comment]
@thecatwhisperer Thanks for reporting this issue. We will take a look into it.

**Comment by balamurugana** [comment]
Previously we were using `google-http-client-xml` for XML parsing which is limiting to use basic types only. To move to better framework, we considered to support android App size. Hence `SimpleXML` is the choice. In my evaluation, Jackson (We use it as JSON framework now) as XML framework had problems in some cases.

If we see issues with `SimpleXML` or more requests to change XML framework, we are open to do.

**Comment by thecatwhisperer** [comment]
> If we see issues with `SimpleXML`

The main issue is it is a legacy library with little to no support.  This is an issue for enterprise organizations such as ourselves.  This kindof library will be flagged by our internal security reviews.

**Comment by balamurugana** [comment]
> > If we see issues with `SimpleXML`
> 
> The main issue is it is a legacy library with little to no support. This is an issue for enterprise organizations such as ourselves. This kindof library will be flagged by our internal security reviews.

Do I understand this as `SimpleXML` is considered as a security issue at your side?

**Comment by thecatwhisperer** [comment]
Yes. 

- No active development for over 6 years.  
- 1 release, 1 contributor since its move to Github
- test in the project are very sparse.

**Comment by kannappanr** [comment]
@thecatwhisperer We will discuss internally and get back to you

**Comment by harshavardhana** [comment]
SimpleXML is a feature complete library, Jackson XML while is actively maintained has consistent security issues being reported either due to complex XML feature functionality that they need to support.

SimpleXML serves this purpose it is simple enough and serves the right functionality for us, I propose we take over maintainence of SimpleXML and the move/fork the dependency into minio-java project itself.

**Comment by thecatwhisperer** [comment]
> I propose we take over maintainence of SimpleXML and the move/fork the dependency into minio-java project itself.

That would alleviate concerns over it being maintained.  After digging into how and why you are using the project, I see how much work it would be to replace too.

**Comment by harshavardhana** [comment]
This is fixed and have made a release 7.1.0
