### ISSUE TITLE
Set custom regions and endpoints

### ISSUE THREAD

**Issue by Arteneko** [minio/minio-java#913]
We can't currently use custom S3-compatible endpoints if they're not either minio or AWS, which sucks, as, for example, [Scaleway](https://www.scaleway.com/en/docs/object-storage-feature/) is s3-compatible, and is compatible with the official AWS SDK.

It would be better to let developers choose *their* endpoints and regions.

**Comment by balamurugana** [comment]
Can you confirm whether `MinioClient minioClient = new MinioClient("https://s3.nl-ams.scw.cloud", "MY-ACCESS-KEY", "MY-SECRET-KEY", "nl-ams");` is working or not?

`MinioClient` object can be created in various ways and [this constructor](http://minio.github.io/minio-java/io/minio/MinioClient.html#MinioClient-java.lang.String-int-java.lang.String-java.lang.String-java.lang.String-boolean-okhttp3.OkHttpClient-) provides much control to users.
```java
MinioClient minioClient = new MinioClient("s3.nl-ams.scw.cloud", 443,
     "MY-ACCESS-KEY", "MY-SECRET-KEY", "nl-ams", true, customHttpClient);
```

**Comment by Arteneko** [comment]
I did not find about those constructors, my bad, I should've been more careful with my research.

I'll open an issue to add Scaleway as known endpoints, then
