### ISSUE TITLE
Add Scaleway S3-compatible storage endpoints

### ISSUE THREAD

**Issue by Arteneko** [minio/minio-java#914]
There is a list of known endpoints for AWS [here](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/AwsS3Endpoints.java).

It'd be neat to also have [Scaleway endpoints](https://www.scaleway.com/en/docs/object-storage-feature/).

**Comment by balamurugana** [comment]
PR https://github.com/minio/minio-java/pull/900 removes `AwsS3Endpoints.java` and having `AwsS3Endpoints.java` is purely an internal entity which may/may not present and does not affect your functionality.

You are free to reopen this issue if minio-java is not working with Scaleway.
