### ISSUE TITLE
ListObjects fails if Owner element is absent in response

### ISSUE THREAD

**Issue by selfenergy** [minio/minio-java#920]
The listObjects command fails if the ListBucketResult/Contents/Owner element is missing in the response. The element is according to [the amazon s3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html#AmazonS3-Type-Object-Owner) optional.
Furthermore, there seems to be no public accessible method to call the internal listObjectsV2 method with fetchOwner=true. Or am I mistaken?
This behaviour has been introduced with version 7.0.0.

```
org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name="Owner", type=void.class, data=false, required=true) on field 'owner' private io.minio.messages.Owner io.minio.messages.Item.owner for class io.minio.messages.Item at line 1
```

**Comment by balamurugana** [comment]
> The listObjects command fails if the ListBucketResult/Contents/Owner element is missing in the response. The element is according to [the amazon s3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html#AmazonS3-Type-Object-Owner) optional.

Could you help here that PR https://github.com/minio/minio-java/pull/921 works?



>  Furthermore, there seems to be no public accessible method to call the internal listObjectsV2 method with fetchOwner=true. Or am I mistaken?

Currently there is no direct option in public methods, but you could use [protected listObjectsV2()](http://minio.github.io/minio-java/io/minio/MinioClient.html#listObjectsV2-java.lang.String-java.lang.String-java.lang.String-boolean-java.lang.Integer-java.lang.String-java.lang.String-boolean-) by inheriting `MinioClient` for custom listing.

If public methods with `fetchOwner=true` is needed, you could use this [listObjects()](http://minio.github.io/minio-java/io/minio/MinioClient.html#listObjects-java.lang.String-java.lang.String-boolean-boolean-) with `useVersion1=true`.

We are also working on builder classes for method arguments. In future there will be `listObjects(ListObjectsArgs args)` where `fetchOwner` will be an argument in `ListObjectsArgs`.

**Comment by selfenergy** [comment]
Thanks for the quick response and the feedback / advice :)
I can confirm that PR #921 fixes this issue.
