### ISSUE TITLE
Etag differs for the same file uploaded by different clients

### ISSUE THREAD

**Issue by looksworking** [minio/minio-java#923]
If I use console mc client it saves ETag property equal to MD5 sum of the file like
```da853c5826b798b82320e42024d97837```
 but java client with
```putObject(String bucketName, String objectName, InputStream stream, PutObjectOptions options)```
saves it differently, like
```007a81efa15c41b717e353868f5952e1-1```
Why does it happen and how can I make them to be the same if file contents doesn't differ?
Previous versions of Java client (6.0.x) also saved ETag as MD5 sum of a file, how can this behavior be restored?

**Comment by balamurugana** [comment]
All methods of `public void putObject()` are using multi-part as default and part size is controlled by `PutObjectOptions`.

If non-multi-part `putObject()` is wanted, you could use [protected String putObject()](http://minio.github.io/minio-java/io/minio/MinioClient.html#putObject-java.lang.String-java.lang.String-java.lang.Object-int-java.util.Map-) by inheriting `MinioClient` to have fine control on uploads.

**Comment by looksworking** [comment]
But in this case I won't be able to use InputStream for file uploads?

**Comment by balamurugana** [comment]
Just wrap with `new BufferedInputStream(is)`

**Comment by looksworking** [comment]
Thank you, works fine!
