### ISSUE TITLE
How to specify size and other parameters in the bucket creation ?

### ISSUE THREAD

**Issue by alwayscodemonkey** [minio/minio-java#925]
Is there a way to specify the configuration parameters for `makeBucket` method ? 

```
makeBucket(String bucketName, String region)
public void makeBucket(String bucketName, String region) [Javadoc]
```
How to pass size and other parameters?

**Comment by kannappanr** [comment]
There is no size parameters in makeBucket API. MinIO implements S3 APIs and there is no such thing in AWS S3. Please feel free to reach out to us at https://slack.min.io for further such questions
