### ISSUE TITLE
S3 Object Operation returns HTTP 307 Temporary redirect

### ISSUE THREAD

**Issue by aalex21** [minio/minio-java#926]
Details: 
1. When new S3 buckets are created (especially eu regions), the DNS propagation time is around 24 hrs.
2. When a minio client is created with a region (ex: eu-west-3), the S3 Object operations are suppose to send to the specific S3 region end point. Since the region specific end point mapping is not defined in AwsS3Endpoints.java (for eu-west-3), the request goes to global S3 end point.
3. The result will be 307 Temporary Redirect HTTP response ("MIN076", "Temporary redirect due to DNS updates in progress" ) . (For a new bucket created)

Solution:
1. If the request can be send to the region specific S3 end point, then request can be processed successfully
2. The following S3 region specific endpoints are not mapped in AwsS3Endpoints.java - eu-west-3, eu-north-1, eu-south-1, ap-northeast-3, ap-east-1, af-south-1

**Comment by balamurugana** [comment]
You can also try this PR https://github.com/minio/minio-java/pull/900 which works for any region. There is no AWS region mapping required logically.

**Comment by aalex21** [comment]
Looks like PR #900 changes can solve this issue ... Waiting for an expected time this PR available in master and make a release ...
