### ISSUE TITLE
Deploying minio-7.0.2-all.jar (Java SDK) on Jboss/Wildfly servers the server start up fails as the minio-7.0.2-all.jar has javax related classes

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio-java#940]
Hi, While deploying minio-7.0.2-all.jar (Java SDK) on Jboss/Wildfly servers the server start up fails as the minio-7.0.2-all.jar has javax related classes (Error : Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "org.apache.xpath.jaxp.XPathImpl.evaluate(Ljava/lang/String;Lorg/xml/sax/InputSource;Ljavax/xml/namespace/QName;)) And why does minio-7.0.2-all.jar contains javax package when the same is present in JDK?

**Comment by balamurugana** [comment]
@PSHREYASHOLLA you would need to use `minio-7.0.2.jar` which doesn't come with any dependency classes (you would need to resolve by your maven/gradle) whereas `minio-7.0.2-all.jar` is a handy jar contains all dependent classes and it can be used standalone.

**Comment by kannappanr** [comment]
@PSHREYASHOLLA Closing this issue as answered. Please feel free to reach out to us if you have further questions.

**Comment by PSHREYASHOLLA** [comment]
But with only minio-7.0.2.jar, even the code to get client,
 MinioClient minioClient = new MinioClient("https://play.min.io", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"); fails Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap.

**Comment by balamurugana** [comment]
@PSHREYASHOLLA Below are dependencies you would need to add in your build system
```
        compile "com.carrotsearch.thirdparty:simple-xml-safe:2.7.1"
        compile "com.google.guava:guava:25.1-jre"
        compile "com.squareup.okhttp3:okhttp:3.13.1"
        compile "com.squareup.okio:okio:1.17.2"
        compile "com.fasterxml.jackson.core:jackson-annotations:2.10.3"
        compile "com.fasterxml.jackson.core:jackson-core:2.10.3"
        compile "com.fasterxml.jackson.core:jackson-databind:2.10.3"
        compile 'com.github.spotbugs:spotbugs-annotations:4.0.0'
        compile 'net.jcip:jcip-annotations:1.0'
        compile 'com.google.code.findbugs:jsr305:3.0.2'
```
