### ISSUE TITLE
Error in version 3.0.10

### ISSUE THREAD

**Issue by qiumingben** [minio/minio-java#943]
The deletion method should be: minioClient.removeObject()，not minioClient.removeObjects()

**Comment by kannappanr** [comment]
@qiumingben The latest version is `7.0.2`, can you please try that?

**Comment by balamurugana** [comment]
> The deletion method should be: minioClient.removeObject()，not minioClient.removeObjects()

It was decided to have multi-object delete as `minioClient.removeObjects()`.
