### ISSUE TITLE
Unable to locate import io.minio.ListObjectsArgs; in minio-7.0.2-all.jar

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio-java#951]
Unable to locate import io.minio.ListObjectsArgs; in minio-7.0.2-all.jar

**Comment by balamurugana** [comment]
@PSHREYASHOLLA How did you get the jar? Is it your own build? Please come to https://slack.min.io/ and catch me by `@bala`

**Comment by PSHREYASHOLLA** [comment]
No downloaded it from Minio website https://docs.min.io/docs/java-client-quickstart-guide.html

**Comment by balamurugana** [comment]
@PSHREYASHOLLA `io.minio.ListObjectsArgs` was added later than release `v7.0.2`. I would like you to join MinIO slack channel for further assistance.

**Comment by PSHREYASHOLLA** [comment]
But in website the latest jar that gets downloaded is SDK minio-7.0.2-all.jar. If the class file is not present in that version,why is the in JAVA SDK API page shows that. Document attached image,
![image](https://user-images.githubusercontent.com/19671054/82752589-aa139f00-9ddc-11ea-9cf7-67476ce2fd5b.png) Please let me know if I am missing something here?

**Comment by balamurugana** [comment]
@PSHREYASHOLLA As mentioned in `slack`, the documentation has a problem. You would need to refer examples/docs in https://github.com/minio/minio-java/tree/7.0.2. Particularly https://github.com/minio/minio-java/blob/7.0.2/docs/API.md
