### ISSUE TITLE
Using a newer version of okhttp

### ISSUE THREAD

**Issue by f-lombardo** [minio/minio-java#952]
Using minio-java with IBM JDK on AS400 I get this error:
https://github.com/square/okhttp/pull/3218
(See also https://github.com/kubernetes-client/java/issues/655)

Would it be possible to use a newer version of okhttp?

Thank you

**Comment by balamurugana** [comment]
Yes. I will check on okhttp v3.14.9 and use that.

**Comment by f-lombardo** [comment]
Very good, thank you!
