### ISSUE TITLE
Offer a way to create and return OutputStreams

### ISSUE THREAD

**Issue by atrauzzi** [minio/minio-java#956]
Right now it looks like the SDK only accepts input streams which results in extra boilerplate in application code looking to write data by streaming it rather than holding it in memory.

The Azure blob storage APIs offer something along these lines via a method called `blobOutputStream`. Basically all metadata is prepared up front and then a method is called to return a stream.

That stream can then be passed back to the caller.

**Comment by balamurugana** [comment]
@atrauzzi Could you point me the API in Azure? I will take a look how it can be adopted.

**Comment by atrauzzi** [comment]
For sure!

Take a look here: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlockBlobClient.java#L79-L146

I really like their API for this kind of functionality.  Requiring all the blob/object metadata upfront means that write operations can be completed independently of providing the metadata itself.

**Comment by balamurugana** [comment]
Thanks. We will check the possibility.

**Comment by mleinweber-dt** [comment]
i am using piped input stream for this purpose, works quite ok

**Comment by balamurugana** [comment]
Yes. This is what I recommended in slack and as per S3 specification, stream size must be known in prior. Hence this feature request doesn't make sense.

**Comment by mleinweber-dt** [comment]
i am doing the following:
```PipedOutputStream pos = new PipedOutputStream();
    PipedInputStream pis = new PipedInputStream(pos, 8192);
    BufferedInputStream bufferedInputStream = new BufferedInputStream(pis);
    BufferedOutputStream bufferedOutputStream = new BufferedOutputStream(pos);
    PutObjectArgs putObjectArgs =
        PutObjectArgs.builder().bucket(bucketName).object(objectName).stream(
                bufferedInputStream, -1, ObjectWriteArgs.MIN_MULTIPART_SIZE)
            .build();
    Future<?> future = CompletableFuture.runAsync(
            () -> {
              try {
                minioClient.putObject(putObjectArgs);
              } catch (Exception e) {
                log.error("Error during minio write; Leaked", e);
              }
            });
    return new S3FutureOutputStream(bufferedOutputStream, future);
```
S3FutureOutputStream does a future.get before close. I added the BufferedStreams because of PipedinputStreams  errored with Read end dead.

Actually this works pretty well in my integration tests.

**Comment by balamurugana** [comment]
Awesome. Closing this issue ATM.

**Comment by mingtiao13** [comment]
Hello, I also have such a demand. I need to return an output stream to the caller. I saw that you solved it through the above method and closed the problem with the script. I don't know how it is written. Can you tell me?

**Comment by mleinweber-dt** [comment]
Here we go... something like

```
import java.io.IOException;
import java.io.OutputStream;
import java.util.concurrent.Future;

public class S3FutureOutputStream extends OutputStream {

  private final OutputStream wrapped;
  private final Future<?> future;

  public S3FutureOutputStream(OutputStream outputStream, Future<?> future) {
    wrapped = outputStream;
    this.future = future;
  }

  @Override
  public void write(int b) throws IOException {
    wrapped.write(b);
  }

  @Override
  public void write(byte[] b) throws IOException {
    wrapped.write(b);
  }

  @Override
  public void write(byte[] b, int off, int len) throws IOException {
    wrapped.write(b, off, len);
  }

  @Override
  public void flush() throws IOException {
    wrapped.flush();
  }

  @Override
  public void close() throws IOException {
    wrapped.close();
    try {
      future.get();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
}

```

**Comment by mingtiao13** [comment]
Thanks for your reply, it helped me a lot
