### ISSUE TITLE
Create empty folder example

### ISSUE THREAD

**Issue by duncanj** [minio/minio-java#969]
Resolved issues https://github.com/minio/minio/issues/2423 and https://github.com/minio/minio-java/issues/653 suggest that it's possible to create an empty folder via the Java client, by specifying an object name with a trailing slash, and ensuring the size is 0 bytes.   

Please could we have an example in the examples folder that demonstrates this?

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-java/pull/972
