### ISSUE TITLE
Signing issue in updateRegionCache

### ISSUE THREAD

**Issue by tkpjun** [minio/minio-java#973]
Specifically when using a https URL, there seems to be some kind of mismatch between the x-amz-content-sha256 value in the header and in the request signature. Header value is UNSIGNED-PAYLOAD, and as far as I could tell (didn't verify with debugging tools), the string "UNSIGNED-PAYLOAD" is hashed into the signature the same way as any regular sha256 hash would be. The problem can be circumvented by setting the client's region manually: then updateRegionCache is never called and other requests raise no exceptions about signatures not matching.

**Comment by vadmeste** [comment]
> The problem can be circumvented by setting the client's region manually

What problem are you trying to solve ? Are you seeing a signature mismatch error ? What is the S3 server that are you using ?

**Comment by balamurugana** [comment]
@tkpjun Please reopen this issue with appropriate information.
