### ISSUE TITLE
When will object tag operation support be released?

### ISSUE THREAD

**Issue by kensou97** [minio/minio-java#974]
Hi，i read the [Docs](https://docs.min.io/docs/java-client-api-reference.html) and find apis for object tag operation. But they are still unavailable in latest version 7.0.2. It seems that  #918 were just merged to master recently. So when will the next version be released?

**Comment by kannappanr** [comment]
@kensou97 We are adding/rewriting APIs to support versioning. We will make a release within the next couple of weeks.
