### ISSUE TITLE
minioClient.getObjectTags() method doesn't exist

### ISSUE THREAD

**Issue by danboliu** [minio/minio-java#977]

**Comment by danboliu** [comment]
Looks like there are lots of methods like .getObjectTags() doesn't exists in the latest Minio lib 7.0.2.

Any ideas?

**Comment by kannappanr** [comment]
getObjectTags is not part of release `7.0.2`

https://javadoc.io/doc/io.minio/minio/latest/index.html has the latest documentation

**Comment by balamurugana** [comment]
As we are in the process of fixing  https://docs.minio.io/docs/java-client-quickstart-guide.html and https://docs.minio.io/docs/java-client-api-reference.html, I recommend to refer correct documentation at  
https://github.com/minio/minio-java/blob/7.0.2/docs/API.md and http://minio.github.io/minio-java/

**Comment by danboliu** [comment]
Hi there

Does that mean that we don't have read/write object tagging capability at the moment? Which seems to be pretty common for S3 apis.

**Comment by balamurugana** [comment]
Those APIs are available in `master` not yet released.
