### ISSUE TITLE
can append object?

### ISSUE THREAD

**Issue by rookeyframe** [minio/minio-java#980]
can appends content to an existing object?

**Comment by nitisht** [comment]
no can not. There is no S3 API for that.

**Comment by balamurugana** [comment]
@rookeyframe you could do this with little tricks using [composeObject()](https://github.com/minio/minio-java/blob/release/docs/API.md#composeObject) by doing below steps
0. Consider you have `object1` to be appended.
1. Upload data to append as new object using `putObject()` as `object2`
2. Now use `composeObject()` to create appended object `object3` using `object1` and  `object2` as sources.
3. Do `copyObject()` from `object3` to `object1` and use `removeObject()` to remove temporary objects.

**Comment by rookeyframe** [comment]
append file or source file must be greater than 5M？

**Comment by balamurugana** [comment]
@rookeyframe Yep. That is limitation in the above trick (Actually it is S3 limitation).

**Comment by rookeyframe** [comment]
@balamurugana 
How to merge or append files smaller than 5M？

**Comment by balamurugana** [comment]
@rookeyframe You would need to download < 5MB object using `getObject()` as a file and append the file locally, then upload the file.

**Comment by rookeyframe** [comment]
@balamurugana
Many object storage vendors support object appending in the following ways

Name     Type        Description
append   String      Indicates that the object is uploaded by appending
position   Integer    Used to specify where to append writes

POST /<object-name>?append&position=<position> HTTP/1.1
Host: <bucket-name>.<zone-id>.qingstor.com
Date: <date>
Authorization: <authorization-string>

Can't SDK add similar support？

**Comment by harshavardhana** [comment]
> @balamurugana
> Many object storage vendors support object appending in the following ways
> 
> Name Type Description
> append String Indicates that the object is uploaded by appending
> position Integer Used to specify where to append writes
> 
> POST /?append&position= HTTP/1.1
> Host: ..qingstor.com
> Date:
> Authorization:
> 
> Can't SDK add similar support？

S3 API doesn't support append, you should use those vendors @rookeyframe if your requirement is append API.

**Comment by balamurugana** [comment]
@rookeyframe There is new release `8.0.0` comes with more methods available using inheritance. You could extend `MinioClient` and do your own `POST /?append&position= HTTP/1.1` for your custom S3 service.

**Comment by ssr7** [comment]
@rookeyframe 
I can upload chunk by chunk a big file into Minio . I consider a byte buffer with 5MB size(chunk size) and save it into Minio with objectId like ( `myfile_part1`,`my_file_part2` ,...)  and I continue this method for the rest of the bytes, and for the last chunk that might be less than 5 MB I could save it. After that, I compose all objects together with the name `my_file` and delete all parts. I tested for 1GB file and checked md5sum of original file and uploaded file that they are the same
