### ISSUE TITLE
Connect to multiple specified nodes of Distributed MinIO setup?

### ISSUE THREAD

**Issue by anton85bk** [minio/minio-java#983]
Hello. I wanted to ask you about ability of minio-java to connect to one of multiple specified nodes of Distributed MinIO setup?

What kind of approach can suite this task, can minio-java handle this, or I need some external tool for this?

Thanks and best regards.

**Comment by harshavardhana** [comment]
@anton85bk you should use load balancers against a common endpoint or use something like a sidecar load balancer like 

https://github.com/minio/sidekick
