### ISSUE TITLE
Java gets inputStream one byte less

### ISSUE THREAD

**Issue by pengweiwang** [minio/minio-java#985]
Java gets inputStream one byte less

**Comment by balamurugana** [comment]
Reopen this issue with complete detail.

**Comment by pengweiwang** [comment]
the code like this：
InputStream inputStream  = minioClient.getObject(request.getBucketName(), request.getFileName())
log.info("sieze[{}],available=[{}]",inputStream.read(),inputStream.available());

and i get the available is one byte less

**Comment by balamurugana** [comment]
@pengweiwang 
>  log.info("sieze[{}],available=[{}]",inputStream.read(),inputStream.available());

`inputStream.read()` reads one byte hence you are getting one byte less.  However `InputStream.available()` is not guaranteed to be equal to object size. You would need to read fully and check how many bytes you read (or is available in the stream).

**Comment by pengweiwang** [comment]
ok thanks
