### ISSUE TITLE
BucketNotification Issues

### ISSUE THREAD

**Issue by xz1996** [minio/minio-java#990]
I'm using 'io.minio:minio:7.0.2' in my spring project, and I also setup local minio server locally by docker image `minio/minio:RELEASE.2020-06-22T03-12-50Z`, the rabbitmq is the event destination, there are some issues that I want to know:

1.  Are `CloudFunctionConfiguration` and `TopicConfiguration`  not supported now? I found only `QueueConfiguration` could work in current java sdk.

2. What's the purpose of "id" in `NotificationCommonConfiguration`? There is no "setId" operation in the official docs <https://docs.min.io/docs/java-client-api-reference.html#setBucketNotification>, but if I ignore it, it will raise exceptions. The same issue to "filter" field, I have to do "setPrefixRule" or "setSuffixRule" so that it will generate a new filter and don't raise errors.

3. The behavior between using `mc event add` in minio client and java sdk to setBucketNotification is confusing. I firstly use `mc event add ...` to add a new notification on the relevant bucket, and get the notification by java sdk, it will also raise the exception:
    ```
    org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=Id, type=void, data=false, required=true) on field 'id' private java.lang.String io.minio.messages.NotificationCommonConfiguration.id
    ```
    Only I created it through java sdk, did I get the notification by java sdk successfully. I hope it can align their behavior between mc and java sdk in the future.
    
Finally, for the following code:

```java
NotificationConfiguration notificationConfiguration = minioClient.getBucketNotification("my-bucketname");
List<QueueConfiguration> queueConfigurationList = notificationConfiguration.queueConfigurationList();
```
If there are no any event list on the bucket, the `queueConfigurationList` is **null**. As far as I'm concerned, empty collection is better than null for the collection as the return result.

Looking forward to your reply, thanks.

**Comment by balamurugana** [comment]
> I'm using 'io.minio:minio:7.0.2' in my spring project, and I also setup local minio server locally by docker image `minio/minio:RELEASE.2020-06-22T03-12-50Z`, the rabbitmq is the event destination, there are some issues that I want to know:
> 
>     1. Are `CloudFunctionConfiguration` and `TopicConfiguration`  not supported now? I found only `QueueConfiguration` could work in current java sdk.
> 

No. They are not supported.

>     2. What's the purpose of "id" in `NotificationCommonConfiguration`? There is no "setId" operation in the official docs https://docs.min.io/docs/java-client-api-reference.html#setBucketNotification, but if I ignore it, it will raise exceptions. The same issue to "filter" field, I have to do "setPrefixRule" or "setSuffixRule" so that it will generate a new filter and don't raise errors.
> 

* There is (setId())[http://minio.github.io/minio-java/io/minio/messages/NotificationCommonConfiguration.html#setId-java.lang.String-] available. As `id` is optional; the example in https://docs.min.io/docs/java-client-api-reference.html#setBucketNotification doesn't have it.
* What exception are you getting for `id`?
* What exception are you getting for `filter`?

>     3. The behavior between using `mc event add` in minio client and java sdk to setBucketNotification is confusing. I firstly use `mc event add ...` to add a new notification on the relevant bucket, and get the notification by java sdk, it will also raise the exception:
>        ```
>        org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=Id, type=void, data=false, required=true) on field 'id' private java.lang.String io.minio.messages.NotificationCommonConfiguration.id
>        ```
>  

This is already fixed in `master` and we are planning to make a release soon.
      
>        
>        Only I created it through java sdk, did I get the notification by java sdk successfully. I hope it can align their behavior between mc and java sdk in the future.
> 

I think you are referring the above here.

> 
> Finally, for the following code:
> 
> ```java
> NotificationConfiguration notificationConfiguration = minioClient.getBucketNotification("my-bucketname");
> List<QueueConfiguration> queueConfigurationList = notificationConfiguration.queueConfigurationList();
> ```
> 
> If there are no any event list on the bucket, the `queueConfigurationList` is **null**. As far as I'm concerned, empty collection is better than null for the collection as the return result.
> 

This is available in `master`. Feel free to try `master` till we make a release.

> Looking forward to your reply, thanks.

**Comment by xz1996** [comment]
> What exception are you getting for id?
What exception are you getting for filter?

When I using mc to add notifications like ```mc event add <minio/bucket-name> <arn>```, it can work without "id" or "filter", so I take for granted that the java SDK can also work without "id" and "filter", but that's not the case. When I using it without "id", it will throw the exception:
```
org.simpleframework.xml.core.ElementException: Value for @org.simpleframework.xml.Element(name=Id, type=void, data=false, required=true) on field 'id' private java.lang.String io.minio.messages.NotificationCommonConfiguration.id is null in class io.minio.messages.QueueConfiguration
```

after setting id but without "filter":
```
org.simpleframework.xml.core.ElementException: Value for @org.simpleframework.xml.Element(name=Filter, type=void, data=false, required=true) on field 'filter' private io.minio.messages.Filter io.minio.messages.NotificationCommonConfiguration.filter is null in class io.minio.messages.QueueConfiguration
```
So I have to both set id and filter in the code, comparing with mc's behaviour, it's confusing, and there is no document to remind me of these things.

**Comment by balamurugana** [comment]
@xz1996 This is already fixed in the `master`

**Comment by xz1996** [comment]
@balamurugana OK, thank for your kind reply.

**Comment by kannappanr** [comment]
@xz1996 Closing this issue as answered. We will be making a release in a couple of days. So, the next release will have the fix.
